package thriftgo_test

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/bmeddeb/phebs/internal/extract/extractors/thriftgo"
	"github.com/bmeddeb/phebs/internal/extract/sdk"
)

// agentGenerated is modeled on Apache Thrift 0.14/0.19 Go output for the
// jaeger agent service (the T19.1 spike corpus): processorMap key literals
// carry the wire method names, and client methods use the upper-first form.
const agentGenerated = `// Code generated by Thrift Compiler (0.14.1). DO NOT EDIT.
package agent

type Agent interface{}

type AgentClient struct{ c thrift.TClient }

func NewAgentClient(c thrift.TClient) *AgentClient { return &AgentClient{c: c} }

func (p *AgentClient) EmitBatch(ctx context.Context, batch *jaeger.Batch) error {
	var _args0 AgentEmitBatchArgs
	if _, err := p.Client_().Call(ctx, "emitBatch", &_args0, nil); err != nil {
		return err
	}
	return nil
}

type AgentProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
}

func NewAgentProcessor(handler Agent) *AgentProcessor {
	self0 := &AgentProcessor{processorMap: make(map[string]thrift.TProcessorFunction)}
	self0.processorMap["emitBatch"] = &agentProcessorEmitBatch{handler: handler}
	self0.processorMap["emitZipkinBatch"] = &agentProcessorEmitZipkinBatch{handler: handler}
	return self0
}
`

// legacyGenerated uses the pre-0.13 header form and a colliding method name
// to exercise both the legacy marker (D3) and call ambiguity.
const legacyGenerated = `// Autogenerated by Thrift Compiler (0.9.3)
package mirror

type Mirror interface{}

type MirrorProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
}

func NewMirrorProcessor(handler Mirror) *MirrorProcessor {
	self1 := &MirrorProcessor{processorMap: make(map[string]thrift.TProcessorFunction)}
	self1.processorMap["emitBatch"] = &mirrorProcessorEmitBatch{handler: handler}
	return self1
}
`

const consumerSource = `package app

func run(t *Transport, ctx context.Context) {
	handler := agent.NewAgentProcessor(t)
	_ = handler
	if err := t.client.EmitZipkinBatch(ctx, spans); err != nil {
		return
	}
	agent.NewAgentProcessorFactory(t)
	utils.NewAgentClientUDP("addr", 0)
}
`

type memoryCorpus struct {
	repo, commit string
	files        map[string]string
	reads        map[string]int
}

func (c *memoryCorpus) RepoName() string { return c.repo }
func (c *memoryCorpus) Commit() string   { return c.commit }
func (c *memoryCorpus) WalkFiles(ctx context.Context, visit func(string) error) error {
	paths := make([]string, 0, len(c.files))
	for filePath := range c.files {
		paths = append(paths, filePath)
	}
	sort.Strings(paths)
	for _, filePath := range paths {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := visit(filePath); err != nil {
			return err
		}
	}
	return nil
}

func (c *memoryCorpus) Read(_ context.Context, filePath string) (sdk.Blob, error) {
	content, ok := c.files[filePath]
	if !ok {
		return sdk.Blob{}, errors.New("not found")
	}
	if c.reads != nil {
		c.reads[filePath]++
	}
	digest := sha256.Sum256([]byte(content))
	return sdk.Blob{Content: content, Digest: "sha256:" + hex.EncodeToString(digest[:])}, nil
}

func extractFacts(t *testing.T, corpus *memoryCorpus) ([]sdk.Fact, sdk.Coverage) {
	t.Helper()
	var facts []sdk.Fact
	coverage, err := thriftgo.New().Extract(context.Background(), corpus, func(fact sdk.Fact) error {
		facts = append(facts, fact)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return facts, coverage
}

func factObjects(facts []sdk.Fact, predicate string) []string {
	var objects []string
	for _, fact := range facts {
		if fact.Assertion.Predicate == predicate {
			objects = append(objects, fact.Assertion.Object)
		}
	}
	sort.Strings(objects)
	return objects
}

func TestRegistrationAndCallResolution(t *testing.T) {
	corpus := &memoryCorpus{
		repo: "example.com/consumer", commit: "c0ffee",
		files: map[string]string{
			"gen/agent/agent.go": agentGenerated,
			"transport.go":       consumerSource,
		},
	}
	facts, coverage := extractFacts(t, corpus)

	if got := factObjects(facts, "REGISTERS_THRIFT_SERVICE"); !reflect.DeepEqual(got, []string{"agent.Agent"}) {
		t.Fatalf("registrations = %v", got)
	}
	if got := factObjects(facts, "CALLS_OPERATION"); !reflect.DeepEqual(got, []string{"/agent.Agent/emitZipkinBatch"}) {
		t.Fatalf("calls = %v", got)
	}
	if coverage.UnresolvedCount != 0 {
		t.Fatalf("unresolved = %d", coverage.UnresolvedCount)
	}

	for _, fact := range facts {
		switch fact.Assertion.Predicate {
		case "REGISTERS_THRIFT_SERVICE":
			if fact.Assertion.Tier != "derived" || fact.Assertion.Lineage == "" ||
				!strings.Contains(fact.Assertion.Detail, `"constructor":"NewAgentProcessor"`) {
				t.Fatalf("registration fact = %+v", fact.Assertion)
			}
		case "CALLS_OPERATION":
			if fact.Assertion.Tier != "heuristic" ||
				!strings.Contains(fact.Assertion.Detail, `"method":"emitZipkinBatch"`) ||
				!strings.Contains(fact.Assertion.Detail, `"go_method":"EmitZipkinBatch"`) {
				t.Fatalf("call fact = %+v", fact.Assertion)
			}
			if fact.Assertion.Subject != "transport.go" {
				t.Fatalf("call subject = %q", fact.Assertion.Subject)
			}
		}
	}
}

func TestAmbiguousGeneratedMethodAbstains(t *testing.T) {
	corpus := &memoryCorpus{
		repo: "example.com/consumer", commit: "c0ffee",
		files: map[string]string{
			"gen/agent/agent.go":   agentGenerated,
			"gen/mirror/mirror.go": legacyGenerated,
			"caller.go": `package app
func send(c Client, ctx context.Context) {
	c.EmitBatch(ctx, batch)
}
`,
		},
	}
	facts, coverage := extractFacts(t, corpus)
	if got := factObjects(facts, "UNRESOLVED_THRIFT_CALL"); !reflect.DeepEqual(got, []string{"EmitBatch"}) {
		t.Fatalf("unresolved calls = %v", got)
	}
	if len(factObjects(facts, "CALLS_OPERATION")) != 0 {
		t.Fatal("ambiguous method must not resolve")
	}
	if coverage.UnresolvedCount != 1 {
		t.Fatalf("unresolved = %d", coverage.UnresolvedCount)
	}
	for _, fact := range facts {
		if fact.Assertion.Predicate == "UNRESOLVED_THRIFT_CALL" &&
			!strings.Contains(fact.Assertion.Detail, `"candidate_count":2`) {
			t.Fatalf("ambiguity detail = %s", fact.Assertion.Detail)
		}
	}
}

func TestGeneratedFilesAreIndexedNotScanned(t *testing.T) {
	corpus := &memoryCorpus{
		repo: "example.com/consumer", commit: "c0ffee",
		files: map[string]string{
			// The generated file itself references processorMap and calls;
			// none of that may surface as consumer evidence.
			"gen/agent/agent.go": agentGenerated,
		},
		reads: map[string]int{},
	}
	facts, coverage := extractFacts(t, corpus)
	if len(facts) != 0 || coverage.UnresolvedCount != 0 {
		t.Fatalf("generated-only corpus emitted %d facts, %d unresolved", len(facts), coverage.UnresolvedCount)
	}
	if corpus.reads["gen/agent/agent.go"] != 1 {
		t.Fatalf("generated file read %d times, want 1", corpus.reads["gen/agent/agent.go"])
	}
}

func TestParseFailuresGapHonestly(t *testing.T) {
	corpus := &memoryCorpus{
		repo: "example.com/consumer", commit: "c0ffee",
		files: map[string]string{
			"gen/broken.go": "// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.\npackage broken\nfunc {",
			"template.go":   "package app\nfunc {{ .Name }}() {}\n",
			"empty.go":      "",
		},
	}
	facts, coverage := extractFacts(t, corpus)
	gaps := factObjects(facts, "THRIFT_EXTRACTION_GAP")
	if !reflect.DeepEqual(gaps, []string{"parse_error", "parse_error"}) {
		t.Fatalf("gaps = %v", gaps)
	}
	if coverage.UnresolvedCount != 2 {
		t.Fatalf("unresolved = %d", coverage.UnresolvedCount)
	}
}

func TestRunsAreByteIdentical(t *testing.T) {
	corpus := &memoryCorpus{
		repo: "example.com/consumer", commit: "c0ffee",
		files: map[string]string{
			"gen/agent/agent.go": agentGenerated,
			"transport.go":       consumerSource,
			"vendor/x/x.go":      "package x\n",
		},
	}
	first, _ := extractFacts(t, corpus)
	second, _ := extractFacts(t, corpus)
	if !reflect.DeepEqual(first, second) {
		t.Fatal("extraction is not deterministic")
	}
}
