// Package thriftgo extracts Go Thrift handler registrations and generated-
// client call sites (T19.3, dark/provisional scope).
//
// It is a syntactic port of the T19.1 spike's validated rules (decisions
// D3-D6 in spike/t191/README.md) into the pure-reader extractor SDK,
// mirroring the grpcgo posture: registrations are "derived" (name-bound to a
// same-repo generated processor constructor) and client call sites are
// "heuristic" (generated method name unique across the repo's stub index).
// Apache Thrift generated Go carries no filename convention, so generated
// files are recognized by their compiler header marker. The wire method name
// (which the IDL declares) is recovered from processorMap key literals, while
// the generated Go identifier is anchored independently by the string literal
// in that client's Call method. No output states or implies measured accuracy.
package thriftgo

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/bmeddeb/phebs/internal/extract/sdk"
)

const (
	domain        = "thrift-consumer"
	version       = "1.2.0"
	schemaVersion = "t19-v1"

	// go/parser is in-process and bounded by input size; cap the source so a
	// single candidate cannot hand it a pathological working set. Oversized
	// candidates are read (the worker requires every candidate read) but
	// counted as unresolved rather than parsed.
	maxGoSourceBytes = 4 << 20

	// SHA-256 of the empty adapter configuration (protodecl precedent).
	adapterConfigDigest = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
)

// New returns the stateless extractor.
func New() sdk.Extractor { return thriftGo{} }

type thriftGo struct{}

func (thriftGo) Domain() string  { return domain }
func (thriftGo) Version() string { return version }

// Candidate covers every regular Go file: generated Thrift files feed the
// name index and all other Go files are scanned for registrations and calls.
func (thriftGo) Candidate(filePath string) bool { return strings.HasSuffix(filePath, ".go") }

var (
	// Both Apache Thrift compiler header forms observed in the wild (D3):
	// modern 0.13+ "Code generated by Thrift Compiler" and the legacy
	// "Autogenerated by Thrift Compiler". Only the leading 4 KiB is checked.
	thriftGeneratedRe = regexp.MustCompile(`(?m)^// (Code generated by Thrift Compiler|Autogenerated by Thrift Compiler)`)
	processorCtorRe   = regexp.MustCompile(`^New([A-Z]\w*)Processor$`)
	wireMethodRe      = regexp.MustCompile(`^[A-Za-z_]\w*$`)
)

// serviceIndex is the cross-file state retained between the generated-code
// pass and the scan pass: derived names and provenance strings only, never
// blob content, preserving the SDK's one-blob-at-a-time contract.
type serviceIndex struct {
	// processorCtor maps a generated New<Service>Processor constructor name
	// to every independently anchored service; registration resolves only
	// when exactly one matches.
	processorCtor map[string][]*serviceEntry
	// methods maps a generated Go method name to (entry, wire name) pairs;
	// call sites resolve only when exactly one service declares the name.
	methods map[string][]methodEntry
	// skip records files pass 1 fully handled (generated files and files
	// that already produced a gap fact) so pass 2 neither re-reads nor
	// double-counts them.
	skip map[string]bool
}

type serviceEntry struct {
	scope    string // generated package name, e.g. "agent"
	name     string // service name, e.g. "Agent"
	stubPath string // generated file that anchored this entry
	lineage  string // provisional lineage id derived from stubPath
}

func (e *serviceEntry) fqn() string { return e.scope + "." + e.name }

type methodEntry struct {
	entry *serviceEntry
	wire  string // IDL wire method name, e.g. "emitBatch"
}

// lineageID reuses the T12.3 provisional recipe: file-scoped, machine-visibly
// provisional until cross-repository contract lineage is promoted.
func lineageID(repo, stubPath string) string {
	h := sha256.Sum256([]byte(repo + "\x00" + stubPath))
	return "provisional_repo_path_v1_" + hex.EncodeToString(h[:])
}

func (thriftGo) Extract(ctx context.Context, corpus sdk.Corpus, emit sdk.Emit) (sdk.Coverage, error) {
	coverage := sdk.Coverage{Protocols: []string{
		"generated-name-anchored-v1", "lineage-provisional-repo-path-v1",
		"resolution-syntactic-v1", "thrift-go",
	}}
	index := &serviceIndex{
		processorCtor: map[string][]*serviceEntry{},
		methods:       map[string][]methodEntry{},
		skip:          map[string]bool{},
	}

	// Pass 1: every Go file is read once to recognize generated Thrift code
	// by its compiler header and build the name index. Generated files
	// declare no facts of their own in this domain — declared operations
	// belong to thriftdecl.
	err := corpus.WalkFiles(ctx, func(relPath string) error {
		if !strings.HasSuffix(relPath, ".go") {
			return nil
		}
		blob, err := corpus.Read(ctx, relPath)
		if err != nil {
			return err
		}
		if len(blob.Content) > maxGoSourceBytes {
			index.skip[relPath] = true
			unresolved, err := emitFileGap(relPath, blob, "source_too_large", emit)
			coverage.UnresolvedCount += unresolved
			return err
		}
		if !isGeneratedThrift(blob.Content) {
			return nil
		}
		index.skip[relPath] = true
		if err := indexGenerated(corpus.RepoName(), relPath, blob.Content, index); err != nil {
			// A malformed generated file is an honest abstention, not a run
			// failure: its services simply stay unresolvable.
			unresolved, emitErr := emitFileGap(relPath, blob, "parse_error", emit)
			coverage.UnresolvedCount += unresolved
			return emitErr
		}
		return nil
	})
	if err != nil {
		return coverage, err
	}

	// Pass 2: every non-generated Go file is re-read and scanned for
	// registrations and call sites, citing the pass-2 blob.
	err = corpus.WalkFiles(ctx, func(relPath string) error {
		if !strings.HasSuffix(relPath, ".go") || index.skip[relPath] {
			return nil
		}
		blob, err := corpus.Read(ctx, relPath)
		if err != nil {
			return err
		}
		unresolved, err := scanFile(relPath, blob, index, emit)
		if err != nil {
			return err
		}
		coverage.UnresolvedCount += unresolved
		return nil
	})
	return coverage, err
}

func isGeneratedThrift(content string) bool {
	head := content
	if len(head) > 4096 {
		head = head[:4096]
	}
	return thriftGeneratedRe.MatchString(head)
}

// indexGenerated extracts service identities from one generated file: the
// package clause supplies the scope, New<Service>Processor constructors
// anchor services, and processorMap key literals inside those constructor
// bodies supply the wire method universe (D4). A generated client method joins
// to that universe only when its own Call expression contains the exact wire
// literal. This reads the compiler's actual identifier instead of trying to
// reproduce version- and option-sensitive Go publicizing rules.
func indexGenerated(repo, relPath, content string, index *serviceIndex) error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, relPath, content, parser.SkipObjectResolution)
	if err != nil {
		return err
	}
	scope := file.Name.Name
	clientMethods := generatedClientMethods(file)
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv != nil || fn.Body == nil {
			continue
		}
		match := processorCtorRe.FindStringSubmatch(fn.Name.Name)
		if match == nil {
			continue
		}
		entry := &serviceEntry{
			scope: scope, name: match[1], stubPath: relPath,
			lineage: lineageID(repo, relPath),
		}
		index.processorCtor[fn.Name.Name] = appendEntryUnique(index.processorCtor[fn.Name.Name], entry)
		for _, wire := range processorMapKeys(fn) {
			goNames := clientMethods[entry.name+"\x00"+wire]
			if len(goNames) != 1 {
				continue
			}
			goName := goNames[0]
			index.methods[goName] = appendMethodUnique(index.methods[goName], methodEntry{entry: entry, wire: wire})
		}
	}
	return nil
}

// generatedClientMethods maps (service, wire method) to the exact Go method
// identifier emitted by Apache Thrift. Generated methods are accepted only
// when their receiver is <Service>Client and a Call expression in that method
// carries a single matching wire literal.
func generatedClientMethods(file *ast.File) map[string][]string {
	methods := make(map[string][]string)
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || fn.Body == nil {
			continue
		}
		receiver := receiverTypeName(fn)
		if !strings.HasSuffix(receiver, "Client") {
			continue
		}
		service := strings.TrimSuffix(receiver, "Client")
		if service == "" {
			continue
		}
		for _, wire := range clientCallWires(fn) {
			key := service + "\x00" + wire
			methods[key] = appendStringUnique(methods[key], fn.Name.Name)
		}
	}
	return methods
}

func receiverTypeName(fn *ast.FuncDecl) string {
	if fn.Recv == nil || len(fn.Recv.List) != 1 {
		return ""
	}
	expression := fn.Recv.List[0].Type
	if pointer, ok := expression.(*ast.StarExpr); ok {
		expression = pointer.X
	}
	identifier, _ := expression.(*ast.Ident)
	if identifier == nil {
		return ""
	}
	return identifier.Name
}

func clientCallWires(fn *ast.FuncDecl) []string {
	var wires []string
	ast.Inspect(fn.Body, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		selector, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || selector.Sel.Name != "Call" {
			return true
		}
		for _, argument := range call.Args {
			literal, ok := argument.(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				continue
			}
			wire, err := strconv.Unquote(literal.Value)
			if err == nil && wireMethodRe.MatchString(wire) {
				wires = appendStringUnique(wires, wire)
			}
		}
		return true
	})
	return wires
}

func appendStringUnique(values []string, candidate string) []string {
	for _, value := range values {
		if value == candidate {
			return values
		}
	}
	return append(values, candidate)
}

// processorMapKeys collects the string keys of `x.processorMap[...] = ...`
// assignments inside a constructor body.
func processorMapKeys(fn *ast.FuncDecl) []string {
	var keys []string
	ast.Inspect(fn.Body, func(node ast.Node) bool {
		assign, ok := node.(*ast.AssignStmt)
		if !ok {
			return true
		}
		for _, lhs := range assign.Lhs {
			indexExpr, ok := lhs.(*ast.IndexExpr)
			if !ok {
				continue
			}
			selector, ok := indexExpr.X.(*ast.SelectorExpr)
			if !ok || selector.Sel.Name != "processorMap" {
				continue
			}
			literal, ok := indexExpr.Index.(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				continue
			}
			wire, err := strconv.Unquote(literal.Value)
			if err != nil || !wireMethodRe.MatchString(wire) {
				continue
			}
			keys = append(keys, wire)
		}
		return true
	})
	return keys
}

func appendEntryUnique(entries []*serviceEntry, candidate *serviceEntry) []*serviceEntry {
	for _, entry := range entries {
		if entry.fqn() == candidate.fqn() && entry.stubPath == candidate.stubPath {
			return entries
		}
	}
	return append(entries, candidate)
}

func appendMethodUnique(entries []methodEntry, candidate methodEntry) []methodEntry {
	for _, entry := range entries {
		if entry.entry.fqn() == candidate.entry.fqn() && entry.wire == candidate.wire &&
			entry.entry.stubPath == candidate.entry.stubPath {
			return entries
		}
	}
	return append(entries, candidate)
}

// emitFileGap records a source-backed unresolved assertion so the trusted
// worker can independently reconcile Coverage.UnresolvedCount. An empty file
// contains no possible call or registration site, so reading it is complete
// coverage even though go/parser cannot form a file AST for it.
func emitFileGap(relPath string, blob sdk.Blob, reason string, emit sdk.Emit) (int, error) {
	if len(blob.Content) == 0 {
		return 0, nil
	}
	const predicate = "THRIFT_EXTRACTION_GAP"
	endLine := 1 + strings.Count(blob.Content[:len(blob.Content)-1], "\n")
	err := emit(sdk.Fact{
		Atom: sdk.AtomInput{
			SchemaVersion: schemaVersion, BlobDigest: blob.Digest,
			StartByte: 0, EndByte: len(blob.Content), RuleID: "thriftgo-file-gap-v1",
			AdapterConfigDigest: adapterConfigDigest,
			FactFingerprint:     predicate + "|" + reason,
		},
		Path: relPath, StartLine: 1, EndLine: endLine,
		Assertion: sdk.AssertionInput{
			Predicate: predicate, Subject: relPath, Object: reason,
			Tier: "unresolved", CodeRole: classifyRole(relPath, blob.Content),
			Detail: `{"schema":"thriftgo-gap-detail-v1","reason":` + strconv.Quote(reason) + `}`,
		},
	})
	if err != nil {
		return 0, err
	}
	return 1, nil
}

// scanFile emits registration and call-site facts for one non-generated Go
// file. Parse failures are honest abstentions (testdata and templates
// legitimately contain invalid Go); they count as unresolved. Oversized
// files were already gapped in pass 1.
func scanFile(relPath string, blob sdk.Blob, index *serviceIndex, emit sdk.Emit) (int, error) {
	if len(blob.Content) > maxGoSourceBytes {
		return emitFileGap(relPath, blob, "source_too_large", emit)
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, relPath, blob.Content, parser.SkipObjectResolution)
	if err != nil {
		return emitFileGap(relPath, blob, "parse_error", emit)
	}
	role := classifyRole(relPath, blob.Content)
	tokenFile := fset.File(file.Pos())

	unresolved := map[string]struct{}{}
	var emitErr error
	emitSpan := func(predicate, object, lineage, rule, tier, detail string, node ast.Node) {
		if emitErr != nil {
			return
		}
		start := tokenFile.Offset(node.Pos())
		end := tokenFile.Offset(node.End())
		if start < 0 || end <= start || end > len(blob.Content) {
			emitErr = fmt.Errorf("invalid parser span for %s in %s", object, relPath)
			return
		}
		emitErr = emit(sdk.Fact{
			Atom: sdk.AtomInput{
				SchemaVersion: schemaVersion, BlobDigest: blob.Digest,
				StartByte: start, EndByte: end, RuleID: rule,
				AdapterConfigDigest: adapterConfigDigest,
				FactFingerprint:     predicate + "|" + object,
			},
			Path:      relPath,
			StartLine: fset.Position(node.Pos()).Line,
			EndLine:   fset.Position(node.End()).Line,
			Assertion: sdk.AssertionInput{
				Predicate: predicate, Subject: relPath, Object: object,
				Lineage: lineage,
				Tier:    tier, CodeRole: role, Detail: detail,
			},
		})
	}
	emitUnresolved := func(predicate, object, rule, detail string, node ast.Node) {
		emitSpan(predicate, object, "", rule, "unresolved", detail, node)
		if emitErr == nil {
			// Count distinct unresolved assertions, matching the worker
			// rather than raw source occurrences.
			unresolved[predicate+"\x00"+object] = struct{}{}
		}
	}

	ast.Inspect(file, func(n ast.Node) bool {
		if emitErr != nil {
			return false
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		callee := ""
		switch fun := call.Fun.(type) {
		case *ast.Ident:
			callee = fun.Name
		case *ast.SelectorExpr:
			callee = fun.Sel.Name
		default:
			return true
		}
		if ctors := index.processorCtor[callee]; len(ctors) > 0 {
			if len(ctors) == 1 {
				entry := ctors[0]
				emitSpan("REGISTERS_THRIFT_SERVICE", entry.fqn(), entry.lineage,
					"thriftgo-register-v1", "derived", registerDetail(callee), call)
			} else {
				emitUnresolved("UNRESOLVED_THRIFT_REGISTRATION", callee,
					"thriftgo-register-ambiguous-v1", ambiguousRegisterDetail(callee, len(ctors)), call)
			}
			return true
		}
		// Method-shaped caller evidence requires a selector with at least one
		// argument (D5), mirroring grpcgo.
		if _, isSelector := call.Fun.(*ast.SelectorExpr); !isSelector || len(call.Args) == 0 {
			return true
		}
		methods := index.methods[callee]
		switch len(methods) {
		case 0:
		case 1:
			method := methods[0]
			emitSpan("CALLS_OPERATION", "/"+method.entry.fqn()+"/"+method.wire,
				method.entry.lineage, "thriftgo-call-v1", "heuristic",
				callDetail(method.wire, callee), call)
		default:
			// Ambiguous generated method name across services: syntactic
			// resolution abstains rather than guesses. Emit one unresolved
			// candidate edge per canonical operation so downstream queries do
			// not need to reproduce the compiler's Go-name transformation.
			candidates := make(map[string]struct{}, len(methods))
			for _, method := range methods {
				operation := "/" + method.entry.fqn() + "/" + method.wire
				candidates[operation] = struct{}{}
			}
			operations := make([]string, 0, len(candidates))
			for operation := range candidates {
				operations = append(operations, operation)
			}
			sort.Strings(operations)
			for _, operation := range operations {
				emitUnresolved("UNRESOLVED_THRIFT_CALL", operation,
					"thriftgo-call-ambiguous-v2",
					ambiguousCallDetail(callee, len(methods), operation), call)
			}
		}
		return true
	})
	return len(unresolved), emitErr
}

func registerDetail(constructor string) string {
	return `{"schema":"thriftgo-register-detail-v1","constructor":` + strconv.Quote(constructor) + `}`
}

func callDetail(wire, goName string) string {
	return `{"schema":"thriftgo-call-detail-v1","method":` + strconv.Quote(wire) +
		`,"go_method":` + strconv.Quote(goName) + `}`
}

func ambiguousCallDetail(goName string, candidates int, operation string) string {
	return `{"schema":"thriftgo-call-ambiguity-v1","method":` + strconv.Quote(goName) +
		`,"candidate_count":` + strconv.Itoa(candidates) +
		`,"candidate_operation":` + strconv.Quote(operation) + `}`
}

func ambiguousRegisterDetail(constructor string, candidates int) string {
	return `{"schema":"thriftgo-register-ambiguity-v1","constructor":` + strconv.Quote(constructor) +
		`,"candidate_count":` + strconv.Itoa(candidates) + `}`
}

// ---- code_role classification, ported verbatim from grpcgo/T11.1 ----

const (
	roleProduction = "production"
	roleTest       = "test"
	roleMock       = "mock"
	roleGenerated  = "generated"
	roleVendor     = "vendor"
)

var (
	generatedHeaderRe = regexp.MustCompile(`(?m)^(//|#).*(Code generated .* DO NOT EDIT|Autogenerated by Thrift Compiler)`)
	mockHeaderRe      = regexp.MustCompile(`Code generated by MockGen|Code generated by mockery|Code generated by counterfeiter`)
)

// classifyRole implements the spike's validated precedence:
// vendor > mock > generated > test > production.
func classifyRole(relPath, content string) string {
	if pathHasSegment(relPath, "vendor") {
		return roleVendor
	}
	head := content
	if len(head) > 4096 {
		head = head[:4096]
	}
	if mockHeaderRe.MatchString(head) || pathHasMockSegment(relPath) {
		return roleMock
	}
	if generatedHeaderRe.MatchString(head) {
		return roleGenerated
	}
	if strings.HasSuffix(relPath, "_test.go") || hasTestSegment(relPath) {
		return roleTest
	}
	return roleProduction
}

func hasTestSegment(relPath string) bool {
	for _, seg := range strings.Split(relPath, "/") {
		if seg == "tests" || seg == "testing" || seg == "testdata" {
			return true
		}
	}
	return false
}

func pathHasSegment(relPath, want string) bool {
	for _, seg := range strings.Split(relPath, "/") {
		if seg == want {
			return true
		}
	}
	return false
}

func pathHasMockSegment(relPath string) bool {
	parts := strings.Split(relPath, "/")
	for i, seg := range parts {
		isFile := i == len(parts)-1
		if seg == "mock" || seg == "mocks" || seg == "mocksgen" || seg == "fake" || seg == "fakes" {
			return true
		}
		if isFile && (strings.HasPrefix(seg, "mock_") || strings.HasPrefix(seg, "fake_") ||
			strings.HasSuffix(seg, "_mock.go") || strings.HasSuffix(seg, "_mock_test.go") ||
			strings.HasSuffix(seg, "_fake.go") || strings.HasSuffix(seg, "_fake_test.go")) {
			return true
		}
	}
	return false
}
