package grpcgo

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"testing"

	"github.com/bmeddeb/phebs/internal/extract/sdk"
)

type memoryCorpus struct {
	repo, commit string
	files        map[string]string
}

func (c memoryCorpus) RepoName() string { return c.repo }
func (c memoryCorpus) Commit() string   { return c.commit }
func (c memoryCorpus) WalkFiles(ctx context.Context, visit func(string) error) error {
	paths := make([]string, 0, len(c.files))
	for filePath := range c.files {
		paths = append(paths, filePath)
	}
	sort.Strings(paths)
	for _, filePath := range paths {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := visit(filePath); err != nil {
			return err
		}
	}
	return nil
}
func (c memoryCorpus) Read(_ context.Context, filePath string) (sdk.Blob, error) {
	content, ok := c.files[filePath]
	if !ok {
		return sdk.Blob{}, fmt.Errorf("no such file %q", filePath)
	}
	sum := sha256.Sum256([]byte(content))
	return sdk.Blob{Content: content, Digest: "sha256:" + hex.EncodeToString(sum[:])}, nil
}

const stubGreeter = `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package helloworld

const (
	Greeter_SayHello_FullMethodName = "/helloworld.Greeter/SayHello"
	Greeter_SayAgain_FullMethodName = "/helloworld.Greeter/SayAgain"
)

var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {}
`

const stubBilling = `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package billing

const (
	Billing_Charge_FullMethodName   = "/acme.billing.Billing/Charge"
	Billing_SayHello_FullMethodName = "/acme.billing.Billing/SayHello"
)

var Billing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acme.billing.Billing",
}

func RegisterBillingServer(s grpc.ServiceRegistrar, srv BillingServer) {}
`

const consumerMain = `package main

func run(ctx context.Context, client helloworld.GreeterClient, b billing.BillingClient) {
	resp, _ := client.SayAgain(ctx, req)
	_, _ = b.Charge(ctx, invoice)
	_, _ = client.SayHello(ctx, req) // ambiguous: declared by two services
	unrelated.Frobnicate(ctx, resp)
}

func serve(s grpc.ServiceRegistrar) {
	helloworld.RegisterGreeterServer(s, &impl{})
}
`

func fixtureCorpus() memoryCorpus {
	return memoryCorpus{
		repo: "example.com/app", commit: "c0ffee",
		files: map[string]string{
			"api/helloworld/helloworld_grpc.pb.go": stubGreeter,
			"api/billing/billing_grpc.pb.go":       stubBilling,
			"cmd/app/main.go":                      consumerMain,
			"vendor/dep/dep.go":                    "package dep\n",
			"internal/notgo.txt":                   "not a candidate",
		},
	}
}

func collect(t *testing.T, corpus memoryCorpus) ([]sdk.Fact, sdk.Coverage) {
	t.Helper()
	var facts []sdk.Fact
	ctx := sdk.WithDiagnosticCounters(context.Background())
	cov, err := New().Extract(ctx, corpus, func(f sdk.Fact) error {
		facts = append(facts, f)
		return nil
	})
	if err != nil {
		t.Fatalf("extract: %v", err)
	}
	return facts, cov
}

func TestExtractResolvesCallsRegistrationsAndAbstains(t *testing.T) {
	facts, cov := collect(t, fixtureCorpus())
	if diagnosticValue(cov, "generated_stubs_recognized") != 2 ||
		diagnosticValue(cov, "first_pass_reads") != 2 ||
		diagnosticValue(cov, "second_pass_reads") != 2 ||
		diagnosticValue(cov, "registrations_found") != 1 ||
		diagnosticValue(cov, "call_sites_found") != 2 ||
		diagnosticValue(cov, "ambiguous_calls") == 0 {
		t.Fatalf("diagnostics = %+v", cov.Diagnostics)
	}

	got := map[string]sdk.Fact{}
	for _, f := range facts {
		got[f.Assertion.Predicate+" "+f.Assertion.Object] = f
	}
	call, ok := got["CALLS_OPERATION /helloworld.Greeter/SayAgain"]
	if !ok {
		t.Fatalf("missing unique call-site fact; got %v", keys(got))
	}
	if call.Assertion.Tier != "heuristic" || call.Assertion.CodeRole != "production" {
		t.Fatalf("call tier/role = %q/%q", call.Assertion.Tier, call.Assertion.CodeRole)
	}
	if !strings.HasPrefix(call.Assertion.Lineage, "provisional_repo_path_v1_") {
		t.Fatalf("call lineage = %q", call.Assertion.Lineage)
	}
	if _, ok := got["CALLS_OPERATION /acme.billing.Billing/Charge"]; !ok {
		t.Fatalf("missing billing call fact")
	}
	reg, ok := got["REGISTERS_GRPC_SERVICE helloworld.Greeter"]
	if !ok {
		t.Fatalf("missing registration fact")
	}
	if reg.Assertion.Tier != "derived" {
		t.Fatalf("registration tier = %q", reg.Assertion.Tier)
	}
	// SayHello is declared by two services: syntactic resolution abstains.
	for key := range got {
		if strings.HasPrefix(key, "CALLS_OPERATION ") && strings.Contains(key, "SayHello") {
			t.Fatalf("ambiguous positive method emitted: %s", key)
		}
	}
	gap, ok := got["UNRESOLVED_GRPC_CALL SayHello"]
	if !ok || gap.Assertion.Tier != "unresolved" ||
		!strings.Contains(gap.Assertion.Detail, `"candidate_count":2`) {
		t.Fatalf("ambiguous call gap = %+v", gap)
	}
	if cov.UnresolvedCount != 1 {
		t.Fatalf("unresolved = %d, want 1 (ambiguous SayHello)", cov.UnresolvedCount)
	}
	// Frobnicate is not in any stub index: silently out of domain, not unresolved.
	for _, f := range facts {
		var detail map[string]any
		if err := json.Unmarshal([]byte(f.Assertion.Detail), &detail); err != nil {
			t.Fatalf("detail is not valid JSON: %q", f.Assertion.Detail)
		}
	}
}

func diagnosticValue(coverage sdk.Coverage, name string) int64 {
	for _, counter := range coverage.Diagnostics {
		if counter.Name == name {
			return counter.Value
		}
	}
	return -1
}

func TestDiagnosticCountersAreExplicitOptIn(t *testing.T) {
	coverage, err := New().Extract(
		context.Background(), fixtureCorpus(), func(sdk.Fact) error { return nil },
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(coverage.Diagnostics) != 0 {
		t.Fatalf("diagnostics enabled without request: %+v", coverage.Diagnostics)
	}
}

func TestSpansCiteExactSource(t *testing.T) {
	corpus := fixtureCorpus()
	facts, _ := collect(t, corpus)
	for _, f := range facts {
		content := corpus.files[f.Path]
		if f.Atom.StartByte < 0 || f.Atom.EndByte > len(content) || f.Atom.StartByte >= f.Atom.EndByte {
			t.Fatalf("span out of range: %+v", f.Atom)
		}
		span := content[f.Atom.StartByte:f.Atom.EndByte]
		if !strings.Contains(span, "(") {
			t.Fatalf("span %q does not look like a call expression", span)
		}
		if f.StartLine <= 0 || f.EndLine < f.StartLine {
			t.Fatalf("line range invalid: %d..%d", f.StartLine, f.EndLine)
		}
	}
}

func TestTwoRunByteIdenticalDeterminism(t *testing.T) {
	run := func() string {
		facts, cov := collect(t, fixtureCorpus())
		payload, err := json.Marshal(struct {
			Facts    []sdk.Fact
			Coverage sdk.Coverage
		}{facts, cov})
		if err != nil {
			t.Fatalf("marshal: %v", err)
		}
		return string(payload)
	}
	if a, b := run(), run(); a != b {
		t.Fatalf("two runs differ:\n%s\n%s", a, b)
	}
}

func TestClassifyRolePrecedence(t *testing.T) {
	mockHeader := "// Code generated by MockGen. DO NOT EDIT.\npackage x\n"
	rows := []struct {
		path, content, want string
	}{
		{"vendor/x/mock_y.go", mockHeader, roleVendor},
		{"a/mocks/client.go", "package mocks\n", roleMock},
		{"a/b/gen.go", "// Code generated by protoc. DO NOT EDIT.\npackage b\n", roleGenerated},
		{"a/b/c_test.go", "package b\n", roleTest},
		{"tests/integration/x.go", "package x\n", roleTest},
		{"a/b/c.go", mockHeader, roleMock},
		{"a/b/c.go", "package b\n", roleProduction},
	}
	for _, row := range rows {
		if got := classifyRole(row.path, row.content); got != row.want {
			t.Fatalf("classifyRole(%q) = %q, want %q", row.path, got, row.want)
		}
	}
}

func TestUnparseableAndOversizedCountUnresolved(t *testing.T) {
	corpus := fixtureCorpus()
	corpus.files["broken/broken.go"] = "package \x00 not go"
	corpus.files["big/big.go"] = "package big\n" + strings.Repeat("// pad\n", 0) +
		"var x = `" + strings.Repeat("a", maxGoSourceBytes) + "`\n"
	facts, cov := collect(t, corpus)
	// ambiguous SayHello + broken + oversized
	if cov.UnresolvedCount != 3 {
		t.Fatalf("unresolved = %d, want 3", cov.UnresolvedCount)
	}
	var unresolved int
	for _, fact := range facts {
		if fact.Assertion.Tier == "unresolved" {
			unresolved++
			content := corpus.files[fact.Path]
			if fact.Atom.StartByte < 0 || fact.Atom.EndByte > len(content) ||
				fact.Atom.StartByte >= fact.Atom.EndByte {
				t.Fatalf("unresolved span out of range: %+v", fact)
			}
		}
	}
	if unresolved != 3 {
		t.Fatalf("emitted unresolved assertions = %d, want 3", unresolved)
	}
}

func TestRegistrationNameCollisionAbstains(t *testing.T) {
	stub := func(service string) string {
		return `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package health

const Health_Check_FullMethodName = "/` + service + `/Check"
var Health_ServiceDesc = grpc.ServiceDesc{ServiceName: "` + service + `"}
func RegisterHealthServer(s grpc.ServiceRegistrar, srv HealthServer) {}
`
	}
	corpus := memoryCorpus{
		repo: "example.com/app", commit: "c0ffee",
		files: map[string]string{
			"api/alpha/health_grpc.pb.go": stub("alpha.Health"),
			"api/beta/health_grpc.pb.go":  stub("beta.Health"),
			"cmd/app/main.go": `package main
func serve(s grpc.ServiceRegistrar) {
	alpha.RegisterHealthServer(s, &alphaImpl{})
	beta.RegisterHealthServer(s, &betaImpl{})
}
`,
		},
	}
	facts, cov := collect(t, corpus)
	if cov.UnresolvedCount != 1 {
		t.Fatalf("unresolved = %d, want one distinct registration assertion", cov.UnresolvedCount)
	}
	if len(facts) != 2 {
		t.Fatalf("facts = %d, want two source-backed registration gaps", len(facts))
	}
	for _, fact := range facts {
		if fact.Assertion.Predicate != "UNRESOLVED_GRPC_REGISTRATION" ||
			fact.Assertion.Object != "RegisterHealthServer" || fact.Assertion.Tier != "unresolved" ||
			!strings.Contains(fact.Assertion.Detail, `"candidate_count":2`) {
			t.Fatalf("collision emitted a positive or malformed fact: %+v", fact)
		}
	}
}

func TestDuplicateFQNAcrossLineagesAbstains(t *testing.T) {
	corpus := memoryCorpus{
		repo: "example.com/app", commit: "c0ffee",
		files: map[string]string{
			"api/v1/health_grpc.pb.go": strings.ReplaceAll(stubBilling,
				"acme.billing.Billing", "shared.Health"),
			"api/v2/health_grpc.pb.go": strings.ReplaceAll(stubBilling,
				"acme.billing.Billing", "shared.Health"),
			"cmd/app/main.go": "package main\nfunc run(ctx context.Context, c Client) { c.Charge(ctx, req) }\n",
		},
	}
	facts, cov := collect(t, corpus)
	if cov.UnresolvedCount != 1 || len(facts) != 1 {
		t.Fatalf("facts/coverage = %d/%+v, want one lineage ambiguity", len(facts), cov)
	}
	fact := facts[0]
	if fact.Assertion.Predicate != "UNRESOLVED_GRPC_CALL" || fact.Assertion.Object != "Charge" ||
		fact.Assertion.Lineage != "" || !strings.Contains(fact.Assertion.Detail, `"candidate_count":2`) {
		t.Fatalf("duplicate FQN was merged: %+v", fact)
	}
}

func TestPackageLessServiceResolves(t *testing.T) {
	stub := `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package greeter

const Greeter_SayHello_FullMethodName = "/Greeter/SayHello"
var Greeter_ServiceDesc = grpc.ServiceDesc{ServiceName: "Greeter"}
func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {}
`
	consumer := `package main
func run(ctx context.Context, client greeter.GreeterClient, s grpc.ServiceRegistrar) {
	client.SayHello(ctx, req)
	greeter.RegisterGreeterServer(s, &impl{})
}
`
	corpus := memoryCorpus{repo: "example.com/app", commit: "c0ffee", files: map[string]string{
		"api/greeter_grpc.pb.go": stub,
		"cmd/app/main.go":        consumer,
	}}
	facts, cov := collect(t, corpus)
	if cov.UnresolvedCount != 0 {
		t.Fatalf("package-less service unresolved = %d", cov.UnresolvedCount)
	}
	got := map[string]bool{}
	for _, fact := range facts {
		got[fact.Assertion.Predicate+" "+fact.Assertion.Object] = true
		if fact.Assertion.Lineage == "" {
			t.Fatalf("package-less fact has no lineage: %+v", fact)
		}
	}
	for _, want := range []string{
		"CALLS_OPERATION /Greeter/SayHello",
		"REGISTERS_GRPC_SERVICE Greeter",
	} {
		if !got[want] {
			t.Fatalf("missing package-less fact %q; got %v", want, got)
		}
	}
}

func TestNoAccuracyLanguageInOutputs(t *testing.T) {
	facts, cov := collect(t, fixtureCorpus())
	blob, _ := json.Marshal(facts)
	all := strings.ToLower(string(blob) + strings.Join(cov.Protocols, " "))
	for _, banned := range []string{"accuracy", "precision", "recall", "validated"} {
		if strings.Contains(all, banned) {
			t.Fatalf("output contains accuracy-claim language %q", banned)
		}
	}
}

func keys(m map[string]sdk.Fact) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
