/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Regenerate with: npm run gen:api
 * (reads ui/openapi.json; refresh it from a live backend with `npm run spec:dump`
 *  — requires the Go toolchain at the repo root: go run ../scripts/openapi-dump)
 * The checked-in openapi.json snapshot means the UI build never needs a
 * running backend; refresh the snapshot when the huma API changes.
 */

export interface paths {
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API analytics */
        get: operations["get-api-analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API audit */
        get: operations["get-api-audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API blame */
        get: operations["get-api-blame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/code-navigation-indexing/enqueue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enqueue-code-navigation-indexing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/code-navigation-indexing/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["plan-code-navigation-indexing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/code-navigation-indexing/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API code navigation indexing providers */
        get: operations["get-api-code-navigation-indexing-providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/code-navigation-indexing/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API code navigation indexing status */
        get: operations["get-api-code-navigation-indexing-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API commit */
        get: operations["get-api-commit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API commits */
        get: operations["get-api-commits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contract_atlas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API contract atlas */
        get: operations["get-api-contract-atlas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contract_atlas/operation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API contract atlas operation */
        get: operations["get-api-contract-atlas-operation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API diff */
        get: operations["get-api-diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/find_definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API find definitions */
        get: operations["get-api-find-definitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/find_references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API find references */
        get: operations["get-api-find-references"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folder_contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API folder contents */
        get: operations["get-api-folder-contents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API health */
        get: operations["get-api-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API hover */
        get: operations["get-api-hover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lifecycle-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API lifecycle status */
        get: operations["get-api-lifecycle-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API reindex */
        post: operations["post-api-reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repo-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API repo status */
        get: operations["list-api-repo-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API repos */
        get: operations["list-api-repos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retention-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API retention status */
        get: operations["get-api-retention-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API search */
        get: operations["get-api-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one exact authorized service */
        get: operations["get-service"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List one authorized repository's services */
        get: operations["list-services"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API source */
        get: operations["get-api-source"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream_search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Streamed search (SSE): `results` events per shard batch, then `done` with aggregate stats */
        get: operations["stream-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API tree */
        get: operations["get-api-tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API version */
        get: operations["get-api-version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyticsOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AnalyticsOutBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            avg_duration_ms: number;
            daily: components["schemas"]["DayCount"][] | null;
            top_repos: components["schemas"]["RepoCount"][] | null;
            /** Format: int64 */
            total_searches: number;
        };
        AuditEvent: {
            action: string;
            actor_email?: string;
            actor_id?: string;
            api_key_id?: string;
            auth_method?: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            source_ip?: string;
            /** Format: int64 */
            status: number;
            target?: string;
        };
        AuditOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuditOutBody.json
             */
            readonly $schema?: string;
            events: components["schemas"]["AuditEvent"][] | null;
            has_more: boolean;
        };
        Authority: {
            active_catalog_generation: string;
            active_desired_generation: string;
            active_source_generation: string;
            /** Format: int64 */
            catalog_control_revision: number;
            current_catalog_generation: string;
            digest: string;
            expression_digest: string;
            /** Format: int64 */
            incarnation: number;
            /** Format: int64 */
            path_bytes: number;
            /** Format: int64 */
            path_count: number;
            path_digest: string;
            /** Format: int64 */
            predicate_atoms: number;
            /** Format: int64 */
            predicate_bytes: number;
            predicate_policy: string;
            repository: string;
            repository_search_generation: string;
            repository_source_generation: string;
            revision_branch: string;
            revision_commit: string;
            revision_selector: string;
            schema: string;
            service_key: string;
            service_state_digest: string;
            /** Format: int64 */
            service_state_revision: number;
            state_summary_digest: string;
            /** Format: int64 */
            state_summary_revision: number;
            status: string;
            topology_policy: string;
        };
        BlameLine: {
            commit_id: string;
            content: string;
            /** Format: int64 */
            line: number;
            /** Format: int64 */
            original_line: number;
            original_path: string;
        };
        BlameResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BlameResult.json
             */
            readonly $schema?: string;
            commits: components["schemas"]["GitCommit"][] | null;
            lines: components["schemas"]["BlameLine"][] | null;
            path: string;
            revision: string;
            truncated: boolean;
        };
        CallerJobProjection: {
            /** Format: int64 */
            attempts: number;
            status: string;
        };
        CapacityStatus: {
            /** @enum {string} */
            completeness: "exact" | "unavailable";
            /** Format: date-time */
            observed_at?: string;
            /** @enum {string} */
            pressure: "normal" | "collect" | "refuse" | "unavailable";
            /** Format: int64 */
            total_bytes?: number;
            /** Format: int64 */
            used_bytes?: number;
            /** Format: int64 */
            used_percent?: number;
        };
        CertificateAnalysisUnit: {
            digest: string;
            name: string;
            primary_paths: string[] | null;
            supporting_paths: string[] | null;
            typed_index_kind?: string;
            typed_index_path?: string;
            typed_index_posture: string;
        };
        CertificateAttempt: {
            commit: string;
            extractor: string;
            failure?: string;
            run_id: string;
            status: string;
            unit_digest?: string;
        };
        CertificateCandidateScope: {
            /** Format: int64 */
            base_source_file_count?: number;
            /** Format: int64 */
            corpus_declared_bytes: number;
            corpus_digest: string;
            /** Format: int64 */
            corpus_file_count: number;
            /** Format: int64 */
            excluded_go_test_file_count?: number;
            /** Format: int64 */
            excluded_scip_definition_count: number;
            /** Format: int64 */
            excluded_scip_document_count: number;
            /** Format: int64 */
            excluded_scip_occurrence_count: number;
            /** Format: int64 */
            excluded_source_declared_bytes: number;
            /** Format: int64 */
            excluded_source_file_count: number;
            /** Format: int64 */
            excluded_source_required_count: number;
            manifest_digest: string;
            plane: string;
            /** Format: int64 */
            planned_declared_bytes: number;
            planned_digest: string;
            /** Format: int64 */
            planned_file_count: number;
            /** Format: int64 */
            planned_required_file_count: number;
            typed_input?: components["schemas"]["CertificateTypedInput"];
        };
        CertificateDomainOutcome: {
            candidate_control_failure?: boolean;
            disposition: string;
            extractor: string;
            generation_digest: string;
            receipt?: components["schemas"]["CertificateOutcomeReceipt"];
            receipt_schema: string;
            receipt_state: string;
        };
        CertificateOutcomeReceipt: {
            bytes: components["schemas"]["ExtractionOperationDomainBytes"];
            counts: components["schemas"]["ExtractionOperationDomainCounts"];
            disposition: string;
            domain: string;
            /** Format: int64 */
            extractor_ms: number;
            extractor_version: string;
            /** Format: int64 */
            inventory_ms: number;
            limits: components["schemas"]["ExtractionOperationDomainLimits"];
            /** Format: int64 */
            opened_source_ms: number;
            reason: string;
            refusal?: components["schemas"]["Receipt"];
            schema: string;
            /** Format: int64 */
            staging_ms: number;
        };
        CertificateRepository: {
            analysis_unit?: components["schemas"]["CertificateAnalysisUnit"];
            indexed_commit?: string;
            repository: string;
            runs: components["schemas"]["CertificateRun"][] | null;
            scip_index: string;
            scope_posture: string;
        };
        CertificateRun: {
            /** Format: int64 */
            assertion_count: number;
            /** Format: int64 */
            atom_count: number;
            /** Format: int64 */
            candidate_file_count: number;
            candidate_scope?: components["schemas"]["CertificateCandidateScope"];
            commit?: string;
            /** Format: int64 */
            corpus_file_count: number;
            domain: string;
            evidence_scope_posture?: string;
            extractor?: string;
            failures?: string[] | null;
            fresh: boolean;
            /** Format: int64 */
            gitlink_count?: number;
            gitlink_digest?: string;
            gitlink_sample_paths?: string[] | null;
            gitlink_sample_truncated?: boolean;
            inventory_policy?: string;
            latest_attempt?: components["schemas"]["CertificateAttempt"];
            outcome?: components["schemas"]["CertificateDomainOutcome"];
            protocols?: string[] | null;
            /** Format: int64 */
            read_bytes: number;
            /** Format: int64 */
            read_file_count: number;
            run_id?: string;
            source_scope_digest?: string;
            status: string;
            unit_digest?: string;
            /** Format: int64 */
            unresolved_count: number;
        };
        CertificateTypedInput: {
            /** Format: int64 */
            declared_bytes: number;
            digest?: string;
            kind: string;
            object_id?: string;
            path?: string;
            present: boolean;
        };
        Chunk: {
            content: string;
            ranges: components["schemas"]["Range"][] | null;
            /** Format: int64 */
            start_line: number;
        };
        CodePosition: {
            /** Format: int32 */
            character: number;
            /** Format: int32 */
            line: number;
        };
        CodeRange: {
            end: components["schemas"]["CodePosition"];
            start: components["schemas"]["CodePosition"];
        };
        CommitListResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CommitListResult.json
             */
            readonly $schema?: string;
            commits: components["schemas"]["GitCommit"][] | null;
            has_more: boolean;
            /** Format: int64 */
            offset: number;
            revision: string;
        };
        CommitResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CommitResult.json
             */
            readonly $schema?: string;
            changes: components["schemas"]["GitFileChange"][] | null;
            commit: components["schemas"]["GitCommit"];
            revision: string;
        };
        ContractCatalogClaim: {
            assertion_id: string;
            code_role?: string;
            detail?: unknown;
            lineage?: string;
            object: string;
            predicate: string;
            run_id: string;
            sources: components["schemas"]["ContractCatalogSource"][] | null;
            sources_truncated: boolean;
            tier: string;
        };
        ContractCatalogFieldDetail: {
            cardinality: string;
            map?: components["schemas"]["ContractCatalogMapShape"];
            name: string;
            oneof?: string;
            schema: string;
            type?: components["schemas"]["ContractCatalogTypeReference"];
        };
        ContractCatalogFieldShape: {
            declaration: components["schemas"]["ContractCatalogClaim"];
            detail: components["schemas"]["ContractCatalogFieldDetail"];
            /** Format: int64 */
            field_number: number;
            nested?: components["schemas"]["ContractCatalogMessage"];
            object: string;
        };
        ContractCatalogImportContext: {
            /** Format: int64 */
            count: number;
            digest: string;
            paths?: string[] | null;
            truncated: boolean;
        };
        ContractCatalogItem: {
            declaration: components["schemas"]["ContractCatalogClaim"];
            declaration_lineage: string;
            kind: string;
            method?: string;
            operation?: string;
            package?: string;
            protocol: string;
            repository: string;
            service_fqn: string;
        };
        ContractCatalogList: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ContractCatalogList.json
             */
            readonly $schema?: string;
            caveat: string;
            coverage: components["schemas"]["CoverageCertificate"];
            coverage_digest: string;
            items: components["schemas"]["ContractCatalogItem"][] | null;
            pagination: components["schemas"]["ContractCatalogPagination"];
            query: components["schemas"]["ContractCatalogQuery"];
            schema_version: string;
        };
        ContractCatalogMapShape: {
            key: components["schemas"]["ContractCatalogTypeReference"];
            value: components["schemas"]["ContractCatalogTypeReference"];
        };
        ContractCatalogMessage: {
            declaration?: components["schemas"]["ContractCatalogClaim"];
            declaration_name?: string;
            fields?: components["schemas"]["ContractCatalogFieldShape"][] | null;
            kind?: string;
            raw: string;
            reason?: string;
            state: string;
            synthetic?: boolean;
            truncated: boolean;
            truncation_reasons?: string[] | null;
        };
        ContractCatalogOperation: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ContractCatalogOperation.json
             */
            readonly $schema?: string;
            callers: components["schemas"]["ContractCatalogRelationship"][] | null;
            caveat: string;
            coverage: components["schemas"]["CoverageCertificate"];
            coverage_digest: string;
            declaration: components["schemas"]["ContractCatalogClaim"];
            declaration_lineage: string;
            fact_detail: components["schemas"]["ContractCatalogOperationFactDetail"];
            implementations: components["schemas"]["ContractCatalogRelationship"][] | null;
            method: string;
            operation: string;
            relationship_limit_reason?: string;
            relationships_truncated: boolean;
            repository: string;
            request: components["schemas"]["ContractCatalogMessage"];
            response: components["schemas"]["ContractCatalogMessage"];
            schema_version: string;
            service_fqn: string;
            shape_truncated: boolean;
            unresolved_candidates: components["schemas"]["ContractCatalogRelationship"][] | null;
        };
        ContractCatalogOperationFactDetail: {
            client_streaming: boolean;
            oneway?: boolean;
            request: components["schemas"]["ContractCatalogTypeReference"];
            response: components["schemas"]["ContractCatalogTypeReference"];
            schema: string;
            server_streaming: boolean;
        };
        ContractCatalogPagination: {
            complete: boolean;
            next_cursor?: string;
            reason?: string;
            truncated: boolean;
        };
        ContractCatalogQuery: {
            lineage?: string;
            package?: string;
            protocol?: string;
            repository?: string;
        };
        ContractCatalogRelationship: {
            claim: components["schemas"]["ContractCatalogClaim"];
            classification: string;
            kind: string;
            reason?: string;
        };
        ContractCatalogSource: {
            assertion_id: string;
            atom_id: string;
            commit: string;
            /** Format: int64 */
            end_byte: number;
            /** Format: int64 */
            end_line: number;
            path: string;
            repository: string;
            run_id: string;
            /** Format: int64 */
            start_byte: number;
            /** Format: int64 */
            start_line: number;
        };
        ContractCatalogTypeReference: {
            declaration?: string;
            imports?: components["schemas"]["ContractCatalogImportContext"];
            kind?: string;
            raw: string;
            reason?: string;
            resolution: string;
        };
        CoverageCertificate: {
            digest: string;
            domains: string[] | null;
            repositories: components["schemas"]["CertificateRepository"][] | null;
            /** Format: int64 */
            repository_count: number;
            schema_version: string;
        };
        DayCount: {
            /** Format: int64 */
            count: number;
            date: string;
        };
        DefinitionResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DefinitionResult.json
             */
            readonly $schema?: string;
            available: boolean;
            location?: components["schemas"]["Location"];
            symbol?: string;
        };
        DiffResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DiffResult.json
             */
            readonly $schema?: string;
            base?: string;
            files: components["schemas"]["GitFileChange"][] | null;
            head: string;
            patch: string;
            truncated: boolean;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ExtractionJobProjection: {
            /** Format: int64 */
            attempts: number;
            refusal?: components["schemas"]["Receipt"];
            status: string;
        };
        ExtractionOperationDomainBytes: {
            /** Format: int64 */
            excluded_source_declared: number;
            /** Format: int64 */
            opened_source: number;
            /** Format: int64 */
            planned_declared: number;
        };
        ExtractionOperationDomainCounts: {
            /** Format: int64 */
            assertions: number;
            /** Format: int64 */
            atoms: number;
            /** Format: int64 */
            candidate_files: number;
            /** Format: int64 */
            corpus_files: number;
            /** Format: int64 */
            excluded_scip_definitions: number;
            /** Format: int64 */
            excluded_scip_documents: number;
            /** Format: int64 */
            excluded_scip_occurrences: number;
            /** Format: int64 */
            excluded_source_files: number;
            /** Format: int64 */
            facts: number;
            /** Format: int64 */
            opened_source_attempts: number;
            /** Format: int64 */
            opened_source_files: number;
            /** Format: int64 */
            staged_chunks: number;
            /** Format: int64 */
            staged_rows: number;
            /** Format: int64 */
            unresolved: number;
        };
        ExtractionOperationDomainLimits: {
            /** Format: int64 */
            abort_wall_ms: number;
            /** Format: int64 */
            aggregate_staged_rows: number;
            /** Format: int64 */
            aggregate_wall_ms: number;
            /** Format: int64 */
            corpus_files: number;
            /** Format: int64 */
            domain_staged_rows: number;
            /** Format: int64 */
            domain_wall_ms: number;
            /** Format: int64 */
            facts: number;
            /** Format: int64 */
            max_serial_domains: number;
            /** Format: int64 */
            mirror_lock_ms: number;
            /** Format: int64 */
            opened_source_attempts: number;
            /** Format: int64 */
            opened_source_bytes: number;
            /** Format: int64 */
            opened_source_files: number;
            /** Format: int64 */
            outcome_wall_ms: number;
            /** Format: int64 */
            scheduler_identity_bytes: number;
            /** Format: int64 */
            source_blob_bytes: number;
            /** Format: int64 */
            typed_input_bytes: number;
        };
        FileResult: {
            chunks: components["schemas"]["Chunk"][] | null;
            language?: string;
            path: string;
            ref?: string;
            repo: string;
        };
        FolderOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FolderOutBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["TreeEntry"][] | null;
        };
        GitCommit: {
            author: components["schemas"]["GitIdentity"];
            committer: components["schemas"]["GitIdentity"];
            id: string;
            message: string;
            parent_ids: string[] | null;
            short_id: string;
            subject: string;
        };
        GitFileChange: {
            /** Format: int64 */
            additions?: number;
            binary?: boolean;
            /** Format: int64 */
            deletions?: number;
            old_path?: string;
            path: string;
            /** Format: int64 */
            similarity?: number;
            status: string;
        };
        GitIdentity: {
            email: string;
            name: string;
            /** Format: date-time */
            time: string;
        };
        HealthOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutBody.json
             */
            readonly $schema?: string;
            /** @example ok */
            status: string;
        };
        HoverInfo: {
            display_name?: string;
            documentation?: string[] | null;
            encoding: string;
            kind?: string;
            language?: string;
            range: components["schemas"]["CodeRange"];
            signature?: string;
            symbol: string;
        };
        HoverResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HoverResult.json
             */
            readonly $schema?: string;
            available: boolean;
            hover?: components["schemas"]["HoverInfo"];
        };
        IndexedRevision: {
            branch: string;
            commit: string;
            selector: string;
        };
        Job: {
            /** Format: int64 */
            attempts: number;
            /** Format: date-time */
            claimed_at?: string;
            claimed_by?: string;
            claimed_by_truncated?: boolean;
            /** Format: date-time */
            created_at: string;
            error?: string;
            error_truncated?: boolean;
            /** Format: date-time */
            finished_at?: string;
            force?: boolean;
            /** Format: date-time */
            heartbeat_at?: string;
            /** Format: date-time */
            not_before?: string;
            status: string;
            target: string;
            target_truncated?: boolean;
        };
        Location: {
            encoding: string;
            path: string;
            range: components["schemas"]["CodeRange"];
            repo: string;
            revision: string;
        };
        OwnerStatus: {
            /** Format: date-time */
            attempted_at?: string;
            backlog: boolean;
            /** @enum {string} */
            completeness: "exact" | "lower_bound" | "unavailable";
            /** Format: int64 */
            deleted: number;
            /** Format: int64 */
            logical_bytes: number;
            /** Format: int64 */
            member_bytes: number;
            name: string;
            /** Format: int64 */
            root_bytes: number;
            /** Format: int64 */
            scanned: number;
            /** @enum {string} */
            state: "not_run" | "ok" | "error";
        };
        Range: {
            /** Format: int64 */
            end_col: number;
            /** Format: int64 */
            end_line: number;
            /** Format: int64 */
            start_col: number;
            /** Format: int64 */
            start_line: number;
        };
        Receipt: {
            classification: string;
            dimension: string;
            generation_kind: string;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            observed: number;
            schema: string;
            stage: string;
        };
        ReferencesResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReferencesResult.json
             */
            readonly $schema?: string;
            available: boolean;
            locations: components["schemas"]["Location"][] | null;
            symbol?: string;
            truncated?: boolean;
        };
        ReindexInBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReindexInBody.json
             */
            readonly $schema?: string;
            /** @description rebuild even when HEAD is already indexed */
            force?: boolean;
            /** @example github.com/foo/bar */
            repo: string;
        };
        ReindexOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReindexOutBody.json
             */
            readonly $schema?: string;
            enqueued: boolean;
        };
        Repo: {
            clone_url: string;
            default_branch?: string;
            deleting?: boolean;
            display_name?: string;
            external_code_host_type?: string;
            external_code_host_url?: string;
            external_id?: string;
            /** Format: date-time */
            indexed_at?: string;
            indexed_commit_hash?: string;
            indexed_revisions?: components["schemas"]["IndexedRevision"][] | null;
            is_archived: boolean;
            is_fork: boolean;
            is_public: boolean;
            latest_indexing_job_status?: string;
            metadata?: {
                [key: string]: unknown;
            };
            name: string;
            /** Format: date-time */
            pushed_at?: string;
            web_url?: string;
        };
        RepoCount: {
            /** Format: int64 */
            count: number;
            name: string;
        };
        RepoStatus: {
            analysis_unit?: components["schemas"]["State"];
            clone_url: string;
            connections?: string[] | null;
            default_branch?: string;
            deleting?: boolean;
            display_name?: string;
            external_code_host_type?: string;
            external_code_host_url?: string;
            external_id?: string;
            /** Format: date-time */
            indexed_at?: string;
            indexed_commit_hash?: string;
            indexed_revisions?: components["schemas"]["IndexedRevision"][] | null;
            is_archived: boolean;
            is_fork: boolean;
            is_public: boolean;
            last_caller_job?: components["schemas"]["CallerJobProjection"];
            last_caller_job_state: string;
            last_extraction_job?: components["schemas"]["ExtractionJobProjection"];
            last_extraction_job_state: string;
            last_index_job?: components["schemas"]["Job"];
            last_index_job_state: string;
            last_resolver_job?: components["schemas"]["ResolverJobProjection"];
            last_resolver_job_state: string;
            latest_indexing_job_status?: string;
            metadata?: {
                [key: string]: unknown;
            };
            name: string;
            orphaned: boolean;
            /** Format: date-time */
            pushed_at?: string;
            web_url?: string;
        };
        ResolverJobProjection: {
            /** Format: int64 */
            attempts: number;
            status: string;
        };
        Result: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Result.json
             */
            readonly $schema?: string;
            files: components["schemas"]["FileResult"][] | null;
            scope_receipt?: components["schemas"]["ScopeReceipt"];
            stats: components["schemas"]["Stats"];
        };
        RetentionComponentStatus: {
            allocation: components["schemas"]["RetentionStatusAllocation"];
            byte_metrics: components["schemas"]["RetentionStatusByteMetric"][] | null;
            count: components["schemas"]["RetentionStatusMetric"];
            id: string;
            /** Format: int64 */
            scanned_identities: number;
            truncated: boolean;
        };
        RetentionDataVolumeStatus: {
            available_bytes: components["schemas"]["RetentionStatusMetric"];
            total_bytes: components["schemas"]["RetentionStatusMetric"];
        };
        RetentionOwnerStatus: {
            accumulating: boolean;
            components: components["schemas"]["RetentionComponentStatus"][] | null;
            decision_relation: string;
            id: string;
            retention_control: components["schemas"]["RetentionStatusControl"];
            scope: string;
        };
        RetentionStatus: {
            $schema: string;
            data_volume: components["schemas"]["RetentionDataVolumeStatus"];
            limits: components["schemas"]["RetentionStatusLimits"];
            owners: components["schemas"]["RetentionOwnerStatus"][] | null;
            /** @enum {string} */
            schema: "phebs-retention-status-v1";
            /** @enum {string} */
            warning_code: "unbounded_historical_publication_retention";
        };
        RetentionStatusAllocation: {
            /** Format: int64 */
            reported_identities: number;
            /** Format: int64 */
            scan_identities: number;
        };
        RetentionStatusByteMetric: {
            /** @enum {string} */
            completeness: "exact" | "lower_bound" | "unavailable";
            /** @enum {string} */
            kind: "logical_encoded" | "canonical_content" | "canonical_receipt" | "apparent_file" | "physical_database";
            /** @enum {string} */
            unit: "bytes";
            /** Format: int64 */
            value: number | null;
        };
        RetentionStatusControl: {
            config_key: string;
            /** @enum {string} */
            default_state: "disabled" | "enabled";
            positive_lifetime_effect: string;
        };
        RetentionStatusLimits: {
            /** Format: int64 */
            aggregate_reported_identity_allocation: number;
            /** Format: int64 */
            aggregate_scan_identity_allocation: number;
            /** Format: int64 */
            components: number;
            /** Format: int64 */
            encoded_response_byte_limit: number;
            /** Format: int64 */
            owners: number;
            /** Format: int64 */
            reported_identities_per_summary: number;
            /** Format: int64 */
            scan_identities_per_summary: number;
        };
        RetentionStatusMetric: {
            /** @enum {string} */
            completeness: "exact" | "lower_bound" | "unavailable";
            /** @enum {string} */
            unit: "identities" | "bytes";
            /** Format: int64 */
            value: number | null;
        };
        ScopeReceipt: {
            digest: string;
            expression_digest: string;
            kind: string;
            membership_policy: string;
            repository?: string;
            /** Format: int64 */
            result_files: number;
            /** Format: int64 */
            result_matches: number;
            result_set_digest: string;
            revisions: components["schemas"]["ScopeRevision"][] | null;
            schema: string;
            service_authority?: components["schemas"]["Authority"];
            service_key?: string;
            service_status?: string;
        };
        ScopeRevision: {
            commit: string;
            repository: string;
        };
        Service: {
            active_catalog_generation?: string;
            active_desired_generation?: string;
            active_source_generation?: string;
            /** Format: date-time */
            changed_at: string;
            /** Format: int64 */
            control_revision: number;
            desired_catalog_generation?: string;
            desired_generation?: string;
            desired_source_generation?: string;
            display_name: string;
            disposition: string;
            /** Format: int64 */
            distinct_path_count: number;
            /** Format: int64 */
            incarnation: number;
            key: string;
            /** Format: int64 */
            membership_count: number;
            origin: string;
            reason?: string;
            removed: boolean;
            repository: string;
            role_counts: components["schemas"]["ServiceRoleCounts"];
            state_digest: string;
            status: string;
            /** Format: int64 */
            successor_count: number;
        };
        ServiceAuthority: {
            id: string;
            kind: string;
            override_id?: string;
            override_version?: string;
            version: string;
        };
        ServiceDetail: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ServiceDetail.json
             */
            readonly $schema?: string;
            memberships: components["schemas"]["ServiceMembership"][] | null;
            repository: components["schemas"]["ServiceRepository"];
            schema: string;
            service: components["schemas"]["Service"];
            successors: string[] | null;
        };
        ServiceInventory: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ServiceInventory.json
             */
            readonly $schema?: string;
            filters: components["schemas"]["ServiceInventoryQuery"];
            pagination: components["schemas"]["ServicePagination"];
            repository: components["schemas"]["ServiceRepository"];
            schema: string;
            services: components["schemas"]["Service"][] | null;
        };
        ServiceInventoryQuery: {
            disposition?: string;
            include_removed?: boolean;
            repository: string;
            status?: string;
        };
        ServiceMembership: {
            origin: string;
            path: string;
            role: string;
        };
        ServicePagination: {
            next_cursor?: string;
            order: string;
            /** Format: int64 */
            page_size: number;
            /** Format: int64 */
            returned: number;
        };
        ServiceRepository: {
            /** Format: int64 */
            accepted_file_count: number;
            authority: components["schemas"]["ServiceAuthority"];
            /** Format: int64 */
            catalog_control_revision: number;
            catalog_digest: string;
            catalog_generation: string;
            /** Format: int64 */
            catalog_service_count: number;
            /** Format: int64 */
            conflict_count: number;
            /** Format: int64 */
            current_count: number;
            /** Format: int64 */
            live_service_count: number;
            /** Format: date-time */
            published_at: string;
            repository: string;
            source_commit: string;
            /** Format: int64 */
            source_file_count: number;
            source_kind: string;
            /** Format: int64 */
            stale_count: number;
            /** Format: int64 */
            state_control_revision: number;
            /** Format: date-time */
            state_updated_at: string;
            /** Format: int64 */
            tombstone_count: number;
            /** Format: int64 */
            unavailable_count: number;
            /** Format: int64 */
            unowned_file_count: number;
        };
        ServiceRoleCounts: {
            /** Format: int64 */
            generated: number;
            /** Format: int64 */
            primary: number;
            /** Format: int64 */
            shared: number;
            /** Format: int64 */
            supporting: number;
            /** Format: int64 */
            typed: number;
        };
        SourceOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SourceOutBody.json
             */
            readonly $schema?: string;
            content: string;
            /** @enum {string} */
            encoding: "utf8" | "base64";
            /** Format: int64 */
            size: number;
        };
        State: {
            digest: string;
            name: string;
            /** Format: int64 */
            primary_path_count: number;
            primary_paths: string[] | null;
            schema: string;
            search_index_posture: string;
            /** Format: int64 */
            supporting_path_count: number;
            supporting_paths: string[] | null;
            typed_index?: components["schemas"]["TypedIndex"];
            typed_index_posture: string;
        };
        Stats: {
            /** Format: int64 */
            duration_ms: number;
            /** Format: int64 */
            file_count: number;
            /** Format: int64 */
            match_count: number;
        };
        Status: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Status.json
             */
            readonly $schema?: string;
            capacity: components["schemas"]["CapacityStatus"];
            owners: components["schemas"]["OwnerStatus"][] | null;
            policy: components["schemas"]["StatusPolicy"];
            /** @enum {string} */
            schema: "phebs-lifecycle-status-v1";
        };
        StatusPolicy: {
            enabled: boolean;
            /** Format: int64 */
            hard_watermark_percent: number;
            /** Format: int64 */
            max_candidates_per_turn: number;
            /** Format: int64 */
            max_deletes_per_turn: number;
            /** Format: int64 */
            max_queries_per_turn: number;
            /** Format: int64 */
            owners: number;
            /** Format: int64 */
            resume_watermark_percent: number;
            /** Format: int64 */
            soft_watermark_percent: number;
        };
        StreamErr: {
            message: string;
        };
        TreeEntry: {
            name: string;
            /** Format: int64 */
            size?: number;
            type: string;
        };
        TreeOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TreeOutBody.json
             */
            readonly $schema?: string;
            paths: string[] | null;
        };
        TypedIndex: {
            kind: string;
            path: string;
        };
        TypedIndexEnqueue: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TypedIndexEnqueue.json
             */
            readonly $schema?: string;
            expected_revision: string;
            idempotency_key: string;
            profile: string;
            provider: string;
            /** @enum {string} */
            purpose: "publish" | "canary" | "dry-run";
            repository: string;
            request_digest: string;
        };
        TypedIndexPreview: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TypedIndexPreview.json
             */
            readonly $schema?: string;
            commit: string;
            idempotency_key: string;
            request_digest: string;
            resource_profile: string;
            schema: string;
            selection: components["schemas"]["TypedIndexSelection"];
        };
        TypedIndexProvider: {
            available: boolean;
            id: string;
            name: string;
        };
        TypedIndexProviders: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TypedIndexProviders.json
             */
            readonly $schema?: string;
            providers: components["schemas"]["TypedIndexProvider"][] | null;
            schema: string;
        };
        TypedIndexSelection: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TypedIndexSelection.json
             */
            readonly $schema?: string;
            expected_revision: string;
            profile: string;
            provider: string;
            /** @enum {string} */
            purpose: "publish" | "canary" | "dry-run";
            repository: string;
        };
        TypedIndexView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TypedIndexView.json
             */
            readonly $schema?: string;
            available: boolean;
            checked_purpose: string;
            commit: string;
            config_profile: string;
            current_commit: string;
            job_state: string;
            profile: string;
            provider: string;
            reason: string;
            repository: string;
            request_digest: string;
            resource_profile: string;
            revision: string;
            schema: string;
            /** @enum {string} */
            state: "absent" | "current" | "stale" | "planning" | "indexing" | "validating" | "publishing" | "failed" | "canceled";
            target_profile: string;
        };
        VersionOutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/VersionOutBody.json
             */
            readonly $schema?: string;
            capabilities?: string[] | null;
            /** @example 0.2.1-dev */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-api-analytics": {
        parameters: {
            query?: {
                /** @description window in days ending today, default 30 */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-audit": {
        parameters: {
            query?: {
                offset?: number;
                /** @description events per page, default 50 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-blame": {
        parameters: {
            query: {
                repo: string;
                /** @description commit-ish; defaults to the indexed commit */
                ref?: string;
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlameResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "enqueue-code-navigation-indexing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypedIndexEnqueue"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypedIndexView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "plan-code-navigation-indexing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypedIndexSelection"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypedIndexPreview"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-code-navigation-indexing-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypedIndexProviders"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-code-navigation-indexing-status": {
        parameters: {
            query: {
                repository: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypedIndexView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-commit": {
        parameters: {
            query: {
                repo: string;
                /** @description commit-ish; defaults to the indexed commit */
                ref?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-commits": {
        parameters: {
            query: {
                repo: string;
                /** @description commit-ish; defaults to the indexed commit */
                ref?: string;
                /** @description optional file path; follows renames */
                path?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitListResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-contract-atlas": {
        parameters: {
            query?: {
                repository?: string;
                package?: string;
                protocol?: string;
                lineage?: string;
                page_size?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractCatalogList"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-contract-atlas-operation": {
        parameters: {
            query: {
                repository: string;
                lineage: string;
                operation: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractCatalogOperation"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-diff": {
        parameters: {
            query: {
                repo: string;
                /** @description base commit; defaults to head's first parent */
                base?: string;
                /** @description head commit; defaults to the indexed commit */
                head?: string;
                /** @description optional path filter */
                path?: string;
                context_lines?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-find-definitions": {
        parameters: {
            query: {
                repo: string;
                /** @description full commit object ID; defaults to the indexed commit */
                ref?: string;
                path: string;
                /** @description zero-based source line */
                line?: number;
                /** @description zero-based character offset */
                character?: number;
                encoding?: "utf8" | "utf16" | "utf32";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-find-references": {
        parameters: {
            query: {
                repo: string;
                /** @description full commit object ID; defaults to the indexed commit */
                ref?: string;
                path: string;
                /** @description zero-based source line */
                line?: number;
                /** @description zero-based character offset */
                character?: number;
                encoding?: "utf8" | "utf16" | "utf32";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferencesResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-folder-contents": {
        parameters: {
            query: {
                repo: string;
                /** @description commit-ish; default HEAD */
                ref?: string;
                /** @description directory; default repo root */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-hover": {
        parameters: {
            query: {
                repo: string;
                /** @description full commit object ID; defaults to the indexed commit */
                ref?: string;
                path: string;
                /** @description zero-based source line */
                line?: number;
                /** @description zero-based character offset */
                character?: number;
                encoding?: "utf8" | "utf16" | "utf32";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoverResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-lifecycle-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReindexInBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-repo-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoStatus"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repo"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-retention-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Phebs-Warning-Code"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-search": {
        parameters: {
            query: {
                q: string;
                /** @description documents shown, default 50, cap 500 */
                max_matches?: number;
                /** @description context lines per match, cap 10 */
                context_lines?: number;
                /** @description shared search scope */
                scope?: "all_code" | "service";
                /** @description required only for service scope */
                repository?: string;
                /** @description required only for service scope */
                service_key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-service": {
        parameters: {
            query: {
                repository: string;
                service_key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-services": {
        parameters: {
            query: {
                repository: string;
                status?: string;
                disposition?: string;
                include_removed?: boolean;
                page_size?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInventory"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-source": {
        parameters: {
            query: {
                repo: string;
                /** @description commit-ish; default HEAD */
                ref?: string;
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "stream-search": {
        parameters: {
            query: {
                q: string;
                /** @description documents shown, default 50, cap 500 */
                max_matches?: number;
                /** @description context lines per match, cap 10 */
                context_lines?: number;
                /** @description shared search scope */
                scope?: "all_code" | "service";
                /** @description required only for service scope */
                repository?: string;
                /** @description required only for service scope */
                service_key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": ({
                        data: components["schemas"]["Stats"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "done";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["StreamErr"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "error";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Result"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "results";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["ScopeReceipt"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "scope";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    })[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-tree": {
        parameters: {
            query: {
                repo: string;
                /** @description commit-ish; default HEAD */
                ref?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOutBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
