"""T47.2b enumeration, frame and scoring-rule tests (synthetic corpus only).

Builds a tiny real git repository in a temp dir so enumerate_repo runs its
full fail-closed path (HEAD pin, clean tree, census reconciliation, client
inventory, proto mapping, site scan) without the real corpus clones. No real
round data, labels, seeds or predictions are touched.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SPIKE = Path(__file__).resolve().parent
sys.path.insert(0, str(SPIKE))
for extra in ("../t111", "../../pilot/validation"):
    sys.path.insert(0, str((SPIKE / extra).resolve()))

import label_protocol  # noqa: E402
import caller_scoring  # noqa: E402
import binding_bundle  # noqa: E402
import enumerate_universe as eu  # noqa: E402
import frames  # noqa: E402

GENERATED_CLIENT = b"""// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2

package greeterpb

import (
\tcontext "context"
\tgrpc "google.golang.org/grpc"
)

const (
\tGreeter_SayHello_FullMethodName = "/greeter.v1.Greeter/SayHello"
)

type GreeterClient interface {
\t// SayHello greets.
\tSayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
\tcc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
\treturn &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
\tout := new(HelloReply)
\terr := c.cc.Invoke(ctx, Greeter_SayHello_FullMethodName, in, out, opts...)
\tif err != nil {
\t\treturn nil, err
\t}
\treturn out, nil
}
"""

PROTO = """syntax = "proto3";

package greeter.v1;

service Greeter {
  // SayHello greets.
  rpc SayHello(HelloRequest) returns (HelloReply);
}
"""

MAIN_GO = """package main

import (
\t"context"

\tgreeterpb "example.com/mini/api/v1"
\t"google.golang.org/grpc"
)

func main() {
\tconn, _ := grpc.Dial("localhost:1")
\tclient := greeterpb.NewGreeterClient(conn)
\t_, _ = client.SayHello(context.Background(), nil)
}
"""

BARE_GO = """package main

func unrelated(g localGreeter) {
\tg.SayHello()
}
"""

IMPORT_ONLY_GO = """package main

import (
\t_ "example.com/mini/api/v1"
)

func noop() {}
"""

TEST_GO = """package main

import "testing"

func TestNothing(t *testing.T) {}
"""

MOCK_GO = """// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/mini/api/v1

package mocks

type MockGreeter struct{}
"""

OLD_CLIENT = b"""// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// protoc-gen-go-grpc v1.2.0 (no FullMethodName constants)

package greeterpb

import (
\tcontext "context"
\tgrpc "google.golang.org/grpc"
)

type GreeterClient interface {
\tSayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
\tcc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
\treturn &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
\tout := new(HelloReply)
\terr := c.cc.Invoke(ctx, "/greeter.v1.Greeter/SayHello", in, out, opts...)
\tif err != nil {
\t\treturn nil, err
\t}
\treturn out, nil
}
"""


def git(clone: Path, *args: str) -> str:
    proc = subprocess.run(["git", "-C", str(clone), *args],
                          capture_output=True, text=True, check=True)
    return proc.stdout


class SyntheticRepoCase(unittest.TestCase):
    """One commit of a synthetic module: client+proto, callers, every role."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.tmp = tempfile.TemporaryDirectory()
        cls.clone = Path(cls.tmp.name) / "mini"
        cls.clone.mkdir()
        git(cls.clone, "init", "-q", "-b", "main")
        files = {
            "go.mod": "module example.com/mini\n\ngo 1.26\n",
            "api/v1/greeter_grpc.pb.go": GENERATED_CLIENT,
            "api/v1/greeter.proto": PROTO,
            "main.go": MAIN_GO,
            "bare.go": BARE_GO,
            "importonly.go": IMPORT_ONLY_GO,
            "main_test.go": TEST_GO,
            "mocks/mock.go": MOCK_GO,
            "vendor/example.com/mini/api/v1/greeter_grpc.pb.go": GENERATED_CLIENT,
        }
        for rel, body in files.items():
            path = cls.clone / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(body if isinstance(body, bytes) else body.encode())
        (cls.clone / "link.go").symlink_to("main.go")
        git(cls.clone, "add", "-A")
        git(cls.clone, "-c", "user.email=t@example.com", "-c", "user.name=t",
            "commit", "-q", "-m", "synthetic corpus")
        cls.commit = git(cls.clone, "rev-parse", "HEAD").strip()

        cls.mappings = {
            "clients": 2,
            "mappings": [
                {"generated_path": "api/v1/greeter_grpc.pb.go",
                 "declaration_path": "api/v1/greeter.proto",
                 "generator_relative_path": "api/v1/greeter.proto", "vendored": False},
                {"generated_path": "vendor/example.com/mini/api/v1/greeter_grpc.pb.go",
                 "declaration_path": "api/v1/greeter.proto",
                 "generator_relative_path": "api/v1/greeter.proto", "vendored": True},
            ],
            "abstentions": [],
        }
        cls.census = {
            "repo": "example/mini", "derived_commit": cls.commit,
            "go_paths": 8, "regular_go_sources": 7, "nonregular_go_paths": [
                {"path": "link.go", "kind": "blob", "mode": "120000",
                 "git_object": git(cls.clone, "ls-tree", "HEAD", "link.go").split()[2]}],
        }
        cls.result = eu.enumerate_repo("example/mini", cls.clone, cls.commit,
                                       cls.census, cls.mappings)

    @classmethod
    def tearDownClass(cls) -> None:
        cls.tmp.cleanup()

    def sites_by(self, path: str) -> dict[str, list[dict]]:
        by_kind: dict[str, list[dict]] = {}
        for row in self.result["sites"]:
            if row["path"] == path:
                by_kind.setdefault(row["kind"], []).append(row)
        return by_kind


class TestEnumeration(SyntheticRepoCase):
    def test_role_classification(self) -> None:
        self.assertEqual(self.result["units"]["by_role"],
                         {"generated": 1, "mock": 1, "production": 3, "test": 1,
                          "vendor": 1})

    def test_declarations(self) -> None:
        decls = {d["generated_path"]: d for d in self.result["declarations"]}
        client = decls["api/v1/greeter_grpc.pb.go"]
        self.assertTrue(client["mapped"])
        self.assertEqual(client["operations"][0]["full_method"],
                         "/greeter.v1.Greeter/SayHello")
        self.assertEqual(client["operations"][0]["full_method_source"],
                         "full_method_constant")
        self.assertEqual(client["operations"][0]["declaration_service"], "Greeter")
        self.assertIsNotNone(client["operations"][0]["declaration_start_byte"])
        vendored = decls["vendor/example.com/mini/api/v1/greeter_grpc.pb.go"]
        self.assertTrue(vendored["vendored"])
        self.assertGreater(vendored["interface_end_byte"],
                           vendored["interface_start_byte"])

    def test_caller_sites(self) -> None:
        main = self.sites_by("main.go")
        self.assertEqual({r["symbol"] for r in main["constructor_call"]}, {"NewGreeterClient"})
        invocations = main["operation_invocation"]
        self.assertEqual({r["symbol"] for r in invocations}, {"SayHello"})
        self.assertTrue(all(r["client_aware"] for r in invocations))
        self.assertEqual(main["import_reference"][0]["symbol"], "example.com/mini/api/v1")
        self.assertEqual(main["import_reference"][0]["code_role"], "production")
        for kind, rows in main.items():
            for row in rows:
                self.assertTrue(row["site_id"].startswith(f"example/mini@{self.commit}:main.go:"))

    def test_non_aware_invocation_stays_visible(self) -> None:
        bare = self.sites_by("bare.go")
        self.assertEqual({r["symbol"] for r in bare["operation_invocation"]}, {"SayHello"})
        self.assertFalse(bare["operation_invocation"][0]["client_aware"])
        self.assertNotIn("import_reference", bare)

    def test_import_only_file(self) -> None:
        rows = self.sites_by("importonly.go")
        self.assertEqual(list(rows), ["import_reference"])

    def test_full_method_string(self) -> None:
        client = self.sites_by("api/v1/greeter_grpc.pb.go")
        strings = client.get("full_method_string", [])
        self.assertTrue(any(r["symbol"] == "/greeter.v1.Greeter/SayHello" for r in strings))

    def test_symlink_reconciled_and_targeted(self) -> None:
        self.assertEqual(self.result["nonregular"]["link_targets"],
                         {"link.go": "main.go"})

    def test_old_generator_without_constants(self) -> None:
        client = eu.extract_client("x/greeter_grpc.pb.go", OLD_CLIENT,
                                   {"x": "example.com/mini"})
        self.assertEqual(client["operations"][0]["full_method"], None)
        self.assertEqual(client["operations"][0]["source"], "client_interface")


class TestFrames(SyntheticRepoCase):
    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        cls.recall, cls.excluded = frames.build_recall_frame(cls.result["sites"])
        cls.attribution = frames.build_attribution_frame(cls.result["declarations"])

    def test_recall_excluded_reconciles_to_universe(self) -> None:
        self.assertEqual(len(self.recall) + self.excluded["excluded_total"],
                         len(self.result["sites"]))

    def test_exclusion_reasons(self) -> None:
        reasons = set(self.excluded["excluded_kinds"])
        self.assertEqual(reasons, {"import_reference",
                                   "operation_invocation_not_client_aware"})

    def test_attribution_units(self) -> None:
        self.assertEqual(len(self.attribution), 2)
        for unit in self.attribution:
            label_protocol.validate_labels([], [])  # schema import sanity
            self.assertTrue(unit["site_id"].startswith(
                f"example/mini@{self.commit}:{unit['generated_path']}:"))

    def test_plan_census_flags(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            out = Path(td)
            for name, rows in (("universe.sites.mini.jsonl", self.result["sites"]),):
                (out / name).write_text("".join(
                    json.dumps(r, sort_keys=True) + "\n" for r in rows))
            (out / "universe.declarations.jsonl").write_text("".join(
                json.dumps(d, sort_keys=True) + "\n" for d in self.result["declarations"]))
            summary = {"repositories": [{
                "repo": "example/mini", "derived_commit": self.commit,
                "eligible_units": {"regular_go_source_paths": ["main.go"]},
                "units": {"regular_go_sources": 1}}]}
            (out / "universe.json").write_text(json.dumps(summary))
            (out / "validation.parameters.json").write_text(json.dumps({
                "schema": "t472-quality-parameters-v1",
                "sampling": {"sites_per_frame_stratum": 5, "smaller_strata": "complete census"}}))
            (out / "source.census.json").write_text("{}")
            (out / "corpus.lock.json").write_text(json.dumps(
                {"repos": [{"derived": {"derived_commit": self.commit,
                                        "corpus_admitted": True}}]}))
            plan = frames.write_frames(out, out, out / "plan",
                                       out / "validation.parameters.json",
                                       out / "source.census.json",
                                       out / "corpus.lock.json")
            recall = next(f for f in plan["frames"] if f["frame_id"] == "recall")
            for stratum in recall["strata"].values():
                self.assertLessEqual(stratum["sample_size"], 5)
                self.assertEqual(stratum["census"], stratum["population"] <= 5)

    def test_draw_is_deterministic_and_seed_checked(self) -> None:
        plan = {"frames": [{"frame_id": "recall", "strata": {
            "s1": {"site_ids": [f"id{i}" for i in range(20)], "sample_size": 5}}}]}
        seed = "ab" * 32
        a = frames.draw_samples(plan, seed)
        b = frames.draw_samples(plan, seed)
        self.assertEqual(a, b)
        self.assertEqual(len(a["recall"]["s1"]), 5)
        with self.assertRaises(frames.FramesError):
            frames.draw_samples(plan, "not-hex")

    def test_candidate_projection_validates_commits(self) -> None:
        good_commit = self.commit

        def envelope(commit: str) -> dict:
            atom = {"id": "a1", "start_byte": 10, "end_byte": 20}
            return {"bundle": {
                "evidence": [{"atom": atom, "repository": "example/mini",
                              "run_id": "r1",
                              "occurrences": [{"repo": "example/mini", "run_id": "r1",
                                               "commit": commit, "path": "main.go",
                                               "start_line": 1, "end_line": 2}]}],
                "assertions": [{"id": "x", "predicate": "CALLS_OPERATION",
                                "repo": "example/mini", "run_id": "r1",
                                "supporting": ["a1"], "object": "greeter.v1.Greeter/SayHello"}]}}

        projected = frames.project_candidate_frames(envelope(good_commit), {good_commit})
        self.assertEqual(projected["precision"]["population"], 1)
        with self.assertRaises(frames.FramesError):
            frames.project_candidate_frames(envelope("f" * 40), {good_commit})


def label_row(site_id: str, invocation: str, operation: str | None = None,
              registration: str = "no", service: str | None = None) -> dict:
    return {"site_id": site_id, "invocation": invocation, "operation": operation,
            "registration": registration, "service": service,
            "expected_code_role": "production", "rationale": "synthetic test",
            "evidence": "synthetic test"}


class TestScoring(unittest.TestCase):
    params = caller_scoring.load_parameters(
        SPIKE / "validation.parameters.json")

    def test_missing_labels_invalidate(self) -> None:
        with self.assertRaises(label_protocol.LabelProtocolError):
            caller_scoring.score_recall("caller_recall", ["s1"], [], set(), {}, 1.96)

    def test_all_unsure_stratum_is_unavailable(self) -> None:
        labels = [label_row("s1", "unsure")]
        results = caller_scoring.score_recall("caller_recall", ["s1"], labels, set(), {"s1": "a"}, 1.96)
        self.assertTrue(results[0]["unavailable"])
        gate = caller_scoring.gate_quality(results, self.params)
        self.assertEqual(gate["round"], "unavailable")

    def test_recall_join(self) -> None:
        labels = [label_row("s1", "yes", "greeter.v1.Greeter/SayHello"),
                  label_row("s2", "yes", "greeter.v1.Greeter/SayHello"),
                  label_row("s3", "no"),
                  label_row("s4", "yes", "greeter.v1.Greeter/SayHello")]
        strata = {s: "repo:production" for s in ("s1", "s2", "s3", "s4")}
        results = caller_scoring.score_recall("caller_recall", ["s1", "s2", "s3", "s4"],
                                              labels, {"s1", "s4"}, strata, 1.96)
        r = results[0]
        self.assertEqual((r["yes"], r["no"], r["decided"]), (2, 1, 3))
        self.assertAlmostEqual(r["proportion"], 2 / 3)

    def test_attributed_edge_requires_operation_match(self) -> None:
        labels = [label_row("s1", "yes", "greeter.v1.Greeter/SayHello"),
                  label_row("s2", "yes", "greeter.v1.Greeter/Other")]
        strata = {"s1": "a", "s2": "a"}
        wrong = {"s1": "greeter.v1.Greeter/Wrong", "s2": "greeter.v1.Greeter/Other"}
        results = caller_scoring.score_precision_family(
            "attributed_edge_precision", ["s1", "s2"], labels, strata, 1.96, wrong)
        self.assertEqual((results[0]["yes"], results[0]["no"]), (1, 1))
        recall = caller_scoring.score_recall("attributed_edge_recall", ["s1", "s2"],
                                             labels, {"s1", "s2"}, strata, 1.96, wrong)
        self.assertEqual((recall[0]["yes"], recall[0]["no"]), (1, 1))

    def test_declaration_attribution(self) -> None:
        labels = [label_row("m1", "no", None, "yes", "greeter.v1.Greeter"),
                  label_row("m2", "no", None, "yes", "greeter.v1.Other"),
                  label_row("a1", "no", None, "no", None)]
        strata = {s: "example/mini" for s in ("m1", "m2", "a1")}
        predicted = {"m1": "greeter.v1.Greeter", "m2": "greeter.v1.Greeter"}
        results = caller_scoring.score_declaration_attribution(
            ["m1", "m2", "a1"], labels, predicted, strata, 1.96)
        r = results[0]
        self.assertEqual((r["yes"], r["no"]), (2, 1))
        self.assertEqual(r["threshold_family"], "attributed_edge")
        with self.assertRaises(caller_scoring.ScoringError):
            caller_scoring.score_declaration_attribution(
                ["m1"], labels[:1], {"m1": "not canonical!"}, {"m1": "example/mini"}, 1.96)

    def test_threshold_gate(self) -> None:
        labels = [label_row("s1", "yes", "greeter.v1.Greeter/SayHello"),
                  label_row("s2", "no")]
        strata = {"s1": "a", "s2": "a"}
        results = caller_scoring.score_precision_family(
            "caller_precision", ["s1", "s2"], labels, strata, 1.96)
        gate = caller_scoring.gate_quality(results, self.params)
        self.assertEqual(gate["round"], "fail")
        self.assertEqual(gate["failures"][0]["floor_percent"], 95)

    def test_ledger_refuses_unknown_duplicate_and_incomplete(self) -> None:
        universe = {"repositories": [{
            "repo": "example/mini", "units": {"regular_go_sources": 2},
            "eligible_units": {"regular_go_source_paths": ["a.go", "b.go"]}}]}
        good = [{"path": "a.go", "state": "analyzed"},
                {"path": "b.go", "state": "failed"}]
        ledger = caller_scoring.eligible_unit_ledger(good, universe)
        self.assertEqual(ledger["total"], 2)
        for bad in ([{"path": "nope.go", "state": "analyzed"}],
                    good + good[:1],
                    [{"path": "a.go", "state": "analyzed"}],
                    [{"path": "a.go", "state": "read"}],
                    [{"path": "a.go", "state": "analyzed"},
                     {"path": "b.go", "state": "analyzed"},
                     {"path": "a.go", "state": "analyzed"}]):
            with self.assertRaises(caller_scoring.ScoringError):
                caller_scoring.eligible_unit_ledger(bad, universe)

    def test_processing_state_gates(self) -> None:
        universe = {"repositories": [{
            "repo": "example/mini", "units": {"regular_go_sources": 100},
            "eligible_units": {"regular_go_source_paths": [f"f{i}.go" for i in range(100)]}}]}
        records = [{"path": f"f{i}.go", "state": "analyzed"} for i in range(92)]
        records += [{"path": "f92.go", "state": "partial"},
                    {"path": "f93.go", "state": "failed"}]
        records += [{"path": f"f{i}.go", "state": "excluded"} for i in range(94, 100)]
        ledger = caller_scoring.eligible_unit_ledger(records, universe)
        gate = caller_scoring.gate_processing_state(ledger, universe, self.params)
        self.assertEqual(gate["round"], "pass")
        weak = [{"path": f"f{i}.go", "state": "analyzed"} for i in range(85)] + \
               [{"path": f"f{i}.go", "state": "excluded"} for i in range(85, 100)]
        gate = caller_scoring.gate_processing_state(
            caller_scoring.eligible_unit_ledger(weak, universe), universe, self.params)
        self.assertEqual(gate["round"], "fail")
        self.assertEqual(gate["failures"][0]["gate"], "analyzed_min")

class TestBindingBundle(unittest.TestCase):
    def test_committed_bundle_validates_with_named_missing(self) -> None:
        bundle = json.loads((SPIKE / "bundle" / "preregistration.bundle.json").read_text())
        missing = binding_bundle.validate_bundle(bundle)
        self.assertIn("bundle.candidate_identities."
                      "sealed proof-bundle-v1 envelope identity and sha256 "
                      "(precision, unresolved frames)", missing)
        self.assertTrue(bundle["external_publication"]["published"] is False)
        self.assertTrue(bundle["quality_scored"] is False)
        self.assertTrue(bundle["predictions_disclosed"] is False)
        self.assertEqual(bundle["label_commitment_schema"],
                         label_protocol.LABEL_COMMITMENT_SCHEMA)

    def test_malformed_digest_refuses(self) -> None:
        bundle = binding_bundle.build_bundle(
            SPIKE.parents[1], SPIKE / "frames")
        bundle["parameters"]["sha256"] = "sha256:not-hex"
        with self.assertRaises(binding_bundle.BundleError):
            binding_bundle.validate_bundle(bundle)


if __name__ == "__main__":
    unittest.main()
