"""T47.2b enumeration, frame and scoring-rule tests (synthetic corpus only).

Builds a tiny real git repository in a temp dir so enumerate_repo runs its
full fail-closed path (HEAD pin, clean tree, census reconciliation, client
inventory, proto mapping, site scan) without the real corpus clones. No real
round data, labels, seeds or predictions are touched.
"""

from __future__ import annotations

import json
import gzip
import copy
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SPIKE = Path(__file__).resolve().parent
sys.path.insert(0, str(SPIKE))
for extra in ("../t111", "../../pilot/validation"):
    sys.path.insert(0, str((SPIKE / extra).resolve()))

import label_protocol  # noqa: E402
import caller_scoring  # noqa: E402
import binding_bundle  # noqa: E402
import enumerate_universe as eu  # noqa: E402
import frames  # noqa: E402

GENERATED_CLIENT = b"""// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2

package greeterpb

import (
\tcontext "context"
\tgrpc "google.golang.org/grpc"
)

const (
\tGreeter_SayHello_FullMethodName = "/greeter.v1.Greeter/SayHello"
)

type GreeterClient interface {
\t// SayHello greets.
\tSayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
\tcc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
\treturn &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
\tout := new(HelloReply)
\terr := c.cc.Invoke(ctx, Greeter_SayHello_FullMethodName, in, out, opts...)
\tif err != nil {
\t\treturn nil, err
\t}
\treturn out, nil
}
"""

PROTO = """syntax = "proto3";

package greeter.v1;

service Greeter {
  // SayHello greets.
  rpc SayHello(HelloRequest) returns (HelloReply);
}
"""

MAIN_GO = """package main

import (
\t"context"

\tgreeterpb "example.com/mini/api/v1"
\t"google.golang.org/grpc"
)

func main() {
\tconn, _ := grpc.Dial("localhost:1")
\tclient := greeterpb.NewGreeterClient(conn)
\t_, _ = client.SayHello(context.Background(), nil)
}
"""

BARE_GO = """package main

func unrelated(g localGreeter) {
\tg.SayHello()
}
"""

IMPORT_ONLY_GO = """package main

import (
\t_ "example.com/mini/api/v1"
)

func noop() {}
"""

TEST_GO = """package main

import "testing"

func TestNothing(t *testing.T) {}
"""

MOCK_GO = """// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/mini/api/v1

package mocks

type MockGreeter struct{}
"""

OLD_CLIENT = b"""// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// protoc-gen-go-grpc v1.2.0 (no FullMethodName constants)

package greeterpb

import (
\tcontext "context"
\tgrpc "google.golang.org/grpc"
)

type GreeterClient interface {
\tSayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
\tcc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
\treturn &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
\tout := new(HelloReply)
\terr := c.cc.Invoke(ctx, "/greeter.v1.Greeter/SayHello", in, out, opts...)
\tif err != nil {
\t\treturn nil, err
\t}
\treturn out, nil
}
"""


def git(clone: Path, *args: str) -> str:
    proc = subprocess.run(["git", "-C", str(clone), *args],
                          capture_output=True, text=True, check=True)
    return proc.stdout


class SyntheticRepoCase(unittest.TestCase):
    """One commit of a synthetic module: client+proto, callers, every role."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.tmp = tempfile.TemporaryDirectory()
        cls.clone = Path(cls.tmp.name) / "mini"
        cls.clone.mkdir()
        git(cls.clone, "init", "-q", "-b", "main")
        files = {
            "go.mod": "module example.com/mini\n\ngo 1.26\n",
            "api/v1/greeter_grpc.pb.go": GENERATED_CLIENT,
            "api/v1/greeter.proto": PROTO,
            "main.go": MAIN_GO,
            "bare.go": BARE_GO,
            "importonly.go": IMPORT_ONLY_GO,
            "main_test.go": TEST_GO,
            "mocks/mock.go": MOCK_GO,
            "vendor/example.com/mini/api/v1/greeter_grpc.pb.go": GENERATED_CLIENT,
        }
        for rel, body in files.items():
            path = cls.clone / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(body if isinstance(body, bytes) else body.encode())
        (cls.clone / "link.go").symlink_to("main.go")
        git(cls.clone, "add", "-A")
        git(cls.clone, "-c", "user.email=t@example.com", "-c", "user.name=t",
            "commit", "-q", "-m", "synthetic corpus")
        cls.commit = git(cls.clone, "rev-parse", "HEAD").strip()

        cls.mappings = {
            "clients": 2,
            "mappings": [
                {"generated_path": "api/v1/greeter_grpc.pb.go",
                 "declaration_path": "api/v1/greeter.proto",
                 "generator_relative_path": "api/v1/greeter.proto", "vendored": False},
                {"generated_path": "vendor/example.com/mini/api/v1/greeter_grpc.pb.go",
                 "declaration_path": "api/v1/greeter.proto",
                 "generator_relative_path": "api/v1/greeter.proto", "vendored": True},
            ],
            "abstentions": [],
        }
        cls.census = {
            "repo": "example/mini", "derived_commit": cls.commit,
            "go_paths": 8, "regular_go_sources": 7, "nonregular_go_paths": [
                {"path": "link.go", "kind": "blob", "mode": "120000",
                 "git_object": git(cls.clone, "ls-tree", "HEAD", "link.go").split()[2]}],
        }
        cls.result = eu.enumerate_repo("example/mini", cls.clone, cls.commit,
                                       cls.census, cls.mappings)

    @classmethod
    def tearDownClass(cls) -> None:
        cls.tmp.cleanup()

    def sites_by(self, path: str) -> dict[str, list[dict]]:
        by_kind: dict[str, list[dict]] = {}
        for row in self.result["sites"]:
            if row["path"] == path:
                by_kind.setdefault(row["kind"], []).append(row)
        return by_kind


class TestEnumeration(SyntheticRepoCase):
    def test_roles_and_source_census(self):
        self.assertEqual(self.result["units"]["by_role"],
                         {"generated": 1, "mock": 1, "production": 3, "test": 1, "vendor": 1})
        self.assertEqual(sum(len(p) for p in self.result["eligible_units"]["by_role"].values()), 7)
        self.assertEqual(self.result["nonregular"]["link_targets"], {"link.go": "main.go"})

    def test_client_interfaces_and_operations(self):
        client = self.result["declarations"][0]
        self.assertEqual(client["interfaces"][0]["client_type"], "GreeterClient")
        self.assertEqual(client["operations"][0]["full_method"], "/greeter.v1.Greeter/SayHello")
        self.assertTrue(client["mapped"])
        self.assertIsNotNone(client["operations"][0]["declaration_start_byte"])

    def test_bare_method_remains_recall_eligible(self):
        row = self.sites_by("bare.go")["operation_invocation"][0]
        self.assertFalse(row["client_aware"])
        self.assertTrue(frames.recall_eligibility(row)[0])

    def test_every_call_is_inventoried(self):
        kinds = self.sites_by("main.go")
        self.assertEqual({r["symbol"] for r in kinds["constructor_call"]}, {"NewGreeterClient"})
        self.assertTrue({"Dial", "Background"} <= {r["symbol"] for r in kinds["indirect_or_other_call"]})

    def test_import_alone_is_explicitly_excluded(self):
        row = self.sites_by("importonly.go")["import_reference"][0]
        self.assertEqual(frames.recall_eligibility(row), (False, "import_reference"))

    def test_full_method_strings(self):
        rows = self.sites_by("api/v1/greeter_grpc.pb.go")["full_method_string"]
        self.assertEqual(rows[0]["symbol"], "/greeter.v1.Greeter/SayHello")

    def test_old_generator(self):
        client = eu.extract_client("x/greeter_grpc.pb.go", OLD_CLIENT, {"x": "example.com/mini"})
        self.assertIsNone(client["operations"][0]["full_method"])

    def test_exact_tree_and_census_refusal(self):
        for commit, census, mappings in [
            ("f" * 40, self.census, self.mappings),
            (self.commit, {**self.census, "regular_go_sources": 9}, self.mappings),
            (self.commit, self.census, {**self.mappings, "clients": 3}),
        ]:
            with self.subTest(commit=commit, census=census), self.assertRaises(eu.UniverseError):
                eu.enumerate_repo("example/mini", self.clone, commit, census, mappings)


class TestSourceScanner(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.scanner = eu.SourceScanner()

    @classmethod
    def tearDownClass(cls):
        cls.scanner.close()

    def scan(self, body):
        return eu.enumerate_sites("example/mini", "a" * 40, "x.go", body, "production",
                                  ["SayHello"], ["NewGreeterClient"], {}, {"example.com/pb"}, self.scanner)[0]

    def test_cross_file_interface_alias_and_method_value(self):
        body = b"package p\nfunc f(w Wrapper){ call := w.SayHello; call(nil); w.SayHello(nil) }\n"
        rows = self.scan(body)
        self.assertEqual([r["symbol"] for r in rows], ["SayHello", "call", "SayHello"])
        self.assertTrue(all(frames.recall_eligibility(r)[0] for r in rows))

    def test_dynamic_factory_and_reflection_calls(self):
        rows = self.scan(b'package p\nfunc f(){ factory()(nil); v.MethodByName("SayHello").Call(nil) }')
        self.assertEqual(len(rows), 4)
        self.assertEqual(len({r["site_id"] for r in rows}), 4)

    def test_generics_and_unicode_byte_positions(self):
        body = 'package p\n// café\nfunc f(){ generic[int](nil); c.SayHello(nil) }'.encode()
        rows = self.scan(body)
        for r in rows:
            self.assertTrue(body[r["start_byte"]:r["end_byte"]])
        self.assertEqual(body[rows[-1]["start_byte"]:rows[-1]["end_byte"]], b"SayHello")

    def test_comment_and_string_text_are_not_calls(self):
        rows = self.scan(b'package p\n// c.SayHello(nil)\nvar s = "call(nil)"')
        self.assertEqual(rows, [])

    def test_parse_failure_refuses(self):
        with self.assertRaises(eu.UniverseError):
            self.scan(b"package p\nfunc broken( {")


class TestFrames(SyntheticRepoCase):
    def test_recall_accounting(self):
        pop, excluded = frames.build_recall_frame(self.result["sites"])
        self.assertEqual(len(pop) + excluded["excluded_total"], len(self.result["sites"]))
        self.assertEqual(set(excluded["excluded_kinds"]), {"import_reference"})
        with self.assertRaises(frames.FramesError):
            frames.build_recall_frame([{ "kind": "invented"}])

    def test_multiservice_interface_units_and_roles(self):
        decl = copy.deepcopy(self.result["declarations"][0])
        interface = {**decl["interfaces"][0], "service": "Other", "client_type": "OtherClient",
                     "start_byte": 1000, "end_byte": 1100}
        decl["interfaces"].append(interface)
        units = frames.build_attribution_frame([decl])
        self.assertEqual(len(units), 2)
        self.assertEqual({u["service"] for u in units}, {"Greeter", "Other"})
        self.assertTrue(all(u["stratum"] == "example/mini:generated" for u in units))
        self.assertEqual(units[1]["site_id"].split(":")[-1], "1000-1100")

    def envelope(self, predicate="CALLS_OPERATION", lineage=None):
        source = self.sites_by("main.go")["operation_invocation"][0]
        start, end = source["citation_spans"][0]
        return {"bundle": {
            "evidence": [{"atom": {"id": "a1", "start_byte": start, "end_byte": end},
                          "repository": "example/mini", "run_id": "r1",
                          "occurrences": [{"repo": "example/mini", "run_id": "r1", "commit": self.commit,
                                           "path": "main.go", "start_line": 1, "end_line": 1}]}],
            "assertions": [{"id": "claim", "predicate": predicate, "repo": "example/mini", "run_id": "r1",
                            "supporting": ["a1"], "object": "/greeter.v1.Greeter/SayHello",
                            "code_role": "production", "lineage": lineage or "provisional_repo_path_v1_" + "a" * 64,
                            "detail": json.dumps({"schema": "go-caller-detail-v1", "protocol": "grpc",
                                                  "unresolved_reason": "missing_declaration" if predicate == "UNRESOLVED_CALLER" else ""})}]}}

    def test_production_coordinate_predicate_and_operation_adapter(self):
        env = self.envelope()
        out = frames.project_candidate_frames(env, {"sites": self.result["sites"]})
        row = out["precision"]["rows"][0]
        source = self.sites_by("main.go")["operation_invocation"][0]
        self.assertEqual(row["site_id"], source["site_id"])
        self.assertNotEqual(row["source_citation"], row["site_id"])
        self.assertEqual(row["object"], "greeter.v1.Greeter/SayHello")
        result = caller_scoring.score_recall("caller_recall", [row["site_id"]],
                 [label_row(row["site_id"], "yes", row["object"])], {row["site_id"]},
                 {row["site_id"]: row["stratum"]}, 1.96)
        self.assertEqual(result[0]["proportion"], 1)
        unresolved = self.envelope("UNRESOLVED_CALLER")
        unresolved["bundle"]["assertions"][0]["lineage"] = ""
        out = frames.project_candidate_frames(unresolved, {"sites": self.result["sites"]})
        self.assertEqual(out["unresolved"]["rows"][0]["unresolved_reason"], "missing_declaration")

    def test_candidate_source_fences_and_conflicts(self):
        mutations = [
            lambda e: e["bundle"]["evidence"][0]["occurrences"][0].update(commit="f" * 40),
            lambda e: e["bundle"]["evidence"][0]["occurrences"][0].update(repo="another/repo"),
            lambda e: e["bundle"]["assertions"][0].update(code_role="vendor"),
            lambda e: e["bundle"]["assertions"][0].update(object="greeter.v1.Greeter/SayHello"),
            lambda e: e["bundle"]["assertions"][0].update(predicate="UNRESOLVED_GRPC_CALL"),
            lambda e: e["bundle"]["assertions"].append({**e["bundle"]["assertions"][0], "object": "/greeter.v1.Other/SayHello"}),
        ]
        for mutation in mutations:
            e = self.envelope(); mutation(e)
            with self.subTest(mutation=mutation), self.assertRaises((frames.FramesError, label_protocol.LabelProtocolError, ValueError)):
                frames.project_candidate_frames(e, {"sites": self.result["sites"]})

    def test_raw_duplicate_lineage_and_role_conflicts_refuse(self):
        for field, bad in (("lineage", "provisional_repo_path_v1_" + "b" * 64),
                           ("code_role", "vendor")):
            env = self.envelope()
            env["bundle"]["assertions"].append({**env["bundle"]["assertions"][0],
                                              "id": "second", field: bad})
            with self.subTest(field=field), self.assertRaises(frames.FramesError):
                frames.project_candidate_frames(env, {"sites": self.result["sites"]})

    def test_identical_raw_duplicate_claims_collapse_once(self):
        env = self.envelope()
        env["bundle"]["assertions"].append({**env["bundle"]["assertions"][0], "id": "second"})
        out = frames.project_candidate_frames(env, {"sites": self.result["sites"]})
        self.assertEqual(out["precision"]["population"], 1)

    def test_census_and_draw_mechanics_use_synthetic_seed_only(self):
        sizes = frames.frame_strata_sizes({"s": ["a", "b"]}, 97)
        self.assertEqual(sizes["s"], {"population": 2, "sample_size": 2, "census": True})
        plan = {"frames": [{"frame_id": "recall", "population": 2, "strata": {"s": {"population": 2, "sample_size": 2}}}]}
        populations = {"recall": [{"site_id": i, "stratum": "s"} for i in ["a", "b"]]}
        self.assertEqual(frames.draw_samples(plan, "a" * 64, populations), frames.draw_samples(plan, "a" * 64, populations))
        with self.assertRaises(frames.FramesError):
            frames.draw_samples(plan, "fake", populations)


    def test_quality_samples_require_all_frames_and_the_complete_draw(self):
        frames_in = [{"frame_id": f, "population": 2,
                      "strata": {"s": {"population": 2, "sample_size": 2}}}
                     for f in {"recall", "precision", "unresolved"}]
        plan = {"quality_frames": frames.QUALITY_FRAMES, "frames": frames_in}
        populations = {f["frame_id"]: [{"site_id": i, "stratum": "s"} for i in ("a", "b")]
                       for f in frames_in}
        drawn = {f: {"s": ["a", "b"]} for f in populations}
        self.assertEqual(set(frames.quality_samples(plan, drawn, populations)), caller_scoring.QUALITY_FAMILIES)
        with self.assertRaises(frames.FramesError):
            frames.quality_samples(plan, {"recall": drawn["recall"]}, populations)
        drawn["precision"]["s"].pop()
        with self.assertRaises(frames.FramesError):
            frames.quality_samples(plan, drawn, populations)


def label_row(site_id, invocation, operation=None, role="production"):
    return {"site_id": site_id, "invocation": invocation, "operation": operation,
            "registration": "no", "service": None, "expected_code_role": role,
            "rationale": "synthetic source judgment", "evidence": "synthetic source"}


def declaration_record(site_id, state="resolved", path="api/greeter.proto"):
    repo_commit = site_id.split(":", 1)[0]
    repo = repo_commit.split("@")[0]
    lineage = "provisional_repo_path_v1_" + eu.hashlib.sha256((repo + "\0" + path).encode()).hexdigest()
    return {"site_id": site_id, "state": state, "operation": "greeter.v1.Greeter/SayHello" if state == "resolved" else None,
            "lineage": lineage if state == "resolved" else None,
            "declaration_site_id": repo_commit + ":" + path + ":1-9" if state == "resolved" else None,
            "rationale": "synthetic independent citation"}


class TestScoring(unittest.TestCase):
    params = caller_scoring.load_parameters(SPIKE / "validation.parameters.json")
    s1 = "example/mini@" + "a" * 40 + ":main.go:10-18"
    s2 = "example/mini@" + "a" * 40 + ":main.go:30-38"
    operation = "greeter.v1.Greeter/SayHello"

    def test_missing_surplus_and_wrong_role_labels_refuse(self):
        for labels in ([], [label_row(self.s2, "no")], [label_row(self.s1, "no", role="vendor")]):
            with self.subTest(labels=labels), self.assertRaises(ValueError):
                caller_scoring.score_recall("caller_recall", [self.s1], labels, set(), {self.s1: "example/mini:production"}, 1.96)

    def test_recall_keeps_negative_sample_count(self):
        labels = [label_row(self.s1, "yes", self.operation), label_row(self.s2, "no")]
        result = caller_scoring.score_recall("caller_recall", [self.s1, self.s2], labels,
                  {self.s1}, {s: "example/mini:production" for s in (self.s1, self.s2)}, 1.96)[0]
        self.assertEqual((result["sampled"], result["decided"], result["nonpositive"]), (2, 1, 1))
        self.assertEqual(result["proportion"], 1)

    def test_declaration_precision_and_recall_require_exact_lineage(self):
        ids = [self.s1, self.s2]
        labels = [label_row(s, "yes", self.operation) for s in ids]
        truth = [declaration_record(s) for s in ids]
        strata = {s: "example/mini:production" for s in ids}
        operations = {s: self.operation for s in ids}
        lineages = {self.s1: truth[0]["lineage"], self.s2: "wrong_lineage"}
        precision = caller_scoring.score_precision_family("attributed_edge_precision", ids, labels,
                     strata, 1.96, operations, lineages, truth)[0]
        recall = caller_scoring.score_recall("attributed_edge_recall", ids, labels, set(ids),
                  strata, 1.96, operations, lineages, truth)[0]
        self.assertEqual((precision["yes"], precision["no"]), (1, 1))
        self.assertEqual((recall["yes"], recall["no"]), (1, 1))
        self.assertEqual(precision["threshold_family"], "attributed_edge_precision")
        self.assertEqual(recall["threshold_family"], "attributed_edge_recall")

    def test_attribution_has_no_true_negative_rescue(self):
        labels = [label_row(self.s1, "no")]
        truth = [declaration_record(self.s1, "not_call")]
        result = caller_scoring.score_recall("attributed_edge_recall", [self.s1], labels, set(),
                  {self.s1: "example/mini:production"}, 1.96, {}, {}, truth)[0]
        self.assertTrue(result["unavailable"])
        self.assertEqual(result["decided"], 0)

    def test_attribution_requires_independent_citations(self):
        for family in ("attributed_edge_recall", "attributed_edge_precision"):
            with self.subTest(family=family), self.assertRaises(caller_scoring.ScoringError):
                if family.endswith("recall"):
                    caller_scoring.score_recall(family, [self.s1], [label_row(self.s1, "yes", self.operation)],
                                               set(), {self.s1: "example/mini:production"}, 1.96)
                else:
                    caller_scoring.score_precision_family(family, [self.s1], [label_row(self.s1, "yes", self.operation)],
                                                         {self.s1: "example/mini:production"}, 1.96)

    def test_declaration_ledger_scope_and_identity_refuse(self):
        for field, bad in (("declaration_site_id", "other/repo@" + "a" * 40 + ":x.proto:1-9"),
                           ("lineage", "wrong"), ("operation", "other.Service/Wrong")):
            truth = declaration_record(self.s1); truth[field] = bad
            with self.subTest(field=field), self.assertRaises(caller_scoring.ScoringError):
                caller_scoring.score_precision_family("attributed_edge_precision", [self.s1],
                   [label_row(self.s1, "yes", self.operation)], {self.s1: "example/mini:production"},
                   1.96, {self.s1: self.operation}, {self.s1: "anything"}, [truth])

    def test_wrong_abstention_fails_and_correct_abstention_passes(self):
        ids = [self.s1, self.s2]
        truth = [{"site_id": self.s1, "state": "resolved", "reason": "", "rationale": "synthetic"},
                 {"site_id": self.s2, "state": "unresolved", "reason": "missing_declaration", "rationale": "synthetic"}]
        result = caller_scoring.score_unresolved(ids, [label_row(s, "yes", self.operation) for s in ids],
                 {s: "missing_declaration" for s in ids}, {s: "example/mini:production" for s in ids}, 1.96, truth)[0]
        self.assertEqual((result["yes"], result["no"]), (1, 1))
        with self.assertRaises(caller_scoring.ScoringError):
            caller_scoring.score_precision_family("unresolved_accuracy", [], [], {}, 1.96)

    def test_missing_resolution_ledger_refuses(self):
        with self.assertRaises(caller_scoring.ScoringError):
            caller_scoring.score_unresolved([self.s1], [label_row(self.s1, "yes", self.operation)],
                {self.s1: "missing_declaration"}, {self.s1: "example/mini:production"}, 1.96, [])

    def gate_fixture(self, yes=10, unsure=0):
        ids = [self.s1 + f"-{n}" for n in range(yes + unsure)]
        labels = [label_row(s, "yes", self.operation) for s in ids[:yes]] + [label_row(s, "unsure") for s in ids[yes:]]
        strata = {s: "example/mini:production" for s in ids}
        base = caller_scoring.score_precision_family("caller_precision", ids, labels, strata, 1.96)[0]
        results = [{**base, "threshold_family": f} for f in caller_scoring.QUALITY_FAMILIES]
        required = {f: {"example/mini:production": ids} for f in caller_scoring.QUALITY_FAMILIES}
        return results, required

    def test_quality_gate_uncertainty_cap_and_all_unsure(self):
        results, required = self.gate_fixture(1, 9)
        self.assertEqual(caller_scoring.gate_quality(results, self.params, required)["round"], "fail")
        results, required = self.gate_fixture(0, 10)
        self.assertEqual(caller_scoring.gate_quality(results, self.params, required)["round"], "invalid")
        results, required = self.gate_fixture(9, 1)
        self.assertEqual(caller_scoring.gate_quality(results, self.params, required)["round"], "pass")

    def test_quality_gate_requires_full_planned_families_and_samples(self):
        results, required = self.gate_fixture()
        for bad, plan in (([], required), (results[:-1], required),
                          (results + results[:1], required), (results, {})):
            with self.subTest(bad=bad), self.assertRaises(caller_scoring.ScoringError):
                caller_scoring.gate_quality(bad, self.params, plan)
        changed = copy.deepcopy(results); changed[0]["sample_site_ids"] = ["other"]
        with self.assertRaises(caller_scoring.ScoringError):
            caller_scoring.gate_quality(changed, self.params, required)

    def test_zero_positive_denominator_remains_unavailable(self):
        result = caller_scoring.score_recall("caller_recall", [self.s1], [label_row(self.s1, "no")],
                                             set(), {self.s1: "example/mini:production"}, 1.96)[0]
        self.assertTrue(result["unavailable"])
        self.assertNotIn("invalid", result)


class TestProcessing(unittest.TestCase):
    params = TestScoring.params

    def universe(self):
        return {"repositories": [
            {"repo": "example/large", "derived_commit": "a" * 40, "units": {"regular_go_sources": 95},
             "eligible_units": {"regular_go_source_paths": [f"f{i}.go" for i in range(95)],
                                "by_role": {"production": [f"f{i}.go" for i in range(95)]}}},
            {"repo": "example/small", "derived_commit": "b" * 40, "units": {"regular_go_sources": 5},
             "eligible_units": {"regular_go_source_paths": [f"f{i}.go" for i in range(5)],
                                "by_role": {"test": [f"f{i}.go" for i in range(5)]}}}]}

    def records(self, small="failed"):
        return [{"repository": r["repo"], "commit": r["derived_commit"], "path": p,
                 "state": "analyzed" if r["repo"] == "example/large" else small}
                for r in self.universe()["repositories"] for p in r["eligible_units"]["regular_go_source_paths"]]

    def test_smaller_failed_stratum_cannot_be_pooled_away(self):
        u = self.universe()
        ledger = caller_scoring.eligible_unit_ledger(self.records(), u)
        gate = caller_scoring.gate_processing_state(ledger, u, self.params)
        self.assertEqual(gate["round"], "fail")
        self.assertEqual(gate["failures"][0]["stratum"], "example/small:test")
        good = caller_scoring.eligible_unit_ledger(self.records("analyzed"), u)
        self.assertEqual(caller_scoring.gate_processing_state(good, u, self.params)["round"], "pass")

    def test_receipts_require_exact_repo_commit_and_terminal_outcome(self):
        good = self.records()
        bads = [good[:-1], good + good[:1]]
        for field, bad in (("repository", "other/repo"), ("commit", "c" * 40), ("state", "read"), ("path", "unknown.go")):
            records = copy.deepcopy(good); records[0][field] = bad; bads.append(records)
        for records in bads:
            with self.subTest(records=records[:1]), self.assertRaises(caller_scoring.ScoringError):
                caller_scoring.eligible_unit_ledger(records, self.universe())

    def test_ledger_totals_and_role_census_cannot_drift(self):
        u = self.universe()
        ledger = caller_scoring.eligible_unit_ledger(self.records(), u)
        ledger["by_stratum"]["example/large:production"]["analyzed"] += 1
        with self.assertRaises(caller_scoring.ScoringError):
            caller_scoring.gate_processing_state(ledger, u, self.params)
        u["repositories"][0]["eligible_units"]["by_role"]["production"].pop()
        with self.assertRaises(caller_scoring.ScoringError):
            caller_scoring.eligible_unit_ledger(self.records(), u)


class TestBindingBundle(unittest.TestCase):
    def bundle(self):
        return json.loads((SPIKE / "bundle/preregistration.bundle.json").read_text())

    def test_committed_bundle_has_named_missing_and_no_authority(self):
        b = self.bundle()
        missing = binding_bundle.validate_bundle(b)
        self.assertTrue(any("independent expected-resolution" in m for m in missing))
        self.assertFalse(b["external_publication"]["published"])
        self.assertFalse(b["quality_scored"])

    def test_missing_structure_and_required_subtree_refuse(self):
        with self.assertRaises(binding_bundle.BundleError):
            binding_bundle.validate_bundle({})
        for key in self.bundle():
            if key == "missing_bindings":
                continue
            b = self.bundle(); del b[key]
            with self.subTest(key=key), self.assertRaises(binding_bundle.BundleError):
                binding_bundle.validate_bundle(b)
        b = self.bundle(); del b["frames_plan"]["members"]["frames.excluded.json"]
        with self.assertRaises(binding_bundle.BundleError):
            binding_bundle.validate_bundle(b)

    def test_all_digest_shapes_and_stale_missing_list_refuse(self):
        mutations = [lambda b: b["parameters"].update(sha256="sha256:bad"),
                     lambda b: b["universe"].update(summary_sha256="sha256:bad"),
                     lambda b: b["universe"].update(declarations_sha256=None),
                     lambda b: b["machinery"]["frames"].update(sha256="anything"),
                     lambda b: b.update(missing_bindings=[])]
        for mutate in mutations:
            b = self.bundle(); mutate(b)
            with self.subTest(mutate=mutate), self.assertRaises(binding_bundle.BundleError):
                binding_bundle.validate_bundle(b)

    def test_identity_paths_counts_and_skeletons_refuse(self):
        mutations = [lambda b: b["parameters"].update(path="wrong.json"),
                     lambda b: b["frames_plan"]["members"]["frames.recall.jsonl.gz"].update(rows=-1),
                     lambda b: b["external_publication"]["prepared_payloads"][1].update(schema="invented")]
        for mutate in mutations:
            b = self.bundle(); mutate(b)
            with self.subTest(mutate=mutate), self.assertRaises(binding_bundle.BundleError):
                binding_bundle.validate_bundle(b)

    def test_builder_refuses_a_changed_frame_member(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp)
            for name in ("frames.plan.json", "frames.recall.jsonl.gz", "frames.attribution.jsonl", "frames.excluded.json"):
                (out / name).write_bytes((SPIKE / "frames" / name).read_bytes())
            with (out / "frames.attribution.jsonl").open("ab") as f:
                f.write(b"{}\n")
            with self.assertRaisesRegex(binding_bundle.BundleError, "frame member identity mismatch"):
                binding_bundle.build_bundle(SPIKE.parents[1], out)

    def test_valid_digest_does_not_skip_other_required_fields(self):
        b = self.bundle(); b["parameters"]["status"] = None
        with self.assertRaises(binding_bundle.BundleError):
            binding_bundle.validate_bundle(b)


if __name__ == "__main__":
    unittest.main()
