package t221

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"strconv"
	"strings"
)

// apacheGeneratedMarker is the header Apache Thrift's Go generator writes.
// Older generators (pre-0.13) wrote "// Autogenerated by Thrift Compiler";
// both are accepted, and G5 asserts the pinned corpus actually carries one.
var apacheGeneratedMarkers = []string{
	"// Code generated by Thrift Compiler",
	"// Autogenerated by Thrift Compiler",
}

// TaggedField is one struct field carrying a `thrift:"name,ID[,flags]"` tag
// in Apache Thrift generated Go. The tag is the only in-file field identity
// the Apache family has: there is no embedded IDL, no digest, no source path.
type TaggedField struct {
	Struct     string
	GoName     string
	ThriftName string
	ID         int
	Required   bool
	StartByte  int
	EndByte    int
}

// ParseThriftTags returns every thrift-tagged struct field in the Go file,
// in declaration order. A malformed thrift tag is an error, never a skip:
// recognition rules must fail loudly in the spike so the decision table can
// record the real failure classes.
func ParseThriftTags(path string) ([]TaggedField, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	var out []TaggedField
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range structType.Fields.List {
				if field.Tag == nil || len(field.Names) != 1 {
					continue
				}
				tagged, found, err := parseThriftTag(field.Tag.Value)
				if err != nil {
					return nil, fmt.Errorf("%s field %s.%s: %w", path, typeSpec.Name.Name, field.Names[0].Name, err)
				}
				if !found {
					continue
				}
				tagged.Struct = typeSpec.Name.Name
				tagged.GoName = field.Names[0].Name
				tagged.StartByte = fset.PositionFor(field.Names[0].Pos(), false).Offset
				tagged.EndByte = fset.PositionFor(field.Names[0].End(), false).Offset
				out = append(out, tagged)
			}
		}
	}
	return out, nil
}

func parseThriftTag(literal string) (TaggedField, bool, error) {
	tag, err := strconv.Unquote(literal)
	if err != nil {
		return TaggedField{}, false, fmt.Errorf("unquote tag: %w", err)
	}
	value := reflect.StructTag(tag).Get("thrift")
	if value == "" {
		return TaggedField{}, false, nil
	}
	parts := strings.Split(value, ",")
	if len(parts) < 2 {
		return TaggedField{}, false, fmt.Errorf("thrift tag %q has no field ID", value)
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		return TaggedField{}, false, fmt.Errorf("thrift tag %q field ID: %w", value, err)
	}
	required := false
	for _, flag := range parts[2:] {
		if flag == "required" {
			required = true
		}
	}
	return TaggedField{ThriftName: parts[0], ID: id, Required: required}, true, nil
}

// HasThriftModuleIdent reports whether the file mentions a ThriftModule
// declaration. G4 asserts this is false across the whole Apache corpus —
// the confirmation that the Apache family has no in-file IDL identity and
// therefore can never earn the module_digest binding.
func HasThriftModuleIdent(path string) (bool, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.SkipObjectResolution)
	if err != nil {
		return false, fmt.Errorf("parse %s: %w", path, err)
	}
	return findThriftModuleLiteral(file) != nil, nil
}

// HasApacheGeneratedMarker reports whether one of the known Apache Thrift
// generator headers appears as a complete comment line in the first bytes.
// A string literal or a longer comment that merely contains the marker is
// not generator evidence.
func HasApacheGeneratedMarker(path string) (bool, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	head := string(content)
	if len(head) > 4096 {
		head = head[:4096]
	}
	for _, line := range strings.Split(head, "\n") {
		line = strings.TrimSuffix(line, "\r")
		for _, marker := range apacheGeneratedMarkers {
			// Line-anchored prefix, not equality: the generator appends
			// its version ("... Thrift Compiler (0.14.1). DO NOT EDIT.").
			if strings.HasPrefix(strings.TrimSpace(line), marker) {
				return true, nil
			}
		}
	}
	return false, nil
}
