package t221

import (
	"crypto/sha1" //nolint:gosec // test fixture follows the embedded descriptor contract.
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf16"
	"unicode/utf8"

	"github.com/scip-code/scip/bindings/go/scip"
)

func TestDocumentEligibilityIsImportAndHeaderBound(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "lookalike.go", `package fake
import reflectfake "example.invalid/thriftreflect"
var ThriftModule = &reflectfake.ThriftModule{Name: "x"}
`)
	writeTestFile(t, root, "marker_string.go", `package fake
const marker = "// Code generated by Thrift Compiler"
type Batch struct { Process string `+"`thrift:\"process,1\"`"+` }
`)
	writeTestFile(t, root, "bad_apache.go", `// Code generated by Thrift Compiler
package fake
type Batch struct { Process string `+"`thrift:\"process,nope\"`"+` }
`)
	writeTestFile(t, root, "bad_module.go", `package fake
import tr "go.uber.org/thriftrw/thriftreflect"
var ThriftModule = &tr.ThriftModule{Name: "x"}
`)
	writeTestFile(t, root, "health.go", thriftRWHealthSource(t))

	resolve := CorpusDocumentResolver(root)
	for _, path := range []string{"lookalike.go", "marker_string.go"} {
		if model, ok, err := resolve(path); err != nil {
			t.Fatalf("%s: %v", path, err)
		} else if ok {
			t.Fatalf("%s classified as %s", path, model.Family)
		}
	}
	for _, path := range []string{"bad_apache.go", "bad_module.go"} {
		if _, _, err := resolve(path); err == nil {
			t.Fatalf("%s: malformed candidate silently became ineligible", path)
		}
	}
	model, ok, err := resolve("health.go")
	if err != nil || !ok || model.Family != "thriftrw" {
		t.Fatalf("bound alias module: model=%+v ok=%v err=%v", model, ok, err)
	}
}

func TestThriftRWDocumentDerivesDeclaredAndFieldZeroIdentity(t *testing.T) {
	root := t.TempDir()
	source := thriftRWHealthSource(t)
	writeTestFile(t, root, "health.go", source)
	model, ok, err := CorpusDocumentResolver(root)("health.go")
	if err != nil || !ok {
		t.Fatalf("resolve: ok=%v err=%v", ok, err)
	}
	assertDefinition := func(identifier, message, field string, id int) {
		t.Helper()
		start := strings.Index(source, identifier)
		for start >= 0 {
			if definition, found := model.DefinitionAt(start, start+len(identifier)); found &&
				definition.Identifier == identifier {
				if definition.Scope != "health" || definition.Message != message ||
					definition.FieldName != field || definition.FieldID != id ||
					definition.SourceBinding != "module_digest" {
					t.Fatalf("%s: %+v", identifier, definition)
				}
				return
			}
			next := strings.Index(source[start+1:], identifier)
			if next < 0 {
				break
			}
			start += next + 1
		}
		t.Fatalf("definition %s not resolved", identifier)
	}
	assertDefinition("GetWorkflowId", "WorkflowExecution", "workflowId", 10)
	assertDefinition("GetSuccess", "Meta_Health_Result", "success", 0)
}

func TestJoinFieldReferencesRequiresTypedIdentityAndValidRanges(t *testing.T) {
	root := t.TempDir()
	generated := `// Code generated by Thrift Compiler
package jaeger
type Process struct{}
type Batch struct {
	Process *Process ` + "`thrift:\"process,1\"`" + `
	Other string
}
`
	reference := "package caller\nvar _ = \"😀\"; var got = batch.Process\n"
	writeTestFile(t, root, "generated.go", generated)
	writeTestFile(t, root, "reference.go", reference)

	symbol := "scip-go gomod example.com/repo v1 pkg/Batch#Process."
	otherSymbol := "scip-go gomod example.com/repo v1 pkg/Batch#Other."
	wrongOwnerSymbol := "scip-go gomod example.com/repo v1 pkg/OtherType#Process."
	defStart := strings.Index(generated, "Process *Process")
	otherStart := strings.Index(generated, "Other string")
	refStart := strings.LastIndex(reference, "Process")
	index := &scip.Index{Documents: []*scip.Document{
		{
			RelativePath:     "generated.go",
			PositionEncoding: scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart,
			Occurrences: []*scip.Occurrence{
				testOccurrence(generated, defStart, len("Process"), symbol, scip.SymbolRole_Definition|scip.SymbolRole_Generated, scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart),
				testOccurrence(generated, defStart, len("Process"), wrongOwnerSymbol, scip.SymbolRole_Definition|scip.SymbolRole_Generated, scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart),
				testOccurrence(generated, otherStart, len("Other"), otherSymbol, scip.SymbolRole_Definition|scip.SymbolRole_Generated, scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart),
			},
		},
		{
			RelativePath:     "reference.go",
			PositionEncoding: scip.PositionEncoding_UTF16CodeUnitOffsetFromLineStart,
			Occurrences: []*scip.Occurrence{
				testOccurrence(reference, refStart, len("Process"), symbol, 0, scip.PositionEncoding_UTF16CodeUnitOffsetFromLineStart),
				{Range: []int32{1, 999, 1000}, Symbol: symbol, SymbolRoles: int32(scip.SymbolRole_ReadAccess)},
			},
		},
	}}

	bindings, abstentions, err := JoinFieldReferences(index, root, CorpusDocumentResolver(root))
	if err != nil {
		t.Fatal(err)
	}
	binding := bindings[symbol]
	if binding == nil {
		t.Fatal("typed field did not bind")
	}
	if binding.Scope != "jaeger" || binding.Message != "Batch" ||
		binding.FieldName != "process" || binding.FieldID != 1 ||
		binding.Object != "jaeger.Batch#1" || binding.SourceBinding != "none" {
		t.Fatalf("binding identity: %+v", binding)
	}
	if len(binding.References) != 1 {
		t.Fatalf("references: %+v", binding.References)
	}
	referenceBinding := binding.References[0]
	if referenceBinding.StartByte != refStart || referenceBinding.EndByte != refStart+len("Process") ||
		referenceBinding.Classification != "unknown" {
		t.Fatalf("reference range/classification: %+v", referenceBinding)
	}
	if bindings[otherSymbol] != nil || !hasAbstention(abstentions, otherSymbol, "unbound-field-identity") {
		t.Fatalf("untagged exact-span definition bound or wrong abstention: %+v", abstentions)
	}
	if bindings[wrongOwnerSymbol] != nil || !hasAbstention(abstentions, wrongOwnerSymbol, "malformed-symbol") {
		t.Fatalf("wrong enclosing type bound or wrong abstention: %+v", abstentions)
	}
	if !hasAbstention(abstentions, symbol, "malformed-reference-range") {
		t.Fatalf("malformed reference was not refused: %+v", abstentions)
	}
}

func TestJoinFieldReferencesRefusesDuplicateDefinitions(t *testing.T) {
	root := t.TempDir()
	source := `// Code generated by Thrift Compiler
package jaeger
type Process struct{}
type Batch struct { Process *Process ` + "`thrift:\"process,1\"`" + ` }
`
	writeTestFile(t, root, "one.go", source)
	writeTestFile(t, root, "two.go", source)
	symbol := "scip-go gomod example.com/repo v1 pkg/Batch#Process."
	start := strings.Index(source, "Process *Process")
	index := &scip.Index{}
	for _, path := range []string{"one.go", "two.go"} {
		index.Documents = append(index.Documents, &scip.Document{
			RelativePath:     path,
			PositionEncoding: scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart,
			Occurrences: []*scip.Occurrence{
				testOccurrence(source, start, len("Process"), symbol, scip.SymbolRole_Definition, scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart),
			},
		})
	}
	bindings, abstentions, err := JoinFieldReferences(index, root, CorpusDocumentResolver(root))
	if err != nil {
		t.Fatal(err)
	}
	if bindings[symbol] != nil || !hasAbstention(abstentions, symbol, "ambiguous-definition") {
		t.Fatalf("duplicate definition selected: bindings=%+v abstentions=%+v", bindings, abstentions)
	}
}

func TestReferenceRolePrecedenceAndPositionBoundaries(t *testing.T) {
	roleCases := []struct {
		name  string
		roles scip.SymbolRole
		want  string
	}{
		{name: "write_over_read", roles: scip.SymbolRole_WriteAccess | scip.SymbolRole_ReadAccess, want: "write"},
		{name: "read_over_test", roles: scip.SymbolRole_ReadAccess | scip.SymbolRole_Test, want: "read"},
		{name: "test_over_generated", roles: scip.SymbolRole_Test | scip.SymbolRole_Generated, want: "test"},
		{name: "generated", roles: scip.SymbolRole_Generated, want: "generated"},
		{name: "unknown", roles: 0, want: "unknown"},
	}
	for _, test := range roleCases {
		t.Run(test.name, func(t *testing.T) {
			if got := classifyRoles(int32(test.roles)); got != test.want {
				t.Fatalf("classifyRoles(%d) = %q, want %q", test.roles, got, test.want)
			}
		})
	}

	content := "x😀y\n"
	starts := lineStarts(content)
	if _, ok := positionByte(content, starts, scip.Position{Line: 0, Character: 2}, scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart); ok {
		t.Fatal("UTF-8 position accepted a mid-rune byte")
	}
	if _, ok := positionByte(content, starts, scip.Position{Line: 0, Character: 2}, scip.PositionEncoding_UTF16CodeUnitOffsetFromLineStart); ok {
		t.Fatal("UTF-16 position accepted a mid-surrogate code unit")
	}
	if got, ok := positionByte(content, starts, scip.Position{Line: 0, Character: 2}, scip.PositionEncoding_UTF32CodeUnitOffsetFromLineStart); !ok || got != len("x😀") {
		t.Fatalf("UTF-32 position = %d/%v, want %d/true", got, ok, len("x😀"))
	}
}

func TestVerifyCorpusCheckoutRejectsUntrackedAndIgnoredBytes(t *testing.T) {
	dir := t.TempDir()
	if err := runGit(dir, "init", "--quiet"); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, dir, "tracked.go", "package corpus\n")
	writeTestFile(t, dir, ".gitignore", "*.tmp\n")
	if err := runGit(dir, "add", "tracked.go", ".gitignore"); err != nil {
		t.Fatal(err)
	}
	if err := runGit(dir, "-c", "user.name=phebs", "-c", "user.email=phebs@example.invalid", "commit", "--quiet", "-m", "fixture"); err != nil {
		t.Fatal(err)
	}
	commit, err := gitOutput(dir, "rev-parse", "HEAD")
	if err != nil {
		t.Fatal(err)
	}
	entry := CorpusEntry{Name: "fixture", Commit: commit}
	writeTestFile(t, dir, "go.mod", corpusFenceContent(entry))
	if err := VerifyCorpusCheckout(dir, entry); err != nil {
		t.Fatalf("exact fence rejected: %v", err)
	}
	writeTestFile(t, dir, "rogue.go", "package rogue\n")
	if err := VerifyCorpusCheckout(dir, entry); err == nil {
		t.Fatal("untracked source accepted")
	}
	if err := os.Remove(filepath.Join(dir, "rogue.go")); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, dir, "rogue.tmp", "ignored but gate-visible\n")
	if err := VerifyCorpusCheckout(dir, entry); err == nil {
		t.Fatal("ignored filesystem byte accepted")
	}
	if err := os.Remove(filepath.Join(dir, "rogue.tmp")); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, dir, "go.mod", corpusFenceContent(entry)+"// modified\n")
	if err := VerifyCorpusCheckout(dir, entry); err == nil {
		t.Fatal("modified fence accepted")
	}
}

func thriftRWHealthSource(t *testing.T) string {
	t.Helper()
	raw := `namespace py ignored
struct WorkflowExecution {
  10: string workflowId
}
service Meta {
  string health()
}
`
	sum := sha1.Sum([]byte(raw)) //nolint:gosec // descriptor fixture.
	return `package health
import (
	tr "go.uber.org/thriftrw/thriftreflect"
	"go.uber.org/thriftrw/wire"
)
const rawIDL = ` + strconvQuote(raw) + `
var ThriftModule = &tr.ThriftModule{
	Name: "health", Package: "health", FilePath: "health.thrift",
	SHA1: "` + hex.EncodeToString(sum[:]) + `", Raw: rawIDL,
}
type WorkflowExecution struct { WorkflowId string }
func (v *WorkflowExecution) ToWire() (wire.Value, error) {
	fields := []wire.Field{wire.Field{ID: 10}}
	return wire.Value{}, nil
}
func (v *WorkflowExecution) GetWorkflowId() string { return v.WorkflowId }
type Meta_Health_Result struct { Success string }
func (v *Meta_Health_Result) ToWire() (wire.Value, error) {
	fields := []wire.Field{wire.Field{ID: 0}}
	return wire.Value{}, nil
}
func (v *Meta_Health_Result) GetSuccess() string { return v.Success }
`
}

func strconvQuote(value string) string {
	return "`" + strings.ReplaceAll(value, "`", "`+\"`\"+`") + "`"
}

func testOccurrence(content string, start, length int, symbol string, roles scip.SymbolRole, encoding scip.PositionEncoding) *scip.Occurrence {
	line := int32(strings.Count(content[:start], "\n"))
	lineStart := strings.LastIndex(content[:start], "\n") + 1
	startCharacter := encodedUnits(content[lineStart:start], encoding)
	endCharacter := startCharacter + encodedUnits(content[start:start+length], encoding)
	return &scip.Occurrence{
		TypedRange:  scip.NewRangeUnchecked([]int32{line, startCharacter, endCharacter}).AsTypedRange(),
		Symbol:      symbol,
		SymbolRoles: int32(roles),
	}
}

func encodedUnits(value string, encoding scip.PositionEncoding) int32 {
	switch encoding {
	case scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart:
		return int32(len(value))
	case scip.PositionEncoding_UTF16CodeUnitOffsetFromLineStart:
		return int32(len(utf16.Encode([]rune(value))))
	case scip.PositionEncoding_UTF32CodeUnitOffsetFromLineStart:
		return int32(utf8.RuneCountInString(value))
	default:
		return -1
	}
}

func writeTestFile(t *testing.T, root, rel, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func hasAbstention(values []Abstention, symbol, reason string) bool {
	for _, value := range values {
		if value.Symbol == symbol && value.Reason == reason {
			return true
		}
	}
	return false
}
