package gocaller_test

import (
	"context"
	"testing"

	"github.com/bmeddeb/phebs/internal/extract/extractors/gocaller"
	"github.com/bmeddeb/phebs/internal/extract/sdk"
)

const directGeneratedGRPC = `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api.proto
package api

const Greeter_SayHello_FullMethodName = "/demo.Greeter/SayHello"

type GreeterClient interface {
	SayHello()
}

var Greeter_ServiceDesc = struct{ ServiceName string }{
	ServiceName: "demo.Greeter",
}

func NewGreeterClient() GreeterClient { return nil }
`

func TestDescribeAndScanDirectSyntaxFile(t *testing.T) {
	symbols, err := gocaller.DescribeGeneratedSource(
		"grpc", "gen/api_grpc.pb.go", "example.com/repo/gen", directGeneratedGRPC,
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(symbols) != 1 || symbols[0].Operation != "/demo.Greeter/SayHello" ||
		len(symbols[0].Constructors) != 1 ||
		symbols[0].Constructors[0] != "NewGreeterClient" {
		t.Fatalf("symbols = %+v", symbols)
	}
	descriptor := gocaller.DirectDescriptor{
		State: "resolved", Protocol: "grpc",
		ImportPath: symbols[0].ImportPath, Package: symbols[0].Package,
		ClientType: symbols[0].ClientType, Method: symbols[0].Method,
		Operation: symbols[0].Operation, Constructors: symbols[0].Constructors,
		GeneratedPath:         symbols[0].GeneratedPath,
		GeneratedObjectID:     "1111111111111111111111111111111111111111",
		GeneratedDigest:       "sha256:1111111111111111111111111111111111111111111111111111111111111111",
		GeneratorRelativePath: symbols[0].GeneratorRelativePath,
		DeclarationPath:       "idl/api.proto", DeclarationLineage: "lineage-a",
	}
	source := `package caller
import api "example.com/repo/gen"
func invoke() {
	client := api.NewGreeterClient()
	client.SayHello()
}
`
	var facts []sdk.Fact
	resolver, err := gocaller.NewDirectResolver(
		context.Background(), "grpc", []gocaller.DirectDescriptor{descriptor},
	)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := resolver.GeneratedSource(
		descriptor.GeneratedPath, descriptor.GeneratedObjectID,
	)
	if err != nil || !generated {
		t.Fatalf("generated source identity = %v, %v", generated, err)
	}
	if _, err := resolver.GeneratedSource(
		descriptor.GeneratedPath, "2222222222222222222222222222222222222222",
	); err == nil {
		t.Fatal("generated source path accepted a stale object identity")
	}
	result, err := gocaller.ScanDirectSyntaxFile(
		context.Background(), gocaller.DirectScanRequest{
			Protocol: "grpc", Path: "src/caller.go",
			Blob:                  sdk.Blob{Content: source, Digest: "sha256:source"},
			Resolver:              resolver,
			ResolverCatalogDigest: "sha256:catalog",
		}, func(fact sdk.Fact) error {
			facts = append(facts, fact)
			return nil
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if result.Emitted != 1 || result.Abstentions != 0 || len(facts) != 1 ||
		facts[0].Assertion.Predicate != "CALLS_OPERATION" ||
		facts[0].Assertion.Object != "/demo.Greeter/SayHello" ||
		facts[0].Assertion.Lineage != "lineage-a" {
		t.Fatalf("result = %+v, facts = %+v", result, facts)
	}
}

func TestDirectResolverRejectsConflictingGeneratedSourceIdentity(t *testing.T) {
	descriptor := gocaller.DirectDescriptor{
		State: "resolved", Protocol: "grpc",
		ImportPath: "example.com/repo/gen", Package: "api",
		ClientType: "GreeterClient", Method: "SayHello",
		Operation: "/demo.Greeter/SayHello", Constructors: []string{"NewGreeterClient"},
		GeneratedPath:         "gen/api_grpc.pb.go",
		GeneratedObjectID:     "1111111111111111111111111111111111111111",
		GeneratedDigest:       "sha256:1111111111111111111111111111111111111111111111111111111111111111",
		GeneratorRelativePath: "api.proto",
		DeclarationPath:       "idl/api.proto", DeclarationLineage: "lineage-a",
	}
	other := descriptor
	other.Method = "Other"
	other.Operation = "/demo.Greeter/Other"
	other.GeneratedObjectID = "2222222222222222222222222222222222222222"
	if _, err := gocaller.NewDirectResolver(
		t.Context(), "grpc", []gocaller.DirectDescriptor{descriptor, other},
	); err == nil {
		t.Fatal("resolver accepted two objects for one generated path")
	}
}

func TestDirectResolverAbstainsOnDuplicateGeneratedProvenance(t *testing.T) {
	first := gocaller.DirectDescriptor{
		State: "resolved", Protocol: "grpc",
		ImportPath: "example.com/repo/gen", Package: "api",
		ClientType: "GreeterClient", Method: "SayHello",
		Operation: "/demo.Greeter/SayHello", Constructors: []string{"NewGreeterClient"},
		GeneratedPath:         "gen/a_grpc.pb.go",
		GeneratedObjectID:     "1111111111111111111111111111111111111111",
		GeneratedDigest:       "sha256:1111111111111111111111111111111111111111111111111111111111111111",
		GeneratorRelativePath: "api.proto",
		DeclarationPath:       "idl/api.proto", DeclarationLineage: "lineage-a",
	}
	second := first
	second.GeneratedPath = "gen/b_grpc.pb.go"
	second.GeneratedObjectID = "2222222222222222222222222222222222222222"
	second.GeneratedDigest = "sha256:2222222222222222222222222222222222222222222222222222222222222222"
	resolver, err := gocaller.NewDirectResolver(
		t.Context(), "grpc", []gocaller.DirectDescriptor{first, second},
	)
	if err != nil {
		t.Fatal(err)
	}
	source := `package caller
import api "example.com/repo/gen"
func invoke() { client := api.NewGreeterClient(); client.SayHello() }
`
	var fact sdk.Fact
	result, err := gocaller.ScanDirectSyntaxFile(
		t.Context(), gocaller.DirectScanRequest{
			Protocol: "grpc", Path: "src/caller.go",
			Blob:     sdk.Blob{Content: source, Digest: "sha256:source"},
			Resolver: resolver, ResolverCatalogDigest: "sha256:catalog",
		}, func(value sdk.Fact) error { fact = value; return nil },
	)
	if err != nil {
		t.Fatal(err)
	}
	if result.Emitted != 1 || result.Abstentions != 1 ||
		fact.Assertion.Predicate != "UNRESOLVED_CALLER" {
		t.Fatalf("duplicate provenance result = %+v, fact = %+v", result, fact)
	}
}

func TestScanDirectSyntaxFileAmbiguityAbstains(t *testing.T) {
	descriptor := gocaller.DirectDescriptor{
		State: "ambiguous", Reason: "multiple_declaration_paths",
		Protocol: "grpc", ImportPath: "example.com/repo/gen",
		Package: "api", ClientType: "GreeterClient", Method: "SayHello",
		Operation: "/demo.Greeter/SayHello", Constructors: []string{"NewGreeterClient"},
		GeneratedPath:         "gen/api_grpc.pb.go",
		GeneratedObjectID:     "1111111111111111111111111111111111111111",
		GeneratedDigest:       "sha256:1111111111111111111111111111111111111111111111111111111111111111",
		GeneratorRelativePath: "api.proto",
	}
	source := `package caller
import api "example.com/repo/gen"
func invoke() { client := api.NewGreeterClient(); client.SayHello() }
`
	var fact sdk.Fact
	result, err := gocaller.ScanDirectSyntaxFile(
		context.Background(), gocaller.DirectScanRequest{
			Protocol: "grpc", Path: "src/caller.go",
			Blob:        sdk.Blob{Content: source, Digest: "sha256:source"},
			Descriptors: []gocaller.DirectDescriptor{descriptor},
		}, func(value sdk.Fact) error { fact = value; return nil },
	)
	if err != nil {
		t.Fatal(err)
	}
	if result.Emitted != 1 || result.Abstentions != 1 ||
		fact.Assertion.Predicate != "UNRESOLVED_CALLER" ||
		fact.Assertion.Object != "/demo.Greeter/SayHello" {
		t.Fatalf("result = %+v, fact = %+v", result, fact)
	}
}
