// Package gocaller extracts declaration-lineage-proven Go call occurrences
// from a committed SCIP index and checked-in generated RPC clients.
//
// The extractor never type-checks, executes, downloads, or generates corpus
// code. SCIP supplies the call-to-generated-symbol edge; generated source
// supplies the wire operation; the immutable attribution snapshot supplies
// the generated-artifact-to-declaration edge. A call is resolved only when
// all three edges agree on exactly one operation and declaration lineage.
package gocaller

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/scip-code/scip/bindings/go/scip"

	"github.com/bmeddeb/phebs/internal/extract/sdk"
)

const (
	grpcDomain   = "grpc-caller"
	thriftDomain = "thrift-caller"
	version      = "1.2.0"
	indexPath    = "index.scip"

	schemaVersion       = "t20-caller-v1"
	maxDocuments        = 100_000
	maxOccurrences      = 1_000_000
	maxSymbolBytes      = 16 << 10
	maxGeneratedBytes   = 4 << 20
	maxSourceBytes      = 4 << 20
	adapterConfigDigest = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
)

// NewGRPC returns the typed protobuf/gRPC caller extractor.
func NewGRPC() sdk.Extractor { return extractor{protocol: "grpc", domain: grpcDomain} }

// NewThrift returns the typed Apache Thrift caller extractor.
func NewThrift() sdk.Extractor { return extractor{protocol: "thrift", domain: thriftDomain} }

type extractor struct {
	protocol string
	domain   string
}

func (e extractor) Domain() string  { return e.domain }
func (e extractor) Version() string { return version }
func (e extractor) Candidate(filePath string) bool {
	return filePath == indexPath || filePath == "go.mod" ||
		strings.HasSuffix(filePath, ".go")
}

type indexedOccurrence struct {
	rangeValue scip.Range
	symbol     string
	roles      int32
}

type indexedDocument struct {
	path        string
	encoding    scip.PositionEncoding
	occurrences []indexedOccurrence
}

type generatedAnchor struct {
	operation         string
	lineage           string
	generatedPath     string
	declarationPath   string
	generatorRelative string
	reason            string
}

type symbolBinding struct {
	symbol            string
	operation         string
	lineage           string
	generatedPath     string
	declarationPath   string
	generatorRelative string
	reason            string
}

type callerDetail struct {
	Schema              string                `json:"schema"`
	Resolution          string                `json:"resolution"`
	Protocol            string                `json:"protocol"`
	GeneratedSymbol     string                `json:"generated_symbol"`
	GeneratedPath       string                `json:"generated_path,omitempty"`
	DeclarationPath     string                `json:"declaration_path,omitempty"`
	GeneratorRelative   string                `json:"generator_relative_path,omitempty"`
	AttributionDigest   string                `json:"attribution_digest,omitempty"`
	UnresolvedReason    string                `json:"unresolved_reason,omitempty"`
	DeclarationEvidence string                `json:"declaration_evidence,omitempty"`
	UnitState           string                `json:"unit_state"`
	UnitReason          string                `json:"unit_reason,omitempty"`
	UnitCandidates      []unitCandidateDetail `json:"unit_candidates,omitempty"`
}

type unitCandidateDetail struct {
	ID              string   `json:"id"`
	BuildTargets    []string `json:"build_targets,omitempty"`
	Deployables     []string `json:"deployables,omitempty"`
	LogicalServices []string `json:"logical_services,omitempty"`
	Owners          []string `json:"owners,omitempty"`
}

var (
	fullMethodRe  = regexp.MustCompile(`^/([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)/([A-Za-z_]\w*)$`)
	serviceNameRe = regexp.MustCompile(`^[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*$`)
	sourceLineRe  = regexp.MustCompile(`(?m)^// source: ([A-Za-z0-9_./-]+\.proto)\r?$`)
	thriftHeader  = regexp.MustCompile(`(?m)^// (Code generated by Thrift Compiler|Autogenerated by Thrift Compiler)`)
	generatedHdr  = regexp.MustCompile(`(?m)^// Code generated .* DO NOT EDIT`)
	mockHeader    = regexp.MustCompile(`Code generated by MockGen|Code generated by mockery|Code generated by counterfeiter`)
)

func fullMethodServiceNameValid(value string) bool {
	return serviceNameRe.MatchString(value)
}

func (e extractor) Extract(
	ctx context.Context,
	corpus sdk.Corpus,
	emit sdk.Emit,
) (sdk.Coverage, error) {
	coverage := sdk.Coverage{Protocols: []string{
		e.protocol, "generated-from-snapshot-v1", "resolution-scip-v1",
		"resolution-syntax-v1", "scip",
	}}
	paths := make(map[string]struct{})
	if err := corpus.WalkFiles(ctx, func(filePath string) error {
		paths[filePath] = struct{}{}
		return nil
	}); err != nil {
		return coverage, err
	}
	var documents []indexedDocument
	if _, present := paths[indexPath]; !present {
		coverage.Protocols = append(coverage.Protocols, "scip-index-absent")
	} else {
		indexCorpus, ok := corpus.(sdk.SCIPCorpus)
		if !ok {
			return coverage, errors.New("corpus does not support bounded SCIP index reads")
		}
		indexBlob, err := indexCorpus.ReadSCIPIndex(ctx)
		if err != nil {
			return coverage, fmt.Errorf("read %s: %w", indexPath, err)
		}
		if len(indexBlob.Content) == 0 {
			// An empty regular blob has no byte that can honestly back a gap
			// assertion. Treat it like unavailable typed input, record the
			// distinct state in coverage, and still allow syntax fallback.
			coverage.Protocols = append(coverage.Protocols, "scip-index-empty")
			indexBlob = sdk.Blob{}
		} else {
			var parseErr error
			documents, parseErr = parseIndex(ctx, indexBlob.Content)
			if parseErr != nil {
				if err := emitGap(indexBlob, "malformed_symbol_input", parseErr.Error(), emit); err != nil {
					return coverage, err
				}
				coverage.UnresolvedCount = 1
				documents = nil
			} else {
				for _, document := range documents {
					if _, present := paths[document.path]; present {
						continue
					}
					if err := emitGap(indexBlob, "stale_symbol_input", document.path, emit); err != nil {
						return coverage, err
					}
					coverage.UnresolvedCount = 1
					documents = nil
					break
				}
			}
			// The raw index is not retained across subsequent source reads.
			indexBlob = sdk.Blob{}
		}
	}

	var attribution attributionLookup = unavailableAttribution{}
	attributionDigest := ""
	if attributionCorpus, ok := corpus.(sdk.AttributionCorpus); ok {
		source, err := attributionCorpus.AttributionSource(ctx)
		if err != nil {
			return coverage, fmt.Errorf("load immutable attribution source: %w", err)
		}
		if source != nil {
			attribution = attributionAdapter{source}
			attributionDigest = source.Digest()
			if strings.HasPrefix(attributionDigest, "sha256:") &&
				len(attributionDigest) == len("sha256:")+64 {
				coverage.Protocols = append(
					coverage.Protocols,
					"attribution-"+strings.TrimPrefix(attributionDigest, "sha256:"),
				)
			}
		}
	}

	bindings, err := e.bindGenerated(ctx, corpus, documents, attribution)
	if err != nil {
		return coverage, err
	}
	unresolved, typedSpans, err := e.emitReferences(
		ctx, corpus, documents, bindings, attribution, attributionDigest, emit,
	)
	if err != nil {
		return coverage, err
	}
	coverage.UnresolvedCount += unresolved
	fallbackUnresolved, err := e.emitSyntaxFallback(
		ctx, corpus, paths, typedSpans, attribution, attributionDigest, emit,
	)
	coverage.UnresolvedCount += fallbackUnresolved
	sort.Strings(coverage.Protocols)
	return coverage, err
}

type generatedFromLookup interface {
	GeneratedFrom(protocol, generatedPath, generatorRelativePath string) sdk.GeneratedFromAttribution
}

type attributionLookup interface {
	generatedFromLookup
	ConsumerUnits(path string, line int) sdk.ConsumerUnitAttribution
}

type unavailableAttribution struct{}

func (unavailableAttribution) GeneratedFrom(_, _, _ string) sdk.GeneratedFromAttribution {
	return sdk.GeneratedFromAttribution{
		State:  sdk.AttributionStateUnavailable,
		Reason: "no_attribution_snapshot",
	}
}

func (unavailableAttribution) ConsumerUnits(_ string, _ int) sdk.ConsumerUnitAttribution {
	return sdk.ConsumerUnitAttribution{
		State:  sdk.AttributionStateUnavailable,
		Reason: "no_attribution_snapshot",
	}
}

type attributionAdapter struct{ sdk.AttributionSource }

func (e extractor) bindGenerated(
	ctx context.Context,
	corpus sdk.Corpus,
	documents []indexedDocument,
	attribution generatedFromLookup,
) (map[string]symbolBinding, error) {
	candidates := make(map[string][]generatedAnchor)
	for _, document := range documents {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if !hasDefinitions(document.occurrences) ||
			!e.generatedPathEligible(document.path) {
			continue
		}
		blob, err := corpus.Read(ctx, document.path)
		if err != nil {
			return nil, fmt.Errorf("read generated document %q: %w", document.path, err)
		}
		if len(blob.Content) > maxGeneratedBytes || !utf8.ValidString(blob.Content) {
			continue
		}
		var anchors map[string][]generatedAnchor
		switch e.protocol {
		case "grpc":
			anchors, err = grpcAnchors(
				document, blob.Content, attribution,
			)
		case "thrift":
			anchors, err = thriftAnchors(
				document, blob.Content, attribution,
			)
		default:
			return nil, fmt.Errorf("unsupported caller protocol %q", e.protocol)
		}
		if err != nil {
			// A generated file that cannot prove an anchor contributes no
			// candidate. SCIP references to it therefore abstain by omission.
			continue
		}
		for symbol, values := range anchors {
			candidates[symbol] = append(candidates[symbol], values...)
		}
	}
	bindings := make(map[string]symbolBinding)
	for symbol, values := range candidates {
		binding, ok := collapseAnchors(symbol, values)
		if ok {
			bindings[symbol] = binding
		}
	}
	return bindings, nil
}

func (e extractor) generatedPathEligible(filePath string) bool {
	switch e.protocol {
	case "grpc":
		return strings.HasSuffix(filePath, "_grpc.pb.go")
	case "thrift":
		return strings.HasSuffix(filePath, ".go")
	default:
		return false
	}
}

func grpcAnchors(
	document indexedDocument,
	content string,
	attribution generatedFromLookup,
) (map[string][]generatedAnchor, error) {
	if !generatedHdr.MatchString(firstBytes(content, 4096)) {
		return nil, errors.New("not generated gRPC Go")
	}
	sourceMatches := sourceLineRe.FindAllStringSubmatch(content, -1)
	if len(sourceMatches) != 1 {
		return nil, errors.New("generated gRPC source marker is not unique")
	}
	generatorRelative := sourceMatches[0][1]
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, document.path, content, parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}
	tokenFile := fset.File(file.Pos())
	fullMethods := make(map[string][]string)
	serviceNames := make(map[string][]string)
	ast.Inspect(file, func(node ast.Node) bool {
		if keyValue, ok := node.(*ast.KeyValueExpr); ok {
			key, keyOK := keyValue.Key.(*ast.Ident)
			literal, literalOK := keyValue.Value.(*ast.BasicLit)
			if keyOK && key.Name == "ServiceName" && literalOK &&
				literal.Kind == token.STRING {
				value, unquoteErr := strconv.Unquote(literal.Value)
				if unquoteErr == nil && fullMethodServiceNameValid(value) {
					short := value[strings.LastIndex(value, ".")+1:]
					serviceNames[short] = appendUnique(serviceNames[short], value)
				}
			}
		}
		literal, ok := node.(*ast.BasicLit)
		if !ok || literal.Kind != token.STRING {
			return true
		}
		value, err := strconv.Unquote(literal.Value)
		if err != nil {
			return true
		}
		match := fullMethodRe.FindStringSubmatch(value)
		if match != nil {
			key := match[1][strings.LastIndex(match[1], ".")+1:] + "\x00" + match[2]
			fullMethods[key] = appendUnique(fullMethods[key], "/"+match[1]+"/"+match[2])
		}
		return true
	})
	definitions := definitionsByStart(document, content)
	result := make(map[string][]generatedAnchor)
	for _, declaration := range file.Decls {
		gen, ok := declaration.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || !strings.HasSuffix(typeSpec.Name.Name, "Client") {
				continue
			}
			iface, ok := typeSpec.Type.(*ast.InterfaceType)
			if !ok {
				continue
			}
			service := strings.TrimSuffix(typeSpec.Name.Name, "Client")
			for _, method := range iface.Methods.List {
				if len(method.Names) != 1 {
					continue
				}
				name := method.Names[0]
				offset := tokenFile.Offset(name.Pos())
				occurrences := definitions[offset]
				operations := fullMethods[service+"\x00"+name.Name]
				if len(occurrences) != 1 || len(operations) != 1 {
					continue
				}
				fullMethod := fullMethodRe.FindStringSubmatch(operations[0])
				if fullMethod == nil || len(serviceNames[service]) != 1 ||
					serviceNames[service][0] != fullMethod[1] {
					continue
				}
				relation := attribution.GeneratedFrom(
					"grpc", document.path, generatorRelative,
				)
				anchor := relationAnchor(
					"grpc", document.path, generatorRelative, operations[0], relation,
				)
				result[occurrences[0].symbol] = append(
					result[occurrences[0].symbol], anchor,
				)
			}
		}
	}
	return result, nil
}

func thriftAnchors(
	document indexedDocument,
	content string,
	attribution generatedFromLookup,
) (map[string][]generatedAnchor, error) {
	if !thriftHeader.MatchString(firstBytes(content, 4096)) {
		return nil, errors.New("not generated Thrift Go")
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, document.path, content, parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}
	tokenFile := fset.File(file.Pos())
	definitions := definitionsByStart(document, content)
	result := make(map[string][]generatedAnchor)
	for _, declaration := range file.Decls {
		fn, ok := declaration.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || len(fn.Recv.List) != 1 || fn.Body == nil {
			continue
		}
		receiver := receiverTypeName(fn.Recv.List[0].Type)
		if !strings.HasSuffix(receiver, "Client") {
			continue
		}
		offset := tokenFile.Offset(fn.Name.Pos())
		occurrences := definitions[offset]
		if len(occurrences) != 1 {
			continue
		}
		wireNames := thriftWireNames(fn)
		if len(wireNames) != 1 {
			continue
		}
		service := strings.TrimSuffix(receiver, "Client")
		operation := "/" + file.Name.Name + "." + service + "/" + wireNames[0]
		relation := attribution.GeneratedFrom("thrift", document.path, "")
		anchor := relationAnchor(
			"thrift", document.path, "", operation, relation,
		)
		result[occurrences[0].symbol] = append(
			result[occurrences[0].symbol], anchor,
		)
	}
	return result, nil
}

func relationAnchor(
	protocol, generatedPath, generatorRelative, operation string,
	relation sdk.GeneratedFromAttribution,
) generatedAnchor {
	anchor := generatedAnchor{
		operation: operation, generatedPath: generatedPath,
		generatorRelative: generatorRelative,
	}
	if relation.State != sdk.AttributionStateResolved ||
		len(relation.Candidates) != 1 {
		anchor.reason = relation.Reason
		if anchor.reason == "" {
			anchor.reason = "generated_from_" + relation.State
		}
		return anchor
	}
	candidate := relation.Candidates[0]
	if candidate.Protocol != protocol || candidate.GeneratedPath != generatedPath ||
		protocol == "grpc" && candidate.GeneratorRelativePath != generatorRelative {
		anchor.reason = "generated_from_mismatch"
		return anchor
	}
	anchor.lineage = candidate.DeclarationLineage
	anchor.declarationPath = candidate.DeclarationPath
	if anchor.lineage == "" {
		anchor.reason = "missing_declaration_lineage"
	}
	return anchor
}

func collapseAnchors(symbol string, values []generatedAnchor) (symbolBinding, bool) {
	sort.Slice(values, func(i, j int) bool {
		left, right := values[i], values[j]
		if left.operation != right.operation {
			return left.operation < right.operation
		}
		if left.lineage != right.lineage {
			return left.lineage < right.lineage
		}
		if left.generatedPath != right.generatedPath {
			return left.generatedPath < right.generatedPath
		}
		return left.reason < right.reason
	})
	unique := values[:0]
	for _, value := range values {
		if len(unique) == 0 || !sameAnchor(unique[len(unique)-1], value) {
			unique = append(unique, value)
		}
	}
	values = unique
	if len(values) == 0 {
		return symbolBinding{}, false
	}
	first := values[0]
	binding := symbolBinding{
		symbol: symbol, operation: first.operation, lineage: first.lineage,
		generatedPath: first.generatedPath, declarationPath: first.declarationPath,
		generatorRelative: first.generatorRelative, reason: first.reason,
	}
	for _, value := range values[1:] {
		if value.operation != binding.operation || value.lineage != binding.lineage ||
			value.reason != binding.reason {
			if value.operation == binding.operation {
				binding.lineage = ""
				binding.reason = "multiple_generated_anchors"
				return binding, true
			}
			return symbolBinding{}, false
		}
	}
	return binding, true
}

func sameAnchor(left, right generatedAnchor) bool {
	return left.operation == right.operation && left.lineage == right.lineage &&
		left.generatedPath == right.generatedPath &&
		left.declarationPath == right.declarationPath &&
		left.generatorRelative == right.generatorRelative &&
		left.reason == right.reason
}

func (e extractor) emitReferences(
	ctx context.Context,
	corpus sdk.Corpus,
	documents []indexedDocument,
	bindings map[string]symbolBinding,
	attribution attributionLookup,
	attributionDigest string,
	emit sdk.Emit,
) (int, map[string]map[byteRange]struct{}, error) {
	unresolved := make(map[string]struct{})
	typedSpans := make(map[string]map[byteRange]struct{})
	for _, document := range documents {
		if err := ctx.Err(); err != nil {
			return len(unresolved), typedSpans, err
		}
		if !documentHasReferences(document, bindings) {
			continue
		}
		blob, err := corpus.Read(ctx, document.path)
		if err != nil {
			return len(unresolved), typedSpans, fmt.Errorf("read caller document %q: %w", document.path, err)
		}
		if len(blob.Content) > maxSourceBytes || !utf8.ValidString(blob.Content) {
			continue
		}
		starts := lineStarts(blob.Content)
		for _, occurrence := range document.occurrences {
			if !isReference(occurrence.roles) {
				continue
			}
			binding, ok := bindings[occurrence.symbol]
			if !ok {
				continue
			}
			start, end, ok := byteSpan(
				blob.Content, starts, occurrence.rangeValue, document.encoding,
			)
			if !ok {
				continue
			}
			if typedSpans[document.path] == nil {
				typedSpans[document.path] = make(map[byteRange]struct{})
			}
			typedSpans[document.path][byteRange{start: start, end: end}] = struct{}{}
			spanStart, spanEnd, present := typedCallSpan(blob.Content, start, end)
			if !present {
				if err := emitCallerFact(
					e.protocol, document.path, blob, starts, start,
					end,
					binding, attributionDigest,
					attribution.ConsumerUnits(document.path, lineAtByte(starts, start)),
					"scip", "scip_range_not_call_selector",
					classifyRole(document.path, blob.Content), emit,
				); err != nil {
					return len(unresolved), typedSpans, err
				}
				unresolved[callerIdentity(binding.operation, document.path, start, end)] = struct{}{}
				continue
			}
			reason := binding.reason
			if binding.lineage == "" && reason == "" {
				reason = "missing_declaration_lineage"
			}
			if err := emitCallerFact(
				e.protocol, document.path, blob, starts, spanStart, spanEnd,
				binding, attributionDigest,
				attribution.ConsumerUnits(document.path, lineAtByte(starts, spanStart)),
				"scip", reason,
				classifyRole(document.path, blob.Content), emit,
			); err != nil {
				return len(unresolved), typedSpans, err
			}
			if reason != "" {
				unresolved[callerIdentity(
					binding.operation, document.path, spanStart, spanEnd,
				)] = struct{}{}
			}
		}
	}
	return len(unresolved), typedSpans, nil
}

func emitCallerFact(
	protocol, filePath string,
	blob sdk.Blob,
	starts []int,
	start, end int,
	binding symbolBinding,
	attributionDigest string,
	units sdk.ConsumerUnitAttribution,
	resolution, reason, codeRole string,
	emit sdk.Emit,
) error {
	if start < 0 || end <= start || end > len(blob.Content) {
		return errors.New("caller source span is invalid")
	}
	tier, rule := "derived", "go-caller-scip-v1"
	if resolution == "syntax" {
		tier, rule = "heuristic", "go-caller-syntax-v1"
	}
	predicate, lineage := "CALLS_OPERATION", binding.lineage
	if reason != "" {
		predicate, lineage, tier = "UNRESOLVED_CALLER", "", "unresolved"
		rule = "go-caller-" + resolution + "-abstention-v1"
	}
	detail := callerDetail{
		Schema: "go-caller-detail-v1", Resolution: resolution, Protocol: protocol,
		GeneratedSymbol: binding.symbol, GeneratedPath: binding.generatedPath,
		DeclarationPath:   binding.declarationPath,
		GeneratorRelative: binding.generatorRelative,
		AttributionDigest: attributionDigest, UnresolvedReason: reason,
		DeclarationEvidence: binding.lineage,
		UnitState:           units.State, UnitReason: units.Reason,
		UnitCandidates: unitCandidateDetails(units.Candidates),
	}
	encoded, err := json.Marshal(detail)
	if err != nil {
		return err
	}
	subject := filePath + ":" + strconv.Itoa(start) + "-" + strconv.Itoa(end)
	return emit(sdk.Fact{
		Atom: sdk.AtomInput{
			SchemaVersion: schemaVersion, BlobDigest: blob.Digest,
			StartByte: start, EndByte: end, RuleID: rule,
			AdapterConfigDigest: adapterConfigDigest,
			FactFingerprint: predicate + "|" + binding.operation + "|" +
				binding.lineage + "|" + reason,
		},
		Path: filePath, StartLine: lineAtByte(starts, start),
		EndLine: lineAtByte(starts, end-1),
		Assertion: sdk.AssertionInput{
			Predicate: predicate, Subject: subject, Object: binding.operation,
			Lineage: lineage, Tier: tier, CodeRole: codeRole,
			Detail: string(encoded),
		},
	})
}

func unitCandidateDetails(
	candidates []sdk.ConsumerUnitCandidate,
) []unitCandidateDetail {
	if len(candidates) == 0 {
		return nil
	}
	result := make([]unitCandidateDetail, 0, len(candidates))
	for _, candidate := range candidates {
		result = append(result, unitCandidateDetail{
			ID:              candidate.ID,
			BuildTargets:    append([]string(nil), candidate.BuildTargets...),
			Deployables:     append([]string(nil), candidate.Deployables...),
			LogicalServices: append([]string(nil), candidate.LogicalServices...),
			Owners:          append([]string(nil), candidate.Owners...),
		})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ID < result[j].ID })
	return result
}

func callerIdentity(operation, filePath string, start, end int) string {
	return operation + "\x00" + filePath + "\x00" +
		strconv.Itoa(start) + ":" + strconv.Itoa(end)
}

func emitGap(blob sdk.Blob, reason, diagnostic string, emit sdk.Emit) error {
	if len(blob.Content) == 0 {
		return nil
	}
	if len(diagnostic) > 1024 {
		diagnostic = diagnostic[:1024]
	}
	detail, err := json.Marshal(struct {
		Schema     string `json:"schema"`
		Reason     string `json:"reason"`
		Diagnostic string `json:"diagnostic,omitempty"`
	}{
		Schema: "go-caller-gap-detail-v1", Reason: reason, Diagnostic: diagnostic,
	})
	if err != nil {
		return err
	}
	return emit(sdk.Fact{
		Atom: sdk.AtomInput{
			SchemaVersion: schemaVersion, BlobDigest: blob.Digest,
			StartByte: 0, EndByte: len(blob.Content),
			RuleID:              "go-caller-index-gap-v1",
			AdapterConfigDigest: adapterConfigDigest,
			FactFingerprint:     "CALLER_EXTRACTION_GAP|" + reason,
		},
		Path: indexPath, StartLine: 1,
		EndLine: 1 + strings.Count(blob.Content[:len(blob.Content)-1], "\n"),
		Assertion: sdk.AssertionInput{
			Predicate: "CALLER_EXTRACTION_GAP", Subject: indexPath,
			Object: reason, Tier: "unresolved", CodeRole: "generated",
			Detail: string(detail),
		},
	})
}

func parseIndex(ctx context.Context, content string) ([]indexedDocument, error) {
	byPath := make(map[string]*indexedDocument)
	metadataSeen := false
	metadataEncoding := scip.PositionEncoding_UnspecifiedPositionEncoding
	documentCount, occurrenceCount := 0, 0
	visitor := scip.IndexVisitor{
		VisitMetadata: func(ctx context.Context, metadata *scip.Metadata) error {
			if err := ctx.Err(); err != nil {
				return err
			}
			if metadataSeen {
				return errors.New("metadata appears more than once")
			}
			metadataSeen = true
			switch metadata.GetTextDocumentEncoding() {
			case scip.TextEncoding_UnspecifiedTextEncoding:
			case scip.TextEncoding_UTF8:
				metadataEncoding = scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart
			case scip.TextEncoding_UTF16:
				metadataEncoding = scip.PositionEncoding_UTF16CodeUnitOffsetFromLineStart
			default:
				return errors.New("metadata has unsupported text encoding")
			}
			return nil
		},
		VisitDocument: func(ctx context.Context, document *scip.Document) error {
			if err := ctx.Err(); err != nil {
				return err
			}
			if !metadataSeen {
				return errors.New("document appears before metadata")
			}
			documentCount++
			if documentCount > maxDocuments {
				return fmt.Errorf("more than %d documents", maxDocuments)
			}
			if err := validPath(document.GetRelativePath()); err != nil {
				return err
			}
			encoding := document.GetPositionEncoding()
			if encoding == scip.PositionEncoding_UnspecifiedPositionEncoding {
				encoding = metadataEncoding
			}
			if !validEncoding(encoding) {
				return fmt.Errorf("document %q has no position encoding", document.GetRelativePath())
			}
			stored := byPath[document.GetRelativePath()]
			if stored == nil {
				stored = &indexedDocument{
					path: document.GetRelativePath(), encoding: encoding,
				}
				byPath[stored.path] = stored
			} else if stored.encoding != encoding {
				return fmt.Errorf("document %q has conflicting encodings", stored.path)
			}
			if len(document.GetOccurrences()) > maxOccurrences-occurrenceCount {
				return fmt.Errorf("more than %d occurrences", maxOccurrences)
			}
			occurrenceCount += len(document.GetOccurrences())
			for _, occurrence := range document.GetOccurrences() {
				if occurrence.GetSymbol() == "" {
					continue
				}
				if len(occurrence.GetSymbol()) > maxSymbolBytes {
					return fmt.Errorf("symbol exceeds %d bytes", maxSymbolBytes)
				}
				rangeValue, present := occurrence.SourceRange()
				if !present || rangeValue.Validate() != nil {
					continue
				}
				stored.occurrences = append(stored.occurrences, indexedOccurrence{
					rangeValue: rangeValue, symbol: occurrence.GetSymbol(),
					roles: occurrence.GetSymbolRoles(),
				})
			}
			return nil
		},
	}
	if err := visitor.ParseStreaming(ctx, strings.NewReader(content)); err != nil {
		return nil, err
	}
	if !metadataSeen {
		return nil, errors.New("metadata is missing")
	}
	documents := make([]indexedDocument, 0, len(byPath))
	for _, document := range byPath {
		sort.Slice(document.occurrences, func(i, j int) bool {
			left, right := document.occurrences[i], document.occurrences[j]
			if comparison := left.rangeValue.CompareStrict(right.rangeValue); comparison != 0 {
				return comparison < 0
			}
			if left.symbol != right.symbol {
				return left.symbol < right.symbol
			}
			return left.roles < right.roles
		})
		documents = append(documents, *document)
	}
	sort.Slice(documents, func(i, j int) bool {
		return documents[i].path < documents[j].path
	})
	return documents, nil
}

func definitionsByStart(document indexedDocument, content string) map[int][]indexedOccurrence {
	starts := lineStarts(content)
	result := make(map[int][]indexedOccurrence)
	for _, occurrence := range document.occurrences {
		if !isDefinition(occurrence.roles) {
			continue
		}
		start, _, ok := byteSpan(content, starts, occurrence.rangeValue, document.encoding)
		if ok {
			result[start] = append(result[start], occurrence)
		}
	}
	return result
}

// typedCallSpan expands a SCIP method-identifier range to its bounded selector
// spelling. SCIP already proves the symbol edge, so this is citation shaping,
// not name-based resolution. It deliberately accepts syntactically incomplete
// source that a committed index still ranges correctly.
func typedCallSpan(content string, start, end int) (int, int, bool) {
	if start < 0 || end <= start || end > len(content) {
		return 0, 0, false
	}
	after := end
	for after < len(content) && (content[after] == ' ' || content[after] == '\t') {
		after++
	}
	if after >= len(content) || content[after] != '(' {
		return 0, 0, false
	}
	spanStart := start
	if spanStart > 0 && content[spanStart-1] == '.' {
		spanStart--
		for spanStart > 0 {
			value := content[spanStart-1]
			if isGoIdentifierByte(value) || value == '.' {
				spanStart--
				continue
			}
			break
		}
	}
	return spanStart, end, true
}

func isGoIdentifierByte(value byte) bool {
	return value == '_' || value >= 'a' && value <= 'z' ||
		value >= 'A' && value <= 'Z' || value >= '0' && value <= '9'
}

func thriftWireNames(fn *ast.FuncDecl) []string {
	var names []string
	ast.Inspect(fn.Body, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		selector, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || selector.Sel.Name != "Call" {
			return true
		}
		for _, argument := range call.Args {
			literal, ok := argument.(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				continue
			}
			value, err := strconv.Unquote(literal.Value)
			if err == nil && value != "" {
				names = appendUnique(names, value)
			}
		}
		return true
	})
	sort.Strings(names)
	return names
}

func receiverTypeName(expression ast.Expr) string {
	if pointer, ok := expression.(*ast.StarExpr); ok {
		expression = pointer.X
	}
	identifier, _ := expression.(*ast.Ident)
	if identifier == nil {
		return ""
	}
	return identifier.Name
}

func appendUnique(values []string, candidate string) []string {
	for _, value := range values {
		if value == candidate {
			return values
		}
	}
	return append(values, candidate)
}

func hasDefinitions(occurrences []indexedOccurrence) bool {
	for _, occurrence := range occurrences {
		if isDefinition(occurrence.roles) {
			return true
		}
	}
	return false
}

func documentHasReferences(document indexedDocument, bindings map[string]symbolBinding) bool {
	for _, occurrence := range document.occurrences {
		if _, present := bindings[occurrence.symbol]; present && isReference(occurrence.roles) {
			return true
		}
	}
	return false
}

func isDefinition(roles int32) bool {
	return roles&int32(scip.SymbolRole_Definition|scip.SymbolRole_ForwardDefinition) != 0
}

func isReference(roles int32) bool { return !isDefinition(roles) }

func firstBytes(content string, limit int) string {
	if len(content) <= limit {
		return content
	}
	return content[:limit]
}

func lineStarts(content string) []int {
	starts := []int{0}
	for index := range len(content) {
		if content[index] == '\n' {
			starts = append(starts, index+1)
		}
	}
	return starts
}

func byteSpan(
	content string,
	starts []int,
	rangeValue scip.Range,
	encoding scip.PositionEncoding,
) (int, int, bool) {
	start, ok := positionByte(content, starts, rangeValue.Start, encoding)
	if !ok {
		return 0, 0, false
	}
	end, ok := positionByte(content, starts, rangeValue.End, encoding)
	return start, end, ok && end >= start
}

func positionByte(
	content string,
	starts []int,
	position scip.Position,
	encoding scip.PositionEncoding,
) (int, bool) {
	if position.Line < 0 || int(position.Line) >= len(starts) || position.Character < 0 {
		return 0, false
	}
	lineStart := starts[position.Line]
	lineEnd := len(content)
	if int(position.Line)+1 < len(starts) {
		lineEnd = starts[position.Line+1] - 1
		if lineEnd > lineStart && content[lineEnd-1] == '\r' {
			lineEnd--
		}
	}
	line := content[lineStart:lineEnd]
	switch encoding {
	case scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart:
		offset := int(position.Character)
		if offset > len(line) || offset < len(line) && !utf8.RuneStart(line[offset]) {
			return 0, false
		}
		return lineStart + offset, true
	case scip.PositionEncoding_UTF16CodeUnitOffsetFromLineStart,
		scip.PositionEncoding_UTF32CodeUnitOffsetFromLineStart:
		units, byteOffset := int32(0), 0
		for byteOffset < len(line) {
			if units == position.Character {
				return lineStart + byteOffset, true
			}
			r, size := utf8.DecodeRuneInString(line[byteOffset:])
			step := int32(1)
			if encoding == scip.PositionEncoding_UTF16CodeUnitOffsetFromLineStart && r > 0xffff {
				step = 2
			}
			units += step
			if units > position.Character {
				return 0, false
			}
			byteOffset += size
		}
		if units == position.Character {
			return lineStart + byteOffset, true
		}
	}
	return 0, false
}

func lineAtByte(starts []int, offset int) int {
	return sort.Search(len(starts), func(index int) bool {
		return starts[index] > offset
	})
}

func validEncoding(encoding scip.PositionEncoding) bool {
	return encoding == scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart ||
		encoding == scip.PositionEncoding_UTF16CodeUnitOffsetFromLineStart ||
		encoding == scip.PositionEncoding_UTF32CodeUnitOffsetFromLineStart
}

func validPath(value string) error {
	if value == "" || len(value) > 4096 || strings.HasPrefix(value, "/") ||
		strings.HasPrefix(value, "-") || strings.Contains(value, `\`) ||
		path.Clean(value) != value || !utf8.ValidString(value) {
		return fmt.Errorf("invalid repository path %q", value)
	}
	for _, component := range strings.Split(value, "/") {
		if component == "" || component == "." || component == ".." {
			return fmt.Errorf("invalid repository path %q", value)
		}
	}
	return nil
}

func classifyRole(filePath, content string) string {
	if pathHasSegment(filePath, "vendor") {
		return "vendor"
	}
	head := firstBytes(content, 4096)
	if mockHeader.MatchString(head) || hasMockSegment(filePath) {
		return "mock"
	}
	if generatedHdr.MatchString(head) {
		return "generated"
	}
	if strings.HasSuffix(filePath, "_test.go") || hasTestSegment(filePath) {
		return "test"
	}
	return "production"
}

func pathHasSegment(filePath, want string) bool {
	for _, segment := range strings.Split(filePath, "/") {
		if segment == want {
			return true
		}
	}
	return false
}

func hasMockSegment(filePath string) bool {
	for _, segment := range strings.Split(filePath, "/") {
		lower := strings.ToLower(segment)
		if lower == "mock" || lower == "mocks" || lower == "mockgen" ||
			strings.HasPrefix(lower, "mock_") || strings.HasSuffix(lower, "_mock") {
			return true
		}
	}
	base := path.Base(filePath)
	return strings.HasPrefix(base, "mock_") || strings.HasSuffix(base, "_mock.go")
}

func hasTestSegment(filePath string) bool {
	for _, segment := range strings.Split(filePath, "/") {
		if segment == "tests" || segment == "testing" || segment == "testdata" {
			return true
		}
	}
	return false
}
