package t201

import "strings"

const (
	ProtoGetSymbol   = "go gomod synthetic.invalid/mono v0.0.0 gen/proto/orders/v1/OrdersClient#Get()."
	ProtoWatchSymbol = "go gomod synthetic.invalid/mono v0.0.0 gen/proto/orders/v1/OrdersClient#Watch()."
	ThriftGetSymbol  = "go gomod synthetic.invalid/mono v0.0.0 gen/thrift/ledger/LedgerClient#Get()."
)

// SmallSourceFiles returns fresh byte slices for the neutral correctness
// corpus. index.scip is intentionally absent: GenerateProfile copies the
// separately prepared, digest-pinned artifact verbatim.
func SmallSourceFiles() map[string][]byte {
	files := map[string]string{
		"go.mod": `module synthetic.invalid/mono

go 1.26
`,
		"idl/proto/orders/v1/orders.proto": `syntax = "proto3";
package synthetic.orders.v1;
option go_package = "synthetic.invalid/mono/gen/proto/orders/v1;ordersv1";
service Orders {
  rpc Get(GetRequest) returns (GetResponse);
  rpc Watch(GetRequest) returns (stream GetResponse);
}
message GetRequest { string id = 1; }
message GetResponse { string id = 1; }
`,
		"vendor/contracts/orders.proto": `syntax = "proto3";
package synthetic.orders.v1;
service Orders { rpc Get(GetRequest) returns (GetResponse); }
message GetRequest { string id = 1; }
message GetResponse { string id = 1; }
`,
		"idl/thrift/ledger.thrift": `namespace go ledger
struct GetRequest { 1: required string id }
struct GetResponse { 1: required string id }
service Ledger {
  GetResponse get(1: GetRequest request)
}
`,
		"vendor/thrift/ledger.thrift": `namespace go ledger
struct GetRequest { 1: required string id }
struct GetResponse { 1: required string id }
service Ledger {
  GetResponse get(1: GetRequest request)
}
`,
		"gen/proto/orders/v1/orders_grpc.pb.go": `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: orders/v1/orders.proto
package ordersv1
const Orders_Get_FullMethodName = "/synthetic.orders.v1.Orders/Get"
const Orders_Watch_FullMethodName = "/synthetic.orders.v1.Orders/Watch"
type OrdersClient interface {
	Get(ctx any, in any, opts ...any) (any, error)
	Watch(ctx any, in any, opts ...any) (any, error)
}
var Orders_ServiceDesc = struct{ ServiceName string }{ServiceName: "synthetic.orders.v1.Orders"}
func RegisterOrdersServer(any, any) {}
`,
		"gen/proto-copy/orders/v1/orders_grpc.pb.go": `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: orders/v1/orders.proto
package orderscopy
const Orders_Get_FullMethodName = "/synthetic.orders.v1.Orders/Get"
type OrdersClient interface { Get(ctx any, in any, opts ...any) (any, error) }
var Orders_ServiceDesc = struct{ ServiceName string }{ServiceName: "synthetic.orders.v1.Orders"}
func RegisterOrdersServer(any, any) {}
`,
		"gen/proto/collision/v1/common_grpc.pb.go": `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: collision/v1/common.proto
package collisionv1
const Common_Get_FullMethodName = "/synthetic.collision.v1.Common/Get"
type CommonClient interface { Get(ctx any, in any, opts ...any) (any, error) }
var Common_ServiceDesc = struct{ ServiceName string }{ServiceName: "synthetic.collision.v1.Common"}
`,
		"gen/thrift/ledger/ledger.go": `// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
package ledger
type LedgerClient struct{}
func (c *LedgerClient) Get(ctx any, request any) (any, error) {
	return c.Call(ctx, "get", request)
}
type LedgerProcessor struct{ processorMap map[string]any }
func NewLedgerProcessor() *LedgerProcessor {
	p := &LedgerProcessor{processorMap: map[string]any{}}
	p.processorMap["get"] = nil
	return p
}
`,
		"gen/thrift/missing/missing.go": `// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
package missing
type MissingClient struct{}
func (c *MissingClient) Get(ctx any, request any) (any, error) {
	return c.Call(ctx, "get", request)
}
type MissingProcessor struct{ processorMap map[string]any }
func NewMissingProcessor() *MissingProcessor {
	p := &MissingProcessor{processorMap: map[string]any{}}
	p.processorMap["get"] = nil
	return p
}
`,
		"gen/thrift/conflict/conflict.go": `// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
package conflict
type ConflictClient struct{}
func (c *ConflictClient) Get(ctx any, request any) (any, error) {
	return c.Call(ctx, "get", request)
}
type ConflictProcessor struct{ processorMap map[string]any }
func NewConflictProcessor() *ConflictProcessor {
	p := &ConflictProcessor{processorMap: map[string]any{}}
	p.processorMap["get"] = nil
	return p
}
`,
		"src/checkout/caller.go": `package checkout
func Load(ctx any, client interface{ Get(any, any, ...any) (any, error) }) {
	_, _ = client.Get(ctx, "order-1")
}
`,
		"src/alias/caller.go": `package alias
func Load(ctx any, c interface{ Get(any, any, ...any) (any, error) }) {
	_, _ = c.Get(ctx, "order-2")
}
`,
		"src/embedded/caller.go": `package embedded
type Client struct { interface{ Get(any, any, ...any) (any, error) } }
func Load(ctx any, c Client) {
	_, _ = c.Get(ctx, "order-3")
}
`,
		"src/wrapper/client.go": `package wrapper
type Orders interface{ Get(any, any, ...any) (any, error) }
func Load(ctx any, c Orders) {
	_, _ = c.Get(ctx, "order-4")
}
`,
		"src/dynamic/caller.go": `package dynamic
func Load(client any, method string) {
	_ = []any{client, method}
}
`,
		"src/thrift/caller.go": `package thriftcaller
func Load(ctx any, client interface{ Get(any, any) (any, error) }) {
	_, _ = client.Get(ctx, "ledger-1")
}
`,
		"src/collision/caller.go": `package collision
func Load(ctx any, client interface{ Get(any, any, ...any) (any, error) }) {
	_, _ = client.Get(ctx, "ambiguous")
}
`,
		"src/checkout/caller_test.go": `package checkout
func TestLoad(client interface{ Get(any, any, ...any) (any, error) }) {
	_, _ = client.Get(nil, "test")
}
`,
		"src/checkout/mock_client.go": `package checkout
type MockClient struct{}
func (MockClient) Get(any, any, ...any) (any, error) { return nil, nil }
func Exercise(m MockClient) { _, _ = m.Get(nil, "mock") }
`,
		"vendor/example/generated_call.go": `// Code generated by neutral-fixture. DO NOT EDIT.
package example
func Exercise(client interface{ Get(any, any, ...any) (any, error) }) {
	_, _ = client.Get(nil, "vendor")
}
`,
		"unit-snapshot.json": `{
  "version": "t20-unit-snapshot-v1",
  "mappings": [
    {"source_path":"src/checkout/caller.go","build_targets":["//src/checkout:lib"],"deployables":["checkout-api"],"logical_services":["checkout"],"owners":["team-checkout"]},
    {"source_path":"src/alias/caller.go","build_targets":["//src/alias:lib"],"deployables":["alias-worker"],"logical_services":["alias-service"],"owners":["team-orders"]},
    {"source_path":"src/embedded/caller.go","build_targets":["//src/embedded:lib","//src/shared:clients"],"deployables":["embedded-api"],"logical_services":["embedded-service","shared-client"],"owners":["team-embedded","team-platform"]},
    {"source_path":"src/wrapper/client.go","build_targets":["//src/wrapper:lib"],"deployables":["wrapper-api"],"logical_services":["wrapper-service"],"owners":[]}
  ]
}
`,
		"generated-from-snapshot.json": `{
  "version": "t20-generated-from-v1",
  "mappings": [
    {"generated_path":"gen/proto/orders/v1/orders_grpc.pb.go","generator_relative_path":"orders/v1/orders.proto","declaration_path":"idl/proto/orders/v1/orders.proto"},
    {"generated_path":"gen/proto-copy/orders/v1/orders_grpc.pb.go","generator_relative_path":"orders/v1/orders.proto","declaration_path":"idl/proto/orders/v1/orders.proto"},
    {"generated_path":"gen/thrift/ledger/ledger.go","declaration_path":"idl/thrift/ledger.thrift"},
    {"generated_path":"gen/thrift/conflict/conflict.go","declaration_path":"idl/thrift/ledger.thrift"},
    {"generated_path":"gen/thrift/conflict/conflict.go","declaration_path":"vendor/thrift/ledger.thrift"}
  ]
}
`,
	}
	out := make(map[string][]byte, len(files))
	for name, contents := range files {
		out[name] = []byte(strings.TrimPrefix(contents, "\n"))
	}
	return out
}
