package extract

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"testing"

	"github.com/bmeddeb/phebs/internal/extract/extractors/grpcgo"
	"github.com/bmeddeb/phebs/internal/extract/sdk"
	"github.com/bmeddeb/phebs/internal/store"
)

type grpcWorkerCorpus struct {
	repo, commit string
	files        map[string]string
}

func (c grpcWorkerCorpus) RepoName() string { return c.repo }
func (c grpcWorkerCorpus) Commit() string   { return c.commit }
func (c grpcWorkerCorpus) WalkFiles(ctx context.Context, visit func(string) error) error {
	paths := make([]string, 0, len(c.files))
	for filePath := range c.files {
		paths = append(paths, filePath)
	}
	sort.Strings(paths)
	for _, filePath := range paths {
		if err := ctx.Err(); err != nil {
			return err
		}
		if err := visit(filePath); err != nil {
			return err
		}
	}
	return nil
}
func (c grpcWorkerCorpus) Read(_ context.Context, filePath string) (sdk.Blob, error) {
	content, ok := c.files[filePath]
	if !ok {
		return sdk.Blob{}, fmt.Errorf("no such file %q", filePath)
	}
	sum := sha256.Sum256([]byte(content))
	return sdk.Blob{Content: content, Digest: "sha256:" + hex.EncodeToString(sum[:])}, nil
}

type grpcWorkerCorpusFactory struct{ files map[string]string }

func (grpcWorkerCorpusFactory) Lock(context.Context, string) (func(), error) {
	return func() {}, nil
}
func (f grpcWorkerCorpusFactory) New(repo, commit string) sdk.Corpus {
	return grpcWorkerCorpus{repo: repo, commit: commit, files: f.files}
}

// Regression for T13.1 review: the real worker reconciles the extractor's
// reported unresolved count against distinct tier=unresolved assertions.
// Two ambiguous occurrences in one file are two atoms supporting one semantic
// gap, and the run must publish rather than fail coverage validation.
func TestGRPCGoAmbiguityPublishesThroughWorker(t *testing.T) {
	files := map[string]string{
		"api/greeter/greeter_grpc.pb.go": `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package greeter
const Greeter_SayHello_FullMethodName = "/demo.Greeter/SayHello"
const Greeter_SayAgain_FullMethodName = "/demo.Greeter/SayAgain"
var Greeter_ServiceDesc = grpc.ServiceDesc{ServiceName: "demo.Greeter"}
func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {}
`,
		"api/billing/billing_grpc.pb.go": `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package billing
const Billing_SayHello_FullMethodName = "/demo.Billing/SayHello"
var Billing_ServiceDesc = grpc.ServiceDesc{ServiceName: "demo.Billing"}
func RegisterBillingServer(s grpc.ServiceRegistrar, srv BillingServer) {}
`,
		"cmd/app/main.go": `package main
func run(ctx context.Context, client Client) {
	client.SayAgain(ctx, req)
	client.SayHello(ctx, req)
	client.SayHello(ctx, req)
}
`,
	}
	repo := &store.Repo{Name: "example.com/app", IndexedCommitHash: unitCommit}
	evidence := newMemoryEvidence()
	worker := Worker{
		Repos: readyRepoGetter(repo), Evidence: evidence,
		NewCorpus:  grpcWorkerCorpusFactory{files: files},
		Extractors: []Extractor{grpcgo.New()},
	}
	if err := worker.Handle(context.Background(), store.Job{Target: repo.Name}); err != nil {
		t.Fatalf("Handle: %v", err)
	}
	if !evidence.published || evidence.aborted {
		t.Fatalf("run state: published=%v aborted=%v", evidence.published, evidence.aborted)
	}
	coverage := evidence.publishedWith
	if coverage.UnresolvedCount != 1 || coverage.AssertionCount != 2 || coverage.AtomCount != 3 ||
		coverage.CandidateFileCount != 3 || coverage.ReadFileCount != 3 {
		t.Fatalf("coverage = %+v, want one distinct gap over two supporting atoms", coverage)
	}
	var unresolvedFacts int
	for _, batch := range evidence.batches {
		for _, assertion := range batch.asserts {
			if assertion.Tier != store.TierUnresolved {
				continue
			}
			unresolvedFacts++
			if assertion.Predicate != "UNRESOLVED_GRPC_CALL" || assertion.Object != "SayHello" {
				t.Fatalf("unexpected unresolved assertion: %+v", assertion)
			}
		}
	}
	if unresolvedFacts != 2 {
		t.Fatalf("unresolved source facts = %d, want 2", unresolvedFacts)
	}
}
