package extract

import (
	"context"
	"strings"
	"testing"

	"github.com/scip-code/scip/bindings/go/scip"
	"google.golang.org/protobuf/proto"

	"github.com/bmeddeb/phebs/internal/analysisunit"
	"github.com/bmeddeb/phebs/internal/candidate"
	"github.com/bmeddeb/phebs/internal/extract/extractors/scipfield"
	"github.com/bmeddeb/phebs/internal/extract/sdk"
	"github.com/bmeddeb/phebs/internal/store"
)

func (c grpcWorkerCorpus) ReadSCIPIndex(ctx context.Context) (sdk.SCIPInput, error) {
	blob, err := c.Read(ctx, "index.scip")
	return sdk.SCIPInput{
		Path: "index.scip", Blob: blob, Present: err == nil,
	}, err
}

func TestSCIPFieldReferencePublishesThroughTrustedWorker(t *testing.T) {
	generated := `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/item.proto

package contract

type Item struct {
	OldName string ` + "`" + `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3"` + "`" + `
}

func (x *Item) GetOldName() string { return x.OldName }
`
	consumer := `package consumer
func use(x *contract.Item) { _ = x.GetOldName() }
`
	getter := "go gomod example.com/contracts v1.0.0 api/Item#GetOldName()."
	field := "go gomod example.com/contracts v1.0.0 api/Item#OldName."
	index := &scip.Index{
		Metadata: &scip.Metadata{},
		Documents: []*scip.Document{
			{
				RelativePath:     "contract/item.pb.go",
				PositionEncoding: scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart,
				Occurrences: []*scip.Occurrence{
					{Range: workerSCIPRange(t, generated, "OldName", 0), Symbol: field, SymbolRoles: int32(scip.SymbolRole_Definition | scip.SymbolRole_Generated)},
					{Range: workerSCIPRange(t, generated, "GetOldName", 0), Symbol: getter, SymbolRoles: int32(scip.SymbolRole_Definition | scip.SymbolRole_Generated)},
				},
			},
			{
				RelativePath:     "consumer/use.go",
				PositionEncoding: scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart,
				Occurrences: []*scip.Occurrence{
					{Range: workerSCIPRange(t, consumer, "GetOldName", 0), Symbol: getter, SymbolRoles: int32(scip.SymbolRole_ReadAccess)},
				},
			},
		},
	}
	indexBytes, err := proto.Marshal(index)
	if err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"index.scip":               string(indexBytes),
		"idl/proto/buf.yaml":       "version: v1\n",
		"idl/proto/api/item.proto": "syntax = \"proto3\"; package acme.v1; message Item { string old_name = 1; }\n",
		"contract/item.pb.go":      generated,
		"consumer/use.go":          consumer,
	}
	repo := &store.Repo{Name: "example.com/consumer", IndexedCommitHash: unitCommit}
	evidence := newMemoryEvidence()
	worker := Worker{
		Repos: readyRepoGetter(repo), Evidence: evidence,
		NewCorpus:  grpcWorkerCorpusFactory{files: files},
		Extractors: []Extractor{scipfield.New()},
	}
	if err := worker.Handle(context.Background(), store.Job{Target: repo.Name}); err != nil {
		t.Fatalf("Handle: %v", err)
	}
	if !evidence.published || evidence.aborted {
		t.Fatalf("run state: published=%v aborted=%v", evidence.published, evidence.aborted)
	}
	coverage := evidence.publishedWith
	if coverage.CandidateFileCount != 0 || coverage.ReadFileCount != 4 ||
		coverage.AssertionCount != 1 || coverage.AtomCount != 1 || coverage.UnresolvedCount != 0 {
		t.Fatalf("coverage = %+v", coverage)
	}
	if len(evidence.batches) != 1 || len(evidence.batches[0].asserts) != 1 {
		t.Fatalf("evidence batches = %+v", evidence.batches)
	}
	assertion := evidence.batches[0].asserts[0]
	if assertion.Predicate != "REFERENCES_PROTO_FIELD" || assertion.Object != "acme.v1.Item#1" ||
		assertion.Tier != store.TierExact || !strings.HasPrefix(assertion.Lineage, "contract_scip_package_v1_") {
		t.Fatalf("assertion = %+v", assertion)
	}
}

func TestSCIPFieldFocusedWorkerExcludesTestLaneAndReportsIt(t *testing.T) {
	const (
		repository    = "example.com/focused-consumer"
		generatedPath = "contract/item.pb_test.go"
		consumerPath  = "consumer/use.go"
		typedPath     = "analysis/index.scip"
	)
	generated := `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/item.proto

package contract

type Item struct {
	OldName string ` + "`" + `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3"` + "`" + `
}

func (x *Item) GetOldName() string { return x.OldName }
`
	consumer := `package consumer
func use(x *contract.Item) { _ = x.GetOldName() }
`
	getter := "go gomod example.com/contracts v1.0.0 api/Item#GetOldName()."
	field := "go gomod example.com/contracts v1.0.0 api/Item#OldName."
	index := &scip.Index{
		Metadata: &scip.Metadata{},
		Documents: []*scip.Document{
			{
				RelativePath:     generatedPath,
				PositionEncoding: scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart,
				Occurrences: []*scip.Occurrence{
					{Range: workerSCIPRange(t, generated, "OldName", 0), Symbol: field, SymbolRoles: int32(scip.SymbolRole_Definition | scip.SymbolRole_Generated)},
					{Range: workerSCIPRange(t, generated, "GetOldName", 0), Symbol: getter, SymbolRoles: int32(scip.SymbolRole_Definition | scip.SymbolRole_Generated)},
				},
			},
			{
				RelativePath:     consumerPath,
				PositionEncoding: scip.PositionEncoding_UTF8CodeUnitOffsetFromLineStart,
				Occurrences: []*scip.Occurrence{
					{Range: workerSCIPRange(t, consumer, "GetOldName", 0), Symbol: getter, SymbolRoles: int32(scip.SymbolRole_ReadAccess)},
				},
			},
		},
	}
	indexBytes, err := proto.Marshal(index)
	if err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		typedPath:                  string(indexBytes),
		"idl/proto/buf.yaml":       "version: v1\n",
		"idl/proto/api/item.proto": "syntax = \"proto3\"; package acme.v1; message Item { string old_name = 1; }\n",
		generatedPath:              generated,
		consumerPath:               consumer,
	}
	unit, err := (analysisunit.Config{
		Name:       "focused-consumer",
		Primary:    []string{consumerPath},
		Supporting: []string{generatedPath, "idl/proto", typedPath},
		TypedIndex: &analysisunit.TypedIndex{
			Kind: analysisunit.TypedIndexKindSCIP,
			Path: typedPath,
		},
	}).Scope(repository).State()
	if err != nil {
		t.Fatal(err)
	}
	manifest := &memoryCandidateManifest{
		identity:    "sha256:" + strings.Repeat("a", 64),
		corpusFiles: len(files),
		unitDigest:  unit.Digest,
		plane:       candidate.PlaneLocal,
		gitlinks: CandidateManifestGitlinks{
			Digest: emptyGitlinkInventory().digest,
		},
		typed: CandidateManifestTypedInput{
			Kind: analysisunit.TypedIndexKindSCIP, Path: typedPath,
			ObjectID:      strings.Repeat("f", 40),
			DeclaredBytes: int64(len(files[typedPath])), Present: true,
		},
	}
	for index, filePath := range []string{
		"idl/proto/api/item.proto",
		"idl/proto/buf.yaml",
		generatedPath,
		consumerPath,
	} {
		manifest.records = append(manifest.records, CandidateManifestFile{
			Path:          filePath,
			ObjectID:      strings.Repeat(string(rune('a'+index)), 40),
			DeclaredBytes: int64(len(files[filePath])),
			SourceLane:    candidate.SourceLaneForPath(filePath),
		})
	}
	reads := make(map[string]int)
	evidence := newMemoryEvidence()
	reportSink, readReport := captureOperationReport(t)
	worker := Worker{
		Repos: readyRepoGetter(&store.Repo{
			Name: repository, IndexedCommitHash: unitCommit,
			IndexedAnalysisUnit: unit,
		}),
		Evidence: evidence,
		NewCorpus: focusedManifestCorpusFactory{
			files: files, typedPath: typedPath, reads: reads,
		},
		Manifests: splitManifestProvider{
			identity: func(
				context.Context, CandidateManifestRequest,
			) (string, error) {
				return manifest.Identity(), nil
			},
			open: func(
				context.Context, CandidateManifestRequest,
			) (CandidateManifest, error) {
				return manifest, nil
			},
		},
		Extractors:       []Extractor{scipfield.New()},
		OperationReports: reportSink,
	}
	if err := worker.Handle(
		context.Background(), store.Job{Target: repository},
	); err != nil {
		t.Fatal(err)
	}
	if reads[generatedPath] != 0 {
		t.Fatalf("excluded ordinary test source reads = %d", reads[generatedPath])
	}
	if !evidence.published || len(evidence.batches) != 0 {
		t.Fatalf(
			"focused publication state: published=%v batches=%d",
			evidence.published, len(evidence.batches),
		)
	}
	coverage := evidence.publishedWith
	if coverage.ExcludedSourceFileCount != 1 ||
		coverage.ExcludedSourceDeclaredBytes != int64(len(generated)) ||
		coverage.ExcludedSCIPDocumentCount != 1 ||
		coverage.ExcludedSCIPDefinitionCount != 2 ||
		coverage.ExcludedSCIPOccurrenceCount != 2 {
		t.Fatalf("focused exclusion coverage = %+v", coverage)
	}
	report, _ := readReport()
	if len(report.Domains) != 1 ||
		report.Domains[0].Counts.ExcludedSourceFiles != 1 ||
		report.Domains[0].Counts.ExcludedSCIPDocuments != 1 ||
		report.Domains[0].Counts.ExcludedSCIPDefinitions != 2 ||
		report.Domains[0].Counts.ExcludedSCIPOccurrences != 2 ||
		report.Domains[0].Bytes.ExcludedSourceDeclared !=
			int64(len(generated)) {
		t.Fatalf("focused operation report = %+v", report)
	}
}

func workerSCIPRange(t *testing.T, content, needle string, occurrence int) []int32 {
	t.Helper()
	offset := -1
	remaining := content
	base := 0
	for index := 0; index <= occurrence; index++ {
		found := strings.Index(remaining, needle)
		if found < 0 {
			t.Fatalf("needle %q occurrence %d not found", needle, occurrence)
		}
		offset = base + found
		base = offset + len(needle)
		remaining = content[base:]
	}
	line := int32(strings.Count(content[:offset], "\n"))
	lineStart := strings.LastIndex(content[:offset], "\n") + 1
	character := int32(offset - lineStart)
	return []int32{line, character, character + int32(len(needle))}
}
