package extract

import (
	"context"
	"testing"

	"github.com/bmeddeb/phebs/internal/extract/extractors/thriftgo"
	"github.com/bmeddeb/phebs/internal/store"
)

// Regression for T19.3: the real worker publishes a thrift-consumer run in
// which generated files are read for indexing, non-generated files are
// re-read for scanning (two reads stay inside the worker's read budget), and
// the manifest reconciles registrations, heuristic calls, and distinct
// unresolved abstentions. Mirrors the grpcgo worker regression.
func TestThriftGoPublishesThroughWorker(t *testing.T) {
	generated := `// Code generated by Thrift Compiler (0.14.1). DO NOT EDIT.
package agent

type Agent interface{}

func NewAgentProcessor(handler Agent) *AgentProcessor {
	self0 := &AgentProcessor{processorMap: make(map[string]thrift.TProcessorFunction)}
	self0.processorMap["emitBatch"] = &agentProcessorEmitBatch{handler: handler}
	return self0
}
`
	mirrored := `// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.
package mirror

type Mirror interface{}

func NewMirrorProcessor(handler Mirror) *MirrorProcessor {
	self1 := &MirrorProcessor{processorMap: make(map[string]thrift.TProcessorFunction)}
	self1.processorMap["emitBatch"] = &mirrorProcessorEmitBatch{handler: handler}
	return self1
}
`
	files := map[string]string{
		"gen/agent/agent.go":   generated,
		"gen/mirror/mirror.go": mirrored,
		"cmd/app/main.go": `package main
func run(c Client, ctx context.Context, s Server) {
	agent.NewAgentProcessor(s)
	c.EmitBatch(ctx, batch)
	c.EmitBatch(ctx, batch)
}
`,
	}
	repo := &store.Repo{Name: "example.com/app", IndexedCommitHash: unitCommit}
	evidence := newMemoryEvidence()
	worker := Worker{
		Repos: readyRepoGetter(repo), Evidence: evidence,
		NewCorpus:  grpcWorkerCorpusFactory{files: files},
		Extractors: []Extractor{thriftgo.New()},
	}
	if err := worker.Handle(context.Background(), store.Job{Target: repo.Name}); err != nil {
		t.Fatalf("Handle: %v", err)
	}
	if !evidence.published || evidence.aborted {
		t.Fatalf("run state: published=%v aborted=%v", evidence.published, evidence.aborted)
	}
	coverage := evidence.publishedWith
	// One registration + one ambiguous-call abstention (two EmitBatch call
	// sites dedupe to one assertion over two supporting atoms).
	if coverage.UnresolvedCount != 1 || coverage.AssertionCount != 2 || coverage.AtomCount != 3 ||
		coverage.CandidateFileCount != 3 || coverage.ReadFileCount != 3 {
		t.Fatalf("coverage = %+v", coverage)
	}
	var registrations, unresolvedCalls int
	for _, batch := range evidence.batches {
		for _, assertion := range batch.asserts {
			switch assertion.Predicate {
			case "REGISTERS_THRIFT_SERVICE":
				registrations++
				if assertion.Object != "agent.Agent" || assertion.Tier != store.TierDerived {
					t.Fatalf("registration = %+v", assertion)
				}
			case "UNRESOLVED_THRIFT_CALL":
				unresolvedCalls++
				if assertion.Object != "EmitBatch" || assertion.Tier != store.TierUnresolved {
					t.Fatalf("unresolved call = %+v", assertion)
				}
			}
		}
	}
	if registrations != 1 || unresolvedCalls != 2 {
		t.Fatalf("registrations = %d, unresolved call facts = %d", registrations, unresolvedCalls)
	}
}
