package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

const generatedClientSource = `// Code generated by fixture. DO NOT EDIT.

package pb

import (
	"context"

	"google.golang.org/grpc"
)

type Request struct{}
type Response struct{}

type FooClient interface {
	Get(context.Context, *Request, ...grpc.CallOption) (*Response, error)
	FooOnly(context.Context, *Request, ...grpc.CallOption) (*Response, error)
}

type BarClient interface {
	Get(context.Context, *Request, ...grpc.CallOption) (*Response, error)
	BarOnly(context.Context, *Request, ...grpc.CallOption) (*Response, error)
}

type PutClient interface {
	Put(context.Context, *Request, ...grpc.CallOption) (*Response, error)
}

type Concrete struct{}

func (*Concrete) Get(context.Context, *Request, ...grpc.CallOption) (*Response, error) {
	return nil, nil
}
func (*Concrete) FooOnly(context.Context, *Request, ...grpc.CallOption) (*Response, error) {
	return nil, nil
}

type ClientConn interface {
	Invoke() error
}

type pipeClient struct{ cc ClientConn }

func (p *pipeClient) Send() error { return p.cc.Invoke() }
`

const applicationSource = `package app

import "example.com/fixture/pb"

import "context"

type Embedded interface {
	pb.PutClient
}

type Unrelated interface {
	Get(context.Context, *pb.Request) (*pb.Response, error)
}

type Ambiguous interface {
	pb.FooClient
	pb.BarClient
}

func Calls(direct pb.FooClient, concrete *pb.Concrete, embedded Embedded, unrelated Unrelated, ambiguous Ambiguous) {
	ctx := context.Background()
	req := &pb.Request{}
	direct.Get(ctx, req)
	concrete.Get(ctx, req)
	embedded.Put(ctx, req)
	unrelated.Get(ctx, req)
	ambiguous.Get(ctx, req)
}
`

const fixtureGoMod = `module example.com/fixture

go 1.23

require google.golang.org/grpc v0.0.0

replace google.golang.org/grpc => ./grpc
`

const fakeGRPCSource = `package grpc

type CallOption interface{ isCallOption() }
`

func TestOracleFindsDirectConcreteAndEmbeddedCalls(t *testing.T) {
	root, commit := makeFixture(t, clientFixtureFiles("app/application.go", applicationSource))

	first, firstDiag := runFixture(t, root, commit)
	second, secondDiag := runFixture(t, root, commit)
	if !bytes.Equal(first, second) {
		t.Fatalf("output is not deterministic:\nfirst=%s\nsecond=%s", first, second)
	}
	if !bytes.Equal(firstDiag, secondDiag) {
		t.Fatalf("diagnostics are not deterministic:\nfirst=%s\nsecond=%s", firstDiag, secondDiag)
	}

	got := decodeRecords(t, first)
	if len(got) != 4 {
		t.Fatalf("got %d records, want 4: %#v", len(got), got)
	}
	wantMethods := []string{"Get", "Get", "Put", "Get"}
	wantStrata := []string{
		stratumGeneratedClient,
		stratumConcreteClient,
		stratumEmbeddedClient,
		stratumAmbiguousClient,
	}
	for i, item := range got {
		if item.Path != "app/application.go" || item.Method != wantMethods[i] || item.Stratum != wantStrata[i] {
			t.Errorf("record %d = %#v", i, item)
		}
	}
	if !(got[0].ByteOffset < got[1].ByteOffset && got[1].ByteOffset < got[2].ByteOffset) {
		t.Fatalf("records are not in deterministic coordinate order: %#v", got)
	}
	for _, excluded := range []string{"unrelated.Get", "cc.Invoke"} {
		method := strings.TrimPrefix(excluded[strings.Index(excluded, "."):], ".")
		offset := strings.Index(applicationSource, excluded)
		if excluded == "cc.Invoke" {
			offset = strings.Index(generatedClientSource, excluded)
		}
		if offset < 0 {
			t.Fatalf("fixture is missing %s", excluded)
		}
		for _, item := range got {
			if item.Method == method && item.ByteOffset == offset+strings.Index(excluded, ".")+1 {
				t.Errorf("excluded call was emitted: %s", excluded)
			}
		}
	}

	var diag diagnostics
	if err := json.Unmarshal(bytes.TrimSpace(firstDiag), &diag); err != nil {
		t.Fatalf("decode diagnostics: %v\n%s", err, firstDiag)
	}
	if diag.MatchedSites != 4 || diag.AmbiguousSites != 1 || diag.GeneratedClientInterfaces != 3 {
		t.Fatalf("unexpected diagnostics: %#v", diag)
	}
}

func TestExactNamedClientWinsOverSameShapedGeneratedInterface(t *testing.T) {
	root, commit := makeFixture(t, clientFixtureFiles(
		"app/application.go",
		`package app

import (
	"context"
	"example.com/fixture/pb"
)

func Call(client pb.FooClient, ctx context.Context, request *pb.Request) {
	client.Get(ctx, request)
}
`,
	))
	// Make BarClient structurally identical to FooClient. The statically named
	// FooClient receiver must still resolve directly rather than disappear as
	// an ambiguous structural match.
	path := filepath.Join(root, "pb", "client.pb.go")
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	content = bytes.ReplaceAll(
		content,
		[]byte("\tBarOnly(context.Context, *Request, ...grpc.CallOption) (*Response, error)\n"),
		[]byte("\tFooOnly(context.Context, *Request, ...grpc.CallOption) (*Response, error)\n"),
	)
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatal(err)
	}
	runGit(t, root, "add", "pb/client.pb.go")
	runGit(t, root, "commit", "-q", "-m", "same-shaped clients")
	commit = strings.TrimSpace(runGit(t, root, "rev-parse", "HEAD"))

	out, diagBytes := runFixture(t, root, commit)
	records := decodeRecords(t, out)
	if len(records) != 1 || records[0].Stratum != stratumGeneratedClient {
		t.Fatalf("same-shaped direct client records = %#v", records)
	}
	var diag diagnostics
	if err := json.Unmarshal(bytes.TrimSpace(diagBytes), &diag); err != nil {
		t.Fatal(err)
	}
	if diag.AmbiguousSites != 0 {
		t.Fatalf("same-shaped direct client was reported ambiguous: %#v", diag)
	}
}

func TestStructuralGRPCClientInterfaceWithoutGeneratedHeaderIsIncluded(t *testing.T) {
	files := clientFixtureFiles(
		"app/application.go",
		`package app

import (
	"context"
	"example.com/fixture/pb"
)

func Call(client pb.FooClient, ctx context.Context, request *pb.Request) {
	client.Get(ctx, request)
}
`,
	)
	files["pb/client.pb.go"] = strings.TrimPrefix(
		files["pb/client.pb.go"],
		"// Code generated by fixture. DO NOT EDIT.\n\n",
	)
	root, commit := makeFixture(t, files)
	out, diagBytes := runFixture(t, root, commit)
	records := decodeRecords(t, out)
	if len(records) != 1 || records[0].Stratum != stratumStructuralClient {
		t.Fatalf("structural client records = %#v", records)
	}
	var diag diagnostics
	if err := json.Unmarshal(bytes.TrimSpace(diagBytes), &diag); err != nil {
		t.Fatal(err)
	}
	if diag.GeneratedClientInterfaces != 0 || diag.StructuralClientInterfaces != 3 {
		t.Fatalf("structural client diagnostics = %#v", diag)
	}
}

func TestOracleCoordinatesPointAtMethodIdentifier(t *testing.T) {
	root, commit := makeFixture(t, clientFixtureFiles("app/application.go", applicationSource))
	out, _ := runFixture(t, root, commit)
	records := decodeRecords(t, out)
	offset := strings.Index(applicationSource, "direct.Get") + len("direct.")
	line, column := lineColumn(applicationSource, offset)
	if records[0].ByteOffset != offset || records[0].Line != line || records[0].Column != column {
		t.Fatalf("first coordinate = %#v, want offset=%d line=%d column=%d", records[0], offset, line, column)
	}
}

func TestWrongPinAndDirtyCheckoutPreserveOldOutput(t *testing.T) {
	root, commit := makeFixture(t, clientFixtureFiles("app/app.go", "package app\n"))
	output := filepath.Join(t.TempDir(), "oracle.jsonl")
	old := []byte("old-output\n")
	if err := os.WriteFile(output, old, 0o644); err != nil {
		t.Fatal(err)
	}

	err := execute(options{root: root, commit: strings.Repeat("0", 40), output: output}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil || !strings.Contains(err.Error(), "does not equal") {
		t.Fatalf("wrong-pin error = %v", err)
	}
	assertFileBytes(t, output, old)

	if err := os.WriteFile(filepath.Join(root, "dirty.txt"), []byte("dirty"), 0o644); err != nil {
		t.Fatal(err)
	}
	err = execute(options{root: root, commit: commit, output: output}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil || !strings.Contains(err.Error(), "dirty") {
		t.Fatalf("dirty-checkout error = %v", err)
	}
	assertFileBytes(t, output, old)
}

func TestAssumeUnchangedCannotHideWorktreeMutation(t *testing.T) {
	root, commit := makeFixture(t, clientFixtureFiles("app/application.go", applicationSource))
	path := filepath.Join(root, "app", "application.go")
	if err := os.WriteFile(path, []byte(strings.Replace(applicationSource, "direct.Get", "direct.FooOnly", 1)), 0o644); err != nil {
		t.Fatal(err)
	}
	runGit(t, root, "update-index", "--assume-unchanged", "app/application.go")
	if status := runGit(t, root, "status", "--porcelain=v1", "--untracked-files=all"); status != "" {
		t.Fatalf("fixture mutation was not hidden by assume-unchanged: %q", status)
	}
	var stdout, stderr bytes.Buffer
	err := execute(options{root: root, commit: commit}, &stdout, &stderr)
	if err == nil || !strings.Contains(err.Error(), "does not match pinned Git blob") {
		t.Fatalf("hidden worktree mutation error = %v", err)
	}
}

func TestLoadFailurePreservesOldOutput(t *testing.T) {
	root, commit := makeFixture(t, map[string]string{
		"go.mod":    "module example.com/broken\n\ngo 1.23\n",
		"broken.go": "package broken\nfunc Broken( {\n",
	})
	output := filepath.Join(t.TempDir(), "oracle.jsonl")
	old := []byte("old-output\n")
	if err := os.WriteFile(output, old, 0o644); err != nil {
		t.Fatal(err)
	}
	err := execute(options{root: root, commit: commit, output: output}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil || (!strings.Contains(err.Error(), "load/type error") && !strings.Contains(err.Error(), "ill-typed")) {
		t.Fatalf("load error = %v", err)
	}
	assertFileBytes(t, output, old)
}

func TestGoModOnlyModuleIsBoundButUnloadedGoSourceFailsClosed(t *testing.T) {
	root, commit := makeFixture(t, map[string]string{
		"go.mod": "module example.com/empty\n\ngo 1.23\n",
	})
	out, diagBytes := runFixture(t, root, commit)
	if len(out) != 0 {
		t.Fatalf("go.mod-only module emitted records: %s", out)
	}
	var diag diagnostics
	if err := json.Unmarshal(bytes.TrimSpace(diagBytes), &diag); err != nil {
		t.Fatalf("decode diagnostics: %v: %s", err, diagBytes)
	}
	if diag.Modules != 1 || diag.LoadedPackages != 0 || diag.SemanticInputsDigest == "" {
		t.Fatalf("go.mod-only diagnostics = %#v", diag)
	}

	if err := os.WriteFile(filepath.Join(root, "ignored.go"), []byte("//go:build never\n\npackage empty\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	runGit(t, root, "add", "ignored.go")
	runGit(t, root, "commit", "-q", "-m", "unloaded source")
	commit = strings.TrimSpace(runGit(t, root, "rev-parse", "HEAD"))
	var stdout, stderr bytes.Buffer
	err := execute(options{root: root, commit: commit}, &stdout, &stderr)
	if err == nil || !strings.Contains(err.Error(), "tracked Go source exists") {
		t.Fatalf("unloaded source error = %v", err)
	}
}

func TestSuccessfulOutputReplacesAtomically(t *testing.T) {
	root, commit := makeFixture(t, clientFixtureFiles("app/application.go", applicationSource))
	output := filepath.Join(t.TempDir(), "oracle.jsonl")
	if err := os.WriteFile(output, []byte("old-output\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := execute(options{root: root, commit: commit, output: output}, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if len(decodeRecords(t, b)) != 4 {
		t.Fatalf("unexpected replacement: %s", b)
	}
	matches, err := filepath.Glob(filepath.Join(filepath.Dir(output), "."+filepath.Base(output)+".tmp-*"))
	if err != nil {
		t.Fatal(err)
	}
	if len(matches) != 0 {
		t.Fatalf("temporary outputs remain: %v", matches)
	}
}

func runFixture(t *testing.T, root, commit string) ([]byte, []byte) {
	t.Helper()
	var out, diag bytes.Buffer
	if err := execute(options{root: root, commit: commit}, &out, &diag); err != nil {
		t.Fatal(err)
	}
	return out.Bytes(), diag.Bytes()
}

func decodeRecords(t *testing.T, data []byte) []record {
	t.Helper()
	var result []record
	dec := json.NewDecoder(bytes.NewReader(data))
	for dec.More() {
		var item record
		if err := dec.Decode(&item); err != nil {
			t.Fatal(err)
		}
		result = append(result, item)
	}
	return result
}

func clientFixtureFiles(applicationPath, application string) map[string]string {
	return map[string]string{
		"go.mod":              fixtureGoMod,
		"grpc/go.mod":         "module google.golang.org/grpc\n\ngo 1.23\n",
		"grpc/call_option.go": fakeGRPCSource,
		"pb/client.pb.go":     generatedClientSource,
		applicationPath:       application,
	}
}

func makeFixture(t *testing.T, files map[string]string) (string, string) {
	t.Helper()
	root := t.TempDir()
	runGit(t, root, "init", "-q")
	runGit(t, root, "config", "user.email", "oracle@example.invalid")
	runGit(t, root, "config", "user.name", "Oracle Test")
	for rel, content := range files {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	runGit(t, root, "add", ".")
	runGit(t, root, "commit", "-q", "-m", "fixture")
	commit := strings.TrimSpace(runGit(t, root, "rev-parse", "HEAD"))
	if len(commit) != 40 {
		t.Fatalf("unexpected commit %q", commit)
	}
	return root, commit
}

func runGit(t *testing.T, root string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", root}, args...)...)
	b, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v: %s", strings.Join(args, " "), err, b)
	}
	return string(b)
}

func assertFileBytes(t *testing.T, path string, want []byte) {
	t.Helper()
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("%s = %q, want %q", path, got, want)
	}
}

func lineColumn(text string, offset int) (int, int) {
	line := strings.Count(text[:offset], "\n") + 1
	last := strings.LastIndex(text[:offset], "\n")
	return line, offset - last
}

func Example_record() {
	b, _ := json.Marshal(record{Path: "app/main.go", Line: 12, Column: 9, ByteOffset: 144, Method: "Get", Stratum: stratumGeneratedClient})
	fmt.Println(string(b))
	// Output: {"path":"app/main.go","line":12,"column":9,"byte_offset":144,"method":"Get","stratum":"generated_client_interface"}
}
