package resolvermaterialize

import (
	"context"
	"slices"
	"testing"

	"github.com/bmeddeb/phebs/internal/extract"
	"github.com/bmeddeb/phebs/internal/resolvercatalog"
)

const materializedGRPCSource = `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: orders.proto
package orders

const Orders_Get_FullMethodName = "/orders.Orders/Get"
type OrdersClient interface { Get() }
var Orders_ServiceDesc = struct{ ServiceName string }{ServiceName: "orders.Orders"}
func NewOrdersClient() OrdersClient { return nil }
`

const materializedThriftSource = `// Code generated by Thrift Compiler
package ledger

type LedgerClient struct{}
func NewLedgerClient() *LedgerClient { return &LedgerClient{} }
func (client *LedgerClient) Get() { client.Call("Get") }
func (client *LedgerClient) Call(string) {}
`

func replaceMaterializedFile(
	t *testing.T,
	manifest *materializeTestManifest,
	blobs *materializeBlobFixture,
	filePath, content string,
) {
	t.Helper()
	for index, file := range manifest.files {
		if file.Path == filePath {
			manifest.files[index] = blobs.add(filePath, content)
			return
		}
	}
	t.Fatalf("materialized fixture does not contain %q", filePath)
}

func TestOpenCallerResolversProjectsBothPacksFromOneCatalogOpen(t *testing.T) {
	registry := newMaterializeTestRegistry(t, ProtocolGRPC, ProtocolThrift)
	request, blobs := resolvedMaterializeRequest(t, t.TempDir(), registry)
	manifest := request.Manifest.(*materializeTestManifest)
	for index, file := range manifest.files {
		switch file.Path {
		case "gen/grpc/orders_grpc.pb.go":
			manifest.files[index] = blobs.add(file.Path, materializedGRPCSource)
		case "gen/thrift/ledger.go":
			manifest.files[index] = blobs.add(file.Path, materializedThriftSource)
		}
	}
	prepared, err := Build(context.Background(), request)
	if err != nil {
		t.Fatal(err)
	}
	state, err := prepared.Publish(
		context.Background(),
		func(context.Context, resolvercatalog.State) error { return nil },
	)
	if err != nil {
		t.Fatal(err)
	}
	publication, views, err := OpenCallerResolvers(
		context.Background(), request.Root, state,
		[]Protocol{ProtocolGRPC, ProtocolThrift},
	)
	if err != nil {
		t.Fatal(err)
	}
	if publication == nil || len(views) != 2 ||
		views[ProtocolGRPC].Resolver() == nil ||
		views[ProtocolThrift].Resolver() == nil {
		t.Fatalf("publication=%v views=%v", publication != nil, views)
	}
	generatedObjects := make(map[string]string)
	for _, file := range manifest.files {
		if file.Path == "gen/grpc/orders_grpc.pb.go" ||
			file.Path == "gen/thrift/ledger.go" {
			generatedObjects[file.Path] = file.ObjectID
		}
	}
	for protocol, view := range views {
		for path, objectID := range generatedObjects {
			generated, sourceErr := view.Resolver().GeneratedSource(path, objectID)
			if sourceErr != nil || !generated {
				t.Fatalf("%s resolver generated source %q = %v, %v",
					protocol, path, generated, sourceErr)
			}
		}
	}
	grpc := views[ProtocolGRPC].Descriptors()
	if len(grpc) != 1 || grpc[0].State != StateResolved || grpc[0].Reason != "" ||
		grpc[0].Operation != "/orders.Orders/Get" || grpc[0].Package != "orders" ||
		grpc[0].ClientType != "OrdersClient" || grpc[0].Method != "Get" ||
		grpc[0].DeclarationLineage != "lineage-grpc" ||
		grpc[0].ImportPath != "example.invalid/root/gen/grpc" ||
		grpc[0].GeneratedPath != "gen/grpc/orders_grpc.pb.go" ||
		grpc[0].GeneratedObjectID == "" || grpc[0].GeneratedDigest == "" ||
		!slices.Equal(grpc[0].Constructors, []string{"NewOrdersClient"}) {
		t.Fatalf("gRPC descriptors = %+v", grpc)
	}
	thrift := views[ProtocolThrift].Descriptors()
	if len(thrift) != 1 || thrift[0].Operation != "/ledger.Ledger/Get" ||
		thrift[0].DeclarationLineage != "lineage-thrift" ||
		thrift[0].ImportPath != "example.invalid/root/gen/thrift" ||
		!slices.Equal(thrift[0].Constructors, []string{"NewLedgerClient"}) {
		t.Fatalf("Thrift descriptors = %+v", thrift)
	}
	for _, generatedPath := range []string{
		"gen/grpc/orders_grpc.pb.go", "gen/thrift/ledger.go",
	} {
		count := 0
		for _, readPath := range blobs.readPaths {
			if readPath == generatedPath {
				count++
			}
		}
		if count != 1 {
			t.Fatalf("generated source %q reads = %d, want 1 (%v)",
				generatedPath, count, blobs.readPaths)
		}
	}
}

func TestOpenCallerResolverRetainsUnparseableGeneratedInput(t *testing.T) {
	registry := newMaterializeTestRegistry(t, ProtocolGRPC, ProtocolThrift)
	request, blobs := resolvedMaterializeRequest(t, t.TempDir(), registry)
	manifest := request.Manifest.(*materializeTestManifest)
	replaceMaterializedFile(
		t, manifest, blobs, "generated-from-snapshot.json",
		`{"version":"t20-generated-from-v1","mappings":[`+
			`{"protocol":"grpc","generated_path":"gen/grpc/orders_grpc.pb.go",`+
			`"declaration_path":"idl/proto/orders.proto"},`+
			`{"protocol":"thrift","generated_path":"gen/thrift/ledger.go",`+
			`"declaration_path":"idl/thrift/ledger.thrift"}]}`,
	)
	var generatedObject string
	for index, file := range manifest.files {
		if file.Path != "gen/grpc/orders_grpc.pb.go" {
			continue
		}
		manifest.files[index] = blobs.add(file.Path, "this is not Go")
		generatedObject = manifest.files[index].ObjectID
	}
	prepared, err := Build(t.Context(), request)
	if err != nil {
		t.Fatal(err)
	}
	state, err := prepared.Publish(
		t.Context(), func(context.Context, resolvercatalog.State) error { return nil },
	)
	if err != nil {
		t.Fatal(err)
	}
	_, view, err := OpenCallerResolver(
		t.Context(), request.Root, state, ProtocolGRPC,
	)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := view.Resolver().GeneratedSource(
		"gen/grpc/orders_grpc.pb.go", generatedObject,
	)
	if err != nil || !generated || len(view.Descriptors()) != 0 {
		t.Fatalf("unparseable generated input = generated:%v descriptors:%d err:%v",
			generated, len(view.Descriptors()), err)
	}
}

func TestOpenCallerResolverBackfillsOptionalGRPCSelectorAndDeduplicates(t *testing.T) {
	for _, test := range []struct {
		name         string
		explicitAlso bool
	}{
		{name: "wildcard"},
		{name: "wildcard plus equivalent explicit", explicitAlso: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			registry := newMaterializeTestRegistry(t, ProtocolGRPC, ProtocolThrift)
			request, blobs := resolvedMaterializeRequest(t, t.TempDir(), registry)
			manifest := request.Manifest.(*materializeTestManifest)
			mappings := `{"protocol":"grpc",` +
				`"generated_path":"gen/grpc/orders_grpc.pb.go",` +
				`"declaration_path":"idl/proto/orders.proto"}`
			if test.explicitAlso {
				mappings += `,{"protocol":"grpc",` +
					`"generated_path":"gen/grpc/orders_grpc.pb.go",` +
					`"generator_relative_path":"orders.proto",` +
					`"declaration_path":"idl/proto/orders.proto"}`
			}
			mappings += `,{"protocol":"thrift",` +
				`"generated_path":"gen/thrift/ledger.go",` +
				`"declaration_path":"idl/thrift/ledger.thrift"}`
			replaceMaterializedFile(
				t, manifest, blobs, "generated-from-snapshot.json",
				`{"version":"t20-generated-from-v1","mappings":[`+mappings+`]}`,
			)
			replaceMaterializedFile(
				t, manifest, blobs, "gen/grpc/orders_grpc.pb.go",
				materializedGRPCSource,
			)
			prepared, err := Build(t.Context(), request)
			if err != nil {
				t.Fatal(err)
			}
			state, err := prepared.Publish(
				t.Context(), func(context.Context, resolvercatalog.State) error { return nil },
			)
			if err != nil {
				t.Fatal(err)
			}
			_, view, err := OpenCallerResolver(
				t.Context(), request.Root, state, ProtocolGRPC,
			)
			if err != nil {
				t.Fatal(err)
			}
			descriptors := view.Descriptors()
			if len(descriptors) != 1 ||
				descriptors[0].GeneratorRelativePath != "orders.proto" ||
				descriptors[0].DeclarationLineage != "lineage-grpc" {
				t.Fatalf("wildcard descriptors = %+v", descriptors)
			}
		})
	}
}

func TestOpenCallerResolversRetainsOversizedGeneratedInputWithoutReadingIt(t *testing.T) {
	registry := newMaterializeTestRegistry(t, ProtocolGRPC, ProtocolThrift)
	request, blobs := resolvedMaterializeRequest(t, t.TempDir(), registry)
	manifest := request.Manifest.(*materializeTestManifest)
	var oversized extract.CandidateManifestFile
	for index, file := range manifest.files {
		switch file.Path {
		case "gen/grpc/orders_grpc.pb.go":
			oversized = blobs.envelope(file.Path, MaxGeneratedSymbolSourceBytes+1)
			manifest.files[index] = oversized
		case "gen/thrift/ledger.go":
			manifest.files[index] = blobs.add(file.Path, materializedThriftSource)
		}
	}
	prepared, err := Build(t.Context(), request)
	if err != nil {
		t.Fatal(err)
	}
	state, err := prepared.Publish(
		t.Context(), func(context.Context, resolvercatalog.State) error { return nil },
	)
	if err != nil {
		t.Fatal(err)
	}
	_, views, err := OpenCallerResolvers(
		t.Context(), request.Root, state, []Protocol{ProtocolGRPC, ProtocolThrift},
	)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := views[ProtocolGRPC].Resolver().GeneratedSource(
		oversized.Path, oversized.ObjectID,
	)
	if err != nil || !generated || len(views[ProtocolGRPC].Descriptors()) != 0 {
		t.Fatalf("oversized generated input = generated:%v descriptors:%d err:%v",
			generated, len(views[ProtocolGRPC].Descriptors()), err)
	}
	if len(views[ProtocolThrift].Descriptors()) != 1 {
		t.Fatalf("oversized sibling suppressed thrift descriptors: %+v",
			views[ProtocolThrift].Descriptors())
	}
	for _, readPath := range blobs.readPaths {
		if readPath == oversized.Path {
			t.Fatalf("oversized generated source was read: %v", blobs.readPaths)
		}
	}
}
