load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_go//go:def.bzl", "go_library")
proto_library(name = "message", srcs = ["message.proto"])
go_proto_library(name = "message_proto", proto = ":message", importpath = "example.test/neutral/message")
go_library(name = "message_go", embed = [":message_proto"], importpath = "example.test/neutral/message")
