package main

import (
	"regexp"
	"strings"
)

var (
	generatedHeaderRe = regexp.MustCompile(`(?m)^(//|#).*Code generated .* DO NOT EDIT`)
	mockHeaderRe      = regexp.MustCompile(`Code generated by MockGen|Code generated by mockery|Code generated by counterfeiter`)
)

// classifyRole implements T11.1 gate 2's separate classification. Precedence:
// vendor > mock > generated > test > production. A generated mock inside
// vendor/ is vendor; a MockGen file outside vendor is mock even though it is
// also generated.
func classifyRole(relPath string, content []byte) string {
	if inVendor(relPath) {
		return roleVendor
	}
	head := content
	if len(head) > 4096 {
		head = head[:4096]
	}
	if mockHeaderRe.Match(head) || pathHasMockSegment(relPath) {
		return roleMock
	}
	if generatedHeaderRe.Match(head) {
		return roleGenerated
	}
	if strings.HasSuffix(relPath, "_test.go") || hasTestSegment(relPath) {
		return roleTest
	}
	return roleProduction
}

// hasTestSegment catches test code that doesn't use the _test.go suffix —
// dapr's integration suite lives under tests/integration/... as plain .go.
func hasTestSegment(relPath string) bool {
	for _, seg := range strings.Split(relPath, "/") {
		if seg == "tests" || seg == "testdata" {
			return true
		}
	}
	return false
}

func inVendor(relPath string) bool {
	for _, seg := range strings.Split(relPath, "/") {
		if seg == "vendor" {
			return true
		}
	}
	return false
}

func pathHasMockSegment(relPath string) bool {
	parts := strings.Split(relPath, "/")
	for i, seg := range parts {
		isFile := i == len(parts)-1
		if seg == "mock" || seg == "mocks" || seg == "mocksgen" {
			return true
		}
		if isFile && (strings.HasPrefix(seg, "mock_") || strings.HasSuffix(seg, "_mock.go") || strings.HasSuffix(seg, "_mock_test.go")) {
			return true
		}
	}
	return false
}
