package main

import "testing"

// Gate 1 slice: identical input + extractor version ⇒ identical evidence IDs;
// any single field change ⇒ different ID; the encoding is injective across
// field boundaries.
func TestAtomIDDeterminism(t *testing.T) {
	base := Atom{
		SchemaVersion: schemaVersion, BlobDigest: "sha256:abc",
		StartByte: 10, EndByte: 42, RuleID: "go-grpc-client-call-v1",
		ExtractorVersion: extractorVersion, AdapterConfigDigest: "none",
		FactFingerprint: "CALLS_OPERATION|/hipstershop.CartService/GetCart",
	}
	first, second := base.ID(), base.ID()
	if first != second {
		t.Fatal("same atom produced different IDs")
	}
	variants := []Atom{base, base, base, base, base, base}
	variants[1].BlobDigest = "sha256:abd"
	variants[2].EndByte = 43
	variants[3].RuleID = "go-grpc-client-call-v2"
	variants[4].ExtractorVersion = "spike-9.9.9"
	variants[5].FactFingerprint = "CALLS_OPERATION|/hipstershop.CartService/EmptyCart"
	seen := map[string]int{}
	for i, v := range variants {
		id := v.ID()
		if prev, dup := seen[id]; dup && i != 0 {
			t.Fatalf("variants %d and %d collided: %s", prev, i, id)
		}
		seen[id] = i
	}
	// Injectivity across field boundaries: moving a character between
	// adjacent fields must change the ID.
	a := Atom{SchemaVersion: "ab", BlobDigest: "c"}
	b := Atom{SchemaVersion: "a", BlobDigest: "bc"}
	if a.ID() == b.ID() {
		t.Fatal("length-delimited encoding is not injective")
	}
}

func TestPrimitiveAtomDeduplicatesAcrossRepositories(t *testing.T) {
	a := newFact("DECLARES_OPERATION", "api/checkout.proto", "shop.Checkout/PlaceOrder",
		roleProduction, tierExact, "repo-a", "aaaaaaaa", "api/checkout.proto",
		10, 40, 2, 2, "proto-rpc-v1", "sha256:blob", "lineage:repo-a/api")
	b := newFact("DECLARES_OPERATION", "vendor/contracts/checkout.proto", "shop.Checkout/PlaceOrder",
		roleVendor, tierExact, "repo-b", "bbbbbbbb", "vendor/contracts/checkout.proto",
		10, 40, 2, 2, "proto-rpc-v1", "sha256:blob", "lineage:repo-b/vendor/contracts")
	if a.AtomID != b.AtomID {
		t.Fatalf("identical primitive content did not deduplicate: %s != %s", a.AtomID, b.AtomID)
	}
	if a.AssertionID == b.AssertionID {
		t.Fatal("occurrence-distinct assertions shared an assertion ID")
	}
	if err := a.validateAtom(); err != nil {
		t.Fatalf("validate first atom: %v", err)
	}
}

func TestFactFingerprintDistinguishesSemanticDetail(t *testing.T) {
	a := newFact("REFERENCES_PROTO_FIELD", "pkg", "shop.Cart#1:id", roleProduction, tierExact,
		"repo", "commit", "cart.go", 1, 5, 1, 1, "go-fieldref-v1", "sha256:blob", "access=field_read;go=Cart.Id")
	b := newFact("REFERENCES_PROTO_FIELD", "pkg", "shop.Cart#1:id", roleProduction, tierExact,
		"repo", "commit", "cart.go", 1, 5, 1, 1, "go-fieldref-v1", "sha256:blob", "access=field_write;go=Cart.Id")
	if a.AtomID == b.AtomID {
		t.Fatal("semantically different field references shared an atom ID")
	}
}

func TestClassifyRole(t *testing.T) {
	gen := []byte("// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage pb\n")
	mock := []byte("// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n")
	plain := []byte("package svc\n")
	cases := []struct {
		path    string
		content []byte
		want    string
	}{
		{"vendor/google.golang.org/grpc/x.go", plain, roleVendor},
		{"vendor/pb/x_mock.go", mock, roleVendor}, // vendor wins
		{"internal/mocks/client_mock.go", mock, roleMock},
		{"internal/foo/bar_mock.go", plain, roleMock}, // path signal alone
		{"internal/fake/client.go", plain, roleMock},
		{"internal/foo/client_fake.go", plain, roleMock},
		{"genproto/demo_grpc.pb.go", gen, roleGenerated},
		{"internal/svc/handler_test.go", plain, roleTest},
		{"internal/svc/handler.go", plain, roleProduction},
	}
	for _, c := range cases {
		if got := classifyRole(c.path, c.content); got != c.want {
			t.Errorf("classifyRole(%q) = %q, want %q", c.path, got, c.want)
		}
	}
}
