#!/usr/bin/env python3
"""Fail-closed regression tests for the Gate 2 v4 benchmark protocol."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from concurrent.futures import ThreadPoolExecutor
from copy import deepcopy
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch


sys.path.insert(0, str(Path(__file__).resolve().parent))

import label_prep as prep  # noqa: E402


class Gate2PreparationTests(unittest.TestCase):
    def test_gate_sampling_config_exhausts_fresh_call_precision(self) -> None:
        config = prep.gate_sampling_config()
        self.assertEqual(config["precision_holdout_per_system"], 1_000_000)
        self.assertEqual(config["precision_dev_per_system"], 0)
        self.assertEqual(
            config["precision_holdout_per_system"],
            config["registration_precision_holdout_per_system"],
        )

    def test_current_lock_binds_build_tags_and_exact_gitlink_exclusions(self) -> None:
        self.assertEqual(
            prep.SYSTEMS,
            (
                "online-boutique",
                "dapr",
                "temporal",
                "loki",
                "grpc-go",
                "etcd",
                "containerd",
                "istio",
            ),
        )
        entries = prep.load_corpus_entries(prep.DEFAULT_LOCK, prep.SYSTEMS)
        self.assertEqual(entries["dapr"]["go_build_tags"], ["unit"])
        self.assertEqual(entries["online-boutique"]["go_build_tags"], [])
        self.assertEqual(
            entries["containerd"]["commit"],
            "9e70782d9a0e92900f402b2c7a4e2aa30754503c",
        )
        self.assertEqual(entries["containerd"]["go_build_tags"], [])
        self.assertEqual(
            entries["istio"]["commit"],
            "25f4803ee1e64fc2fcb95d07b1c0e3353594e9a9",
        )
        self.assertEqual(entries["istio"]["go_build_tags"], [])
        for system in ("temporal", "loki"):
            exclusions = entries[system]["excluded_gitlinks"]
            self.assertEqual(len(exclusions), 1)
            self.assertEqual(
                set(exclusions[0]), {"path", "object_id", "reason"}
            )
            self.assertRegex(exclusions[0]["object_id"], r"^[0-9a-f]{40}$")

    def test_registration_candidates_are_source_independent_and_masked(self) -> None:
        source = r'''
package fixture

func RegisterDeclaredServer(s Server) {}

func wire(s Server) {
    pb.RegisterAlphaServer(s, alpha)
    RegisterBetaServer(s, beta)
    s.RegisterService(&Gamma_ServiceDesc, gamma)
    // pb.RegisterCommentServer(s, comment)
    _ = "pb.RegisterStringServer(s, stringValue)"
    _ = `pb.RegisterRawServer(s, raw)`
    /* pb.RegisterBlockServer(s, block) */
}
'''
        methods = [
            match.group(1)
            for match in prep.registration_matches(prep.mask_go_source(source))
        ]
        self.assertEqual(
            methods,
            ["RegisterAlphaServer", "RegisterBetaServer", "RegisterService"],
        )

    def test_source_role_precedence_covers_all_five_roles(self) -> None:
        generated = "// Code generated by fixture. DO NOT EDIT.\npackage p\n"
        mocked = "// Code generated by MockGen. DO NOT EDIT.\npackage p\n"
        self.assertEqual(prep.source_code_role("vendor/mock_x_test.go", mocked), "vendor")
        self.assertEqual(prep.source_code_role("tests/mock_x.go", mocked), "mock")
        self.assertEqual(prep.source_code_role("pkg/fake/fake.go", "package fake\n"), "mock")
        self.assertEqual(prep.source_code_role("pkg/service_fake.go", "package p\n"), "mock")
        self.assertEqual(prep.source_code_role("tests/generated_test.go", generated), "generated")
        self.assertEqual(prep.source_code_role("pkg/service_test.go", "package p\n"), "test")
        self.assertEqual(
            prep.source_code_role(
                "common/testing/taskpoller/taskpoller.go", "package taskpoller\n"
            ),
            "test",
        )
        self.assertEqual(prep.source_code_role("pkg/service.go", "package p\n"), "production")

    def test_site_identity_changes_with_commit(self) -> None:
        first = prep.site_id("fixture", "a" * 40, "p.go", 17, "Call")
        second = prep.site_id("fixture", "b" * 40, "p.go", 17, "Call")
        self.assertNotEqual(first, second)

    def test_repo_directory_named_like_system_is_not_stripped_from_fact_path(self) -> None:
        root = Path("/corpus/temporal")
        self.assertEqual(
            prep.relpath_of("temporal/server_test.go", "temporal", root),
            "temporal/server_test.go",
        )
        self.assertEqual(
            prep.relpath_of("corpus/temporal/service.go", "temporal", root),
            "service.go",
        )

    def test_burns_carry_forward_by_content_into_census(self) -> None:
        commits = prep.load_corpus_lock(prep.DEFAULT_LOCK, prep.SYSTEMS)
        _, binding, active = prep.scoped_burn_binding(
            prep.DEFAULT_BURN_LEDGER, commits
        )
        self.assertGreater(binding["coordinate_count"], 0)
        self.assertEqual(
            binding["carry_forward_schema"], "t111-burn-carry-forward-census-v3"
        )
        # Cohort overlap and source translation may collapse multiple historical
        # disclosures onto one active interval. Every historical projection
        # still has at least one fail-closed resolution record.
        self.assertGreater(binding["active_coordinate_count"], 0)
        self.assertGreaterEqual(
            binding["resolution_count"], binding["coordinate_count"]
        )
        self.assertLessEqual(
            binding["active_coordinate_count"], binding["resolution_count"]
        )
        self.assertEqual(binding["resolution_count"], sum(binding["resolution_dispositions"].values()))
        self.assertEqual(set(active), set(prep.SYSTEMS))
        self.assertTrue(
            all(active[system] for system in prep.LEGACY_BURN_COMMITS)
        )
        self.assertRegex(binding["active_coordinates_sha256"], r"^sha256:[0-9a-f]{64}$")

    def test_relocated_old_blob_does_not_hide_modified_original_path(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            corpus_dir = Path(raw) / "corpus"
            root = corpus_dir / "fixture"
            root.mkdir(parents=True)
            subprocess.run(["git", "init", "-q", str(root)], check=True)
            subprocess.run(
                ["git", "-C", str(root), "config", "user.email", "fixture@example.invalid"],
                check=True,
            )
            subprocess.run(
                ["git", "-C", str(root), "config", "user.name", "Fixture"], check=True
            )
            original = "package p\nfunc old() {\n\tcall()\n}\n"
            (root / "p.go").write_text(original, encoding="utf-8")
            subprocess.run(["git", "-C", str(root), "add", "p.go"], check=True)
            subprocess.run(["git", "-C", str(root), "commit", "-qm", "old"], check=True)
            old_commit = subprocess.check_output(
                ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
            ).strip()

            (root / "q.go").write_text(original, encoding="utf-8")
            (root / "p.go").write_text(
                "package p\nfunc changed() {\n\tdifferent()\n}\n", encoding="utf-8"
            )
            subprocess.run(["git", "-C", str(root), "add", "p.go", "q.go"], check=True)
            subprocess.run(["git", "-C", str(root), "commit", "-qm", "current"], check=True)
            current_commit = subprocess.check_output(
                ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
            ).strip()
            burned = [
                {"system": "fixture", "path": "p.go", "start_line": 3, "end_line": 3}
            ]
            base_binding = {
                "schema": "t111-burn-scope-v2",
                "ledger_sha256": "0" * 64,
                "coordinate_count": 1,
                "coordinates_sha256": "sha256:" + "1" * 64,
                "source_identities": {
                    "fixture-cohort": {
                        "fixture": prep.source_identity("fixture", old_commit)
                    }
                },
            }
            cohorts = [
                {
                    "cohort_id": "fixture-cohort",
                    "input_binding": None,
                    "source_commits": {"fixture": old_commit},
                    "source_artifacts": [],
                    "coordinates": burned,
                    "coordinate_count": 1,
                    "coordinates_sha256": "sha256:" + "1" * 64,
                }
            ]
            with (
                patch.object(
                    prep,
                    "verified_burn_ledger",
                    return_value=(burned, base_binding, cohorts),
                ),
            ):
                _, binding, active = prep.scoped_burn_binding(
                    Path(raw) / "unused.json",
                    {"fixture": current_commit},
                    corpus_dir,
                )
            self.assertIn(
                {"system": "fixture", "path": "q.go", "start_line": 3, "end_line": 3},
                active["fixture"],
            )
            self.assertIn(
                {"system": "fixture", "path": "p.go", "start_line": 1, "end_line": 4},
                active["fixture"],
            )
            self.assertEqual(binding["resolution_dispositions"]["identical_blob_relocated"], 1)
            self.assertEqual(binding["resolution_dispositions"]["changed_path_census"], 1)

    def test_cross_fixture_burns_every_identical_blob_occurrence_only(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            corpus_dir = Path(raw) / "corpus"
            source_root = corpus_dir / "source"
            target_root = corpus_dir / "target"
            unmatched_root = corpus_dir / "unmatched"
            for root in (source_root, target_root, unmatched_root):
                self._init_git_fixture(root)

            exposed = "package p\nfunc exposed() {\n\tcall()\n}\n"
            source_commit = self._commit_fixture(
                source_root, "source", {"original.go": exposed}
            )
            target_commit = self._commit_fixture(
                target_root,
                "target",
                {
                    "copies/first.go": exposed,
                    "copies/second.go": exposed,
                    "similar.go": (
                        "package p\nfunc exposed() {\n\tcall()\n\tother()\n}\n"
                    ),
                },
            )
            unmatched_commit = self._commit_fixture(
                unmatched_root,
                "unmatched",
                {"different.go": "package p\nfunc different() {}\n"},
            )
            burned, base_binding, cohorts = self._burn_stub(
                "source", source_commit, "original.go", 3, 3
            )
            commits = {
                "source": source_commit,
                "target": target_commit,
                "unmatched": unmatched_commit,
            }
            with (
                patch.object(
                    prep,
                    "verified_burn_ledger",
                    return_value=(burned, base_binding, cohorts),
                ),
                patch.object(prep, "digest_parts", wraps=prep.digest_parts) as digest,
            ):
                _, binding, active = prep.scoped_burn_binding(
                    Path(raw) / "unused.json", commits, corpus_dir
                )

            self.assertEqual(
                binding["carry_forward_schema"],
                "t111-burn-carry-forward-census-v3",
            )
            self.assertEqual(
                active["source"],
                [
                    {
                        "system": "source",
                        "path": "original.go",
                        "start_line": 3,
                        "end_line": 3,
                    }
                ],
            )
            self.assertEqual(
                active["target"],
                [
                    {
                        "system": "target",
                        "path": "copies/first.go",
                        "start_line": 3,
                        "end_line": 3,
                    },
                    {
                        "system": "target",
                        "path": "copies/second.go",
                        "start_line": 3,
                        "end_line": 3,
                    },
                ],
            )
            self.assertEqual(active["unmatched"], [])
            self.assertEqual(
                binding["resolution_dispositions"],
                {"identical_blob_relocated": 2, "identical_path": 1},
            )

            resolution_call = next(
                call
                for call in digest.call_args_list
                if call.args[0] == "t111-burn-resolution-v3"
            )
            resolutions = resolution_call.args[1]
            cross_rows = [
                row for row in resolutions if row["target_system"] == "target"
            ]
            self.assertEqual(
                [row["target_path"] for row in cross_rows],
                ["copies/first.go", "copies/second.go"],
            )
            self.assertTrue(
                all(
                    row["source_system"] == "source"
                    and row["target_system"] == "target"
                    and row["source_commit"] == source_commit
                    and row["target_commit"] == target_commit
                    for row in cross_rows
                )
            )
            self.assertIn(
                "t111-active-burn-census-v3",
                [call.args[0] for call in digest.call_args_list],
            )

            with patch.object(
                prep,
                "verified_burn_ledger",
                return_value=(burned, base_binding, cohorts),
            ):
                _, reversed_binding, _ = prep.scoped_burn_binding(
                    Path(raw) / "unused.json",
                    dict(reversed(list(commits.items()))),
                    corpus_dir,
                )
            self.assertEqual(
                reversed_binding["active_coordinates_sha256"],
                binding["active_coordinates_sha256"],
            )
            self.assertEqual(
                reversed_binding["resolution_sha256"],
                binding["resolution_sha256"],
            )

    def test_cross_fixture_match_does_not_relax_same_system_fail_closed(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            corpus_dir = Path(raw) / "corpus"
            source_root = corpus_dir / "source"
            target_root = corpus_dir / "target"
            for root in (source_root, target_root):
                self._init_git_fixture(root)

            exposed = "package p\nfunc exposed() {\n\tcall()\n}\n"
            old_commit = self._commit_fixture(
                source_root, "old", {"original.go": exposed}
            )
            source_commit = self._commit_fixture(
                source_root,
                "deleted",
                {"replacement.go": "package p\nfunc replacement() {}\n"},
                remove=("original.go",),
            )
            target_commit = self._commit_fixture(
                target_root, "copy", {"copy.go": exposed}
            )
            burned, base_binding, cohorts = self._burn_stub(
                "source", old_commit, "original.go", 3, 3
            )
            with patch.object(
                prep,
                "verified_burn_ledger",
                return_value=(burned, base_binding, cohorts),
            ):
                with self.assertRaisesRegex(
                    prep.PrepError,
                    "disclosed source cannot be mapped into the current tree",
                ):
                    prep.scoped_burn_binding(
                        Path(raw) / "unused.json",
                        {"source": source_commit, "target": target_commit},
                        corpus_dir,
                    )

    def test_burn_source_fixture_must_remain_in_current_corpus(self) -> None:
        burned, base_binding, cohorts = self._burn_stub(
            "missing", "a" * 40, "old.go", 1, 1
        )
        with tempfile.TemporaryDirectory() as raw:
            with patch.object(
                prep,
                "verified_burn_ledger",
                return_value=(burned, base_binding, cohorts),
            ):
                with self.assertRaisesRegex(
                    prep.PrepError, "burn source fixture is absent"
                ):
                    prep.scoped_burn_binding(
                        Path(raw) / "unused.json", {}, Path(raw) / "corpus"
                    )

    def test_same_system_unique_span_translation_is_preserved(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            corpus_dir = Path(raw) / "corpus"
            root = corpus_dir / "fixture"
            self._init_git_fixture(root)
            old_commit = self._commit_fixture(
                root,
                "old",
                {"p.go": "package p\nfunc f() {\n\tunique()\n}\n"},
            )
            current_commit = self._commit_fixture(
                root,
                "current",
                {"p.go": "package p\nfunc f() {\n\t// inserted\n\tunique()\n}\n"},
            )
            burned, base_binding, cohorts = self._burn_stub(
                "fixture", old_commit, "p.go", 3, 3
            )
            with patch.object(
                prep,
                "verified_burn_ledger",
                return_value=(burned, base_binding, cohorts),
            ):
                _, binding, active = prep.scoped_burn_binding(
                    Path(raw) / "unused.json",
                    {"fixture": current_commit},
                    corpus_dir,
                )
            self.assertEqual(
                active["fixture"],
                [
                    {
                        "system": "fixture",
                        "path": "p.go",
                        "start_line": 4,
                        "end_line": 4,
                    }
                ],
            )
            self.assertEqual(
                binding["resolution_dispositions"],
                {"unique_line_span_translation": 1},
            )

    def test_exposed_sample_is_appended_as_an_idempotent_v2_burn_cohort(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            ledger = root / "burn-ledger.json"
            ledger.write_bytes(prep.DEFAULT_BURN_LEDGER.read_bytes())
            artifact = root / "artifact"
            artifact.mkdir()
            rows_by_name = {
                "sites.census.jsonl": [],
                "sites.dev.jsonl": [
                    {
                        "site_id": "site-1",
                        "system": "fixture",
                        "path": "p.go",
                        "line": 7,
                        "column": 3,
                        "method": "Call",
                    }
                ],
                "sites.holdout.jsonl": [],
            }
            hashes = {}
            for name, rows in rows_by_name.items():
                prep.write_jsonl(artifact / name, rows)
                hashes[name] = prep.sha256_file(artifact / name)
            binding = "sha256:" + "7" * 64
            manifest = {
                "schema": prep.SCHEMA,
                "gate_design_fixed": True,
                "randomization": {"input_binding": binding},
                "provenance": {"locked_commits": {"fixture": "8" * 40}},
                "artifacts_sha256": hashes,
                "burn_ledger": {"ledger_sha256": prep.sha256_file(ledger)},
            }
            (artifact / "manifest.json").write_text(
                json.dumps(manifest), encoding="utf-8"
            )
            first = prep.append_exposed_sample_to_burn_ledger(artifact, ledger)
            cohorts, _ = prep.load_burn_ledger_cohorts(ledger)
            added = [row for row in cohorts if row["input_binding"] == binding]
            self.assertEqual(len(added), 1)
            self.assertEqual(
                added[0]["coordinates"],
                [
                    {
                        "system": "fixture",
                        "path": "p.go",
                        "start_line": 7,
                        "end_line": 7,
                    }
                ],
            )
            before = ledger.read_bytes()
            second = prep.append_exposed_sample_to_burn_ledger(artifact, ledger)
            self.assertEqual(second, first)
            self.assertEqual(ledger.read_bytes(), before)

    def test_seed_receipt_rejects_constants_and_wrong_input_binding(self) -> None:
        binding = "sha256:" + "a" * 64
        valid = self._seed_record(binding)
        self.assertEqual(
            prep.validate_seed_record(valid, expected_input_binding=binding), valid
        )
        with self.assertRaisesRegex(prep.PrepError, "different locked inputs"):
            prep.validate_seed_record(
                valid, expected_input_binding="sha256:" + "b" * 64
            )
        with self.assertRaisesRegex(prep.PrepError, "legacy, zero"):
            prep.validate_seed_record(
                {**valid, "seed_hex": f"{prep.LEGACY_DIAGNOSTIC_SEED:064x}"}
            )
        with self.assertRaisesRegex(prep.PrepError, "legacy, zero"):
            prep.validate_seed_record(
                {**valid, "seed_hex": binding.removeprefix("sha256:")}
            )
        with self.assertRaisesRegex(prep.PrepError, "plausible entropy"):
            prep.validate_seed_record(
                {**valid, "seed_hex": "0123456789abcdef" * 4}
            )
        with self.assertRaisesRegex(prep.PrepError, "independently auditable"):
            prep.validate_seed_record({**valid, "source": "os_csprng"})
        with self.assertRaisesRegex(prep.PrepError, "recorded after"):
            prep.validate_seed_record(
                {**valid, "recorded_at": valid["input_committed_at"]}
            )
        beacon = self._seed_record(binding, source="public_randomness_beacon")
        with self.assertRaisesRegex(prep.PrepError, "official NIST"):
            prep.validate_seed_record(
                {**beacon, "source_reference": "https://example.test/pulse/1"}
            )
        with self.assertRaisesRegex(prep.PrepError, "complete"):
            prep.validate_seed_record({**valid, "unexpected": True})
        with self.assertRaisesRegex(prep.PrepError, "persistent input commitment time"):
            prep.validate_seed_record(
                valid,
                expected_input_binding=binding,
                expected_input_committed_at="2026-07-13T11:59:00Z",
            )

    def test_input_commitment_requires_exact_initial_github_revision(self) -> None:
        manifest = {
            "randomization": {
                "input_committed_at": "2026-07-13T12:00:30Z",
                "input_binding": "sha256:" + "1" * 64,
            },
            "attempt_claim": {"schema": "attempt"},
            "systems": ["fixture"],
            "sampling_config": {},
            "decision_rule": {},
            "burn_ledger": {},
            "protocol_coverage": {},
            "frames": {
                frame: {
                    "definition": frame,
                    "extractor_independent": True,
                    "population_size": 0,
                    "strata": [],
                }
                for frame in prep.FRAMES
            },
            "power_analysis": {"attainable": True},
            "provenance": {},
        }
        document = prep.input_commitment_document(manifest)
        api_url = "https://api.github.com/gists/abc123"
        revision = "a" * 40
        created_at = "2026-07-13T11:59:00Z"
        receipt = {
            "schema": "t111-github-initial-gist-receipt-v1",
            "api_url": api_url,
            "revision": revision,
            "created_at": created_at,
            "document_sha256": "sha256:" + prep.hashlib.sha256(document).hexdigest(),
        }
        seed = {"commitment_github_receipt": receipt}
        responses = {
            api_url: {
                "url": api_url,
                "created_at": created_at,
                "history": [{"version": revision, "committed_at": created_at}],
            },
            api_url + "/" + revision: {
                "files": {
                    "commitment.json": {
                        "content": document.decode(),
                        "truncated": False,
                    }
                }
            },
        }
        prep.verify_input_commitment_publication(
            manifest, seed, responses.__getitem__
        )
        responses[api_url + "/" + revision]["files"]["commitment.json"][
            "content"
        ] = "changed\n"
        with self.assertRaisesRegex(prep.PrepError, "cannot be verified"):
            prep.verify_input_commitment_publication(
                manifest, seed, responses.__getitem__
            )

    def test_input_commitment_and_power_ignore_seed_realized_dev_allocation(self) -> None:
        first = self._power_manifest(population=400, holdout=200)
        first.update(
            randomization={
                "input_committed_at": "2026-07-13T12:00:30Z",
                "input_binding": "sha256:" + "1" * 64,
                "selection_seed_digests": {
                    frame: "sha256:" + "a" * 64 for frame in prep.FRAMES
                },
            },
            attempt_claim={"schema": "attempt"},
            decision_rule={},
            burn_ledger={},
            protocol_coverage={},
            provenance={},
        )
        for frame in prep.FRAMES:
            detail = first["frames"][frame]
            detail.update(
                definition=frame,
                extractor_independent=frame.endswith("recall"),
                population_size=sum(
                    int(row["population_size"]) for row in detail["strata"]
                ),
            )
            for row in detail["strata"]:
                row["census_inclusion_probability"] = 1
                row["holdout_inclusion_probability"] = (
                    int(row["holdout_sample_size"])
                    / int(row["sample_population_size"])
                )
                row["dev_inclusion_probability"] = None
        first["power_analysis"] = prep.preflight_gate_design(first)

        second = deepcopy(first)
        second["randomization"]["selection_seed_digests"] = {
            frame: "sha256:" + "b" * 64 for frame in prep.FRAMES
        }
        for index, frame in enumerate(prep.FRAMES, start=1):
            for row in second["frames"][frame]["strata"]:
                row["dev_sample_size"] = index
        second["power_analysis"] = prep.preflight_gate_design(second)

        self.assertEqual(first["power_analysis"], second["power_analysis"])
        first_document = prep.input_commitment_document(first)
        self.assertEqual(first_document, prep.input_commitment_document(second))
        commitment = json.loads(first_document)
        self.assertEqual(commitment["schema"], prep.INPUT_COMMITMENT_SCHEMA)
        for frame in prep.FRAMES:
            for row in commitment["frames"][frame]["strata"]:
                self.assertEqual(
                    set(row), set(prep.INPUT_COMMITMENT_STRATUM_FIELDS)
                )
                self.assertNotIn("dev_sample_size", row)
                self.assertNotIn("dev_inclusion_probability", row)
        invalid_commitment = deepcopy(commitment)
        invalid_commitment["systems"] = list(prep.SYSTEMS)
        invalid_commitment["frames"][prep.FRAMES[0]]["strata"][0][
            "dev_sample_size"
        ] = 1
        invalid_document = (
            json.dumps(invalid_commitment, indent=2, sort_keys=True) + "\n"
        ).encode()
        with self.assertRaisesRegex(prep.PrepError, "realized or invalid"):
            prep.validate_input_commitment_document(invalid_document)
        api_url = "https://api.github.com/gists/abc123"
        revision = "c" * 40
        created_at = "2026-07-13T11:59:00Z"
        receipt = {
            "schema": "t111-github-initial-gist-receipt-v1",
            "api_url": api_url,
            "revision": revision,
            "created_at": created_at,
            "document_sha256": "sha256:"
            + prep.hashlib.sha256(first_document).hexdigest(),
        }
        responses = {
            api_url: {
                "url": api_url,
                "created_at": created_at,
                "history": [{"version": revision, "committed_at": created_at}],
            },
            api_url + "/" + revision: {
                "files": {
                    "commitment.json": {
                        "content": first_document.decode(),
                        "truncated": False,
                    }
                }
            },
        }
        prep.verify_input_commitment_publication(
            second,
            {"commitment_github_receipt": receipt},
            responses.__getitem__,
        )

    def test_commit_set_attempt_rejects_rebinding_tampering_and_symlink(self) -> None:
        commits = {
            system: f"{index + 1:040x}"
            for index, system in enumerate(prep.SYSTEMS)
        }
        with self.assertRaisesRegex(prep.PrepError, "every fixed"):
            prep.commit_set_lineage_binding(
                {system: commits[system] for system in prep.SYSTEMS[:4]}
            )
        base = "sha256:" + "a" * 64
        final = "sha256:" + "b" * 64
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            with patch.object(prep, "SEALED_CLAIM_ROOT", root):
                claim = prep.locked_attempt_claim(
                    commits=commits,
                    base_input_binding=base,
                    input_binding=final,
                    committed_at="2026-07-13T12:00:30Z",
                    create=True,
                )
                self.assertEqual(claim["input_binding"], final)
                repeated = prep.locked_attempt_claim(
                    commits=commits,
                    base_input_binding=base,
                    input_binding=final,
                    committed_at="2026-07-13T12:00:30Z",
                    create=True,
                )
                self.assertEqual(repeated, claim)
                with self.assertRaisesRegex(prep.PrepError, "different final input"):
                    prep.locked_attempt_claim(
                        commits=commits,
                        base_input_binding=base,
                        input_binding="sha256:" + "e" * 64,
                        committed_at="2026-07-13T12:01:30Z",
                        create=True,
                    )
                with self.assertRaisesRegex(prep.PrepError, "different input lineage"):
                    prep.locked_attempt_claim(
                        commits=commits,
                        base_input_binding="sha256:" + "c" * 64,
                        input_binding=None,
                        committed_at=None,
                        create=False,
                    )
                path = next(root.glob(".t111-gate2-source-*.attempt.json"))
                path.write_text("{}\n", encoding="utf-8")
                with self.assertRaisesRegex(prep.PrepError, "invalid.*attempt"):
                    prep.locked_attempt_claim(
                        commits=commits,
                        base_input_binding=base,
                        input_binding=final,
                        committed_at=None,
                        create=False,
                    )

        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            lineage = prep.commit_set_lineage_binding(commits).removeprefix("sha256:")
            target = root / "target.json"
            target.write_text("{}\n", encoding="utf-8")
            (root / f".t111-gate2-source-{lineage}.attempt.json").symlink_to(target)
            with patch.object(prep, "SEALED_CLAIM_ROOT", root):
                with self.assertRaisesRegex(prep.PrepError, "missing persistent"):
                    prep.locked_attempt_claim(
                        commits=commits,
                        base_input_binding=base,
                        input_binding=final,
                        committed_at=None,
                        create=False,
                    )

    def test_seed_binding_changes_with_locked_inputs(self) -> None:
        base = {
            "systems": ("fixture",),
            "sampling_config": {"n": 1},
            "corpus_lock_sha256": "1" * 64,
            "facts_sha256": {"fixture.facts.jsonl": "2" * 64},
            "burn_binding": {"coordinate_count": 700},
            "corpus_inputs": {
                "fixture": {
                    "commit": "3" * 40,
                    "excluded_gitlinks": [],
                    "go_build_tags": [],
                }
            },
            "population_binding": {
                prep.FRAME_CALL_RECALL: {
                    "population_size": 1,
                    "sha256": "sha256:" + "5" * 64,
                }
            },
        }
        first = prep.seed_input_binding(**base)
        changed = deepcopy(base)
        changed["facts_sha256"]["fixture.facts.jsonl"] = "4" * 64
        self.assertNotEqual(first, prep.seed_input_binding(**changed))
        changed = deepcopy(base)
        changed["typed_call_oracle_diagnostics"] = {
            "fixture": {"semantic_inputs_digest": "sha256:" + "6" * 64}
        }
        self.assertNotEqual(first, prep.seed_input_binding(**changed))

    def test_selection_is_reproducible_but_changes_with_audit_entropy(self) -> None:
        population = [
            {
                "site_id": f"site-{index}",
                "system": "fixture",
                "stratum": "fixture|risk",
            }
            for index in range(20)
        ]
        first = prep.select_by_system(population, 5, 1, "entropy-a", "holdout")
        repeated = prep.select_by_system(population, 5, 1, "entropy-a", "holdout")
        second = prep.select_by_system(population, 5, 1, "entropy-b", "holdout")
        self.assertEqual(
            [row["site_id"] for row in first],
            [row["site_id"] for row in repeated],
        )
        self.assertNotEqual(
            {row["site_id"] for row in first},
            {row["site_id"] for row in second},
        )

    def test_typed_oracle_coordinates_are_strictly_cross_checked(self) -> None:
        data = b"package p\nfunc f() { client.Call(ctx) }\n"
        offset = data.index(b"Call")
        line, column = prep.byte_coordinate(data, offset)
        record = {
            "path": "p.go",
            "line": line,
            "column": column,
            "byte_offset": offset,
            "method": "Call",
            "stratum": "generated_client_interface",
        }
        diagnostics = {
            "schema": prep.TYPED_ORACLE_DIAGNOSTICS_SCHEMA,
            "runtime_version": "go1.26.5",
            "goos": "darwin",
            "goarch": "arm64",
            "semantic_inputs_digest": "sha256:" + "a" * 64,
            "modules": 1,
            "loaded_packages": 1,
            "root_source_files": 1,
            "external_source_files": 0,
            "generated_client_interfaces": 1,
            "structural_client_interfaces": 0,
            "selector_call_sites": 1,
            "matched_sites": 1,
            "ambiguous_sites": 0,
            "deduplicated_matches": 0,
        }
        completed = SimpleNamespace(
            returncode=0,
            stdout=(json.dumps(record) + "\n").encode(),
            stderr=(json.dumps(diagnostics) + "\n").encode(),
        )
        with patch.object(prep.subprocess, "run", return_value=completed):
            with patch.object(prep, "git_blob", return_value=data):
                rows, actual_diagnostics = prep.scan_typed_call_recall_frame(
                    "fixture", Path("/corpus"), "1" * 40, [], {"p.go"}
                )
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0]["method"], "Call")
        self.assertEqual(actual_diagnostics, diagnostics)
        bad = {**record, "byte_offset": offset + 1}
        completed.stdout = (json.dumps(bad) + "\n").encode()
        with patch.object(prep.subprocess, "run", return_value=completed):
            with patch.object(prep, "git_blob", return_value=data):
                with self.assertRaisesRegex(prep.PrepError, "does not point"):
                    prep.scan_typed_call_recall_frame(
                        "fixture", Path("/corpus"), "1" * 40, [], {"p.go"}
                    )
        completed.stdout = (json.dumps(record) + "\n").encode()
        diagnostics["matched_sites"] = 2
        completed.stderr = (json.dumps(diagnostics) + "\n").encode()
        with patch.object(prep.subprocess, "run", return_value=completed):
            with patch.object(prep, "git_blob", return_value=data):
                with self.assertRaisesRegex(prep.PrepError, "match count"):
                    prep.scan_typed_call_recall_frame(
                        "fixture", Path("/corpus"), "1" * 40, [], {"p.go"}
                    )

    def test_source_frame_binding_ignores_extractor_outcomes(self) -> None:
        populations = {
            frame: [
                {
                    "site_id": f"{frame}-site",
                    "system": "fixture",
                    "stratum": f"fixture|{frame}",
                    "extracted": False,
                    "emitted_roles": [],
                }
            ]
            for frame in prep.FRAMES
        }
        kwargs = {
            "systems": ("fixture",),
            "sampling_config": {"n": 1},
            "corpus_lock_sha256": "1" * 64,
            "burn_binding": {"active_coordinate_count": 0},
            "corpus_inputs": {"fixture": {"commit": "2" * 40}},
            "prep_script_sha256": "3" * 64,
        }
        first = prep.frame_selection_bindings(populations=populations, **kwargs)
        changed = deepcopy(populations)
        changed[prep.FRAME_CALL_RECALL][0].update(
            extracted=True, emitted_roles=["vendor"], object="pkg.Service/Method"
        )
        second = prep.frame_selection_bindings(populations=changed, **kwargs)
        self.assertEqual(
            first[prep.FRAME_CALL_RECALL], second[prep.FRAME_CALL_RECALL]
        )
        seed = self._seed_record("sha256:" + "a" * 64)
        self.assertEqual(
            prep.audited_selection_seeds(first, seed)[prep.FRAME_CALL_RECALL],
            prep.audited_selection_seeds(second, seed)[prep.FRAME_CALL_RECALL],
        )

    def test_code_snapshot_mutations_fail_closed(self) -> None:
        with patch.object(prep, "sha256_file", side_effect=["changed", "verifier"]):
            with self.assertRaisesRegex(prep.PrepError, "label_prep.py changed"):
                prep.verify_code_snapshots("prep", "verifier")
        with patch.object(prep, "sha256_file", side_effect=["prep", "changed"]):
            with self.assertRaisesRegex(prep.PrepError, "gate34_common.py changed"):
                prep.verify_code_snapshots("prep", "verifier")

    def test_role_selection_is_independent_of_emitted_roles(self) -> None:
        candidates = []
        for role in sorted(prep.CODE_ROLES):
            for index in range(3):
                candidates.append(
                    {
                        "site_id": f"{role}-{index}",
                        "candidate_role": role,
                        "extracted": True,
                        "role": "production",
                    }
                )
        first_population = prep.build_role_population(candidates, [])
        first = prep.select_role_cohort(
            first_population, 2, "seed", "role", require_full_quota=True
        )
        mutated = [{**row, "role": "vendor"} for row in candidates]
        second_population = prep.build_role_population(mutated, [])
        second = prep.select_role_cohort(
            second_population, 2, "seed", "role", require_full_quota=True
        )
        self.assertEqual(
            [row["site_id"] for row in first], [row["site_id"] for row in second]
        )

        without_vendor = [
            row for row in first_population if row["candidate_role"] != "vendor"
        ]
        with self.assertRaisesRegex(prep.PrepError, "vendor"):
            prep.select_role_cohort(
                without_vendor, 1, "seed", "role", require_full_quota=True
            )

        risk_population = prep.build_role_population(
            [
                {
                    "site_id": "grpc",
                    "candidate_role": "production",
                    "risk": "known_rpc_name",
                    "extracted": False,
                },
                {
                    "site_id": "unrelated",
                    "candidate_role": "production",
                    "risk": "other_exported_selector",
                    "extracted": False,
                },
            ],
            [],
        )
        self.assertEqual([row["site_id"] for row in risk_population], ["grpc"])

    def test_power_preflight_includes_both_protocol_families(self) -> None:
        manifest = self._power_manifest(population=300, holdout=300)
        report = prep.preflight_gate_design(manifest)
        self.assertEqual(report["schema"], "t111-gate2-power-v2")
        self.assertTrue(report["attainable"])
        self.assertEqual(report["family_size"], 0)
        self.assertEqual(set(report["best_case"]), {
            "client_call", "registration", "census_unique_sites",
            "holdout_unique_floor", "dev_unique_ceiling",
            "blind_fraction_denominator_at_bound", "maximum_recall_label_units",
            "blind_fraction_lower_bound",
        })

        impossible = self._power_manifest(population=1000, holdout=20)
        diagnostic = prep.preflight_gate_design(
            impossible,
            raise_on_failure=False,
        )
        self.assertEqual(diagnostic["family_size"], 4)
        with self.assertRaisesRegex(prep.PrepError, "statistically incapable"):
            prep.preflight_gate_design(impossible)

        nonexhaustive_precision = self._power_manifest(population=300, holdout=300)
        nonexhaustive_precision["frames"][prep.FRAME_CALL_PRECISION]["strata"][0][
            "holdout_sample_size"
        ] = 299
        with self.assertRaisesRegex(prep.PrepError, "not an exhaustive fresh holdout"):
            prep.preflight_gate_design(nonexhaustive_precision)

        unsampled = self._power_manifest(population=300, holdout=300)
        unsampled["frames"][prep.FRAME_CALL_PRECISION]["strata"].append(
            {
                "id": "fixture|vendor",
                "system": "fixture",
                "label": "vendor",
                "population_size": 1,
                "sample_population_size": 1,
                "census_size": 0,
                "holdout_sample_size": 0,
                "dev_sample_size": 0,
            }
        )
        with self.assertRaisesRegex(prep.PrepError, "zero holdout inclusion"):
            prep.preflight_gate_design(unsampled)

        empty_fixture = deepcopy(manifest)
        empty_fixture["systems"].append("empty-fixture")
        empty_report = prep.preflight_gate_design(
            empty_fixture, raise_on_failure=False
        )
        self.assertFalse(empty_report["attainable"])
        self.assertTrue(
            any(
                "empty-fixture" in reason
                and "fixture precision bound is below 90%" in reason
                for reason in empty_report["reasons"]
            )
        )

        insufficient_capacity = deepcopy(manifest)
        insufficient_capacity["frames"][prep.FRAME_CALL_RECALL]["strata"][0][
            "holdout_sample_size"
        ] = 199
        insufficient_capacity["frames"][prep.FRAME_REGISTRATION_RECALL]["strata"][0][
            "holdout_sample_size"
        ] = 100
        with self.assertRaisesRegex(prep.PrepError, "200 positives and 100"):
            prep.preflight_gate_design(insufficient_capacity)

        outcome_independent_manifest = deepcopy(manifest)
        outcome_independent_manifest["realized_selection"] = {
            "dev": ["same-site"] * 10_000,
            "holdout": [],
            "extractor_outcomes": [False] * 10_000,
        }
        outcome_independent = prep.preflight_gate_design(outcome_independent_manifest)
        self.assertTrue(outcome_independent["attainable"])
        self.assertEqual(outcome_independent, report)

        for index, frame in enumerate(prep.FRAMES, start=1):
            for row in outcome_independent_manifest["frames"][frame]["strata"]:
                row["dev_sample_size"] = index * 10_000
        self.assertEqual(
            prep.preflight_gate_design(outcome_independent_manifest), report
        )

    def test_blind_fraction_lower_bound_is_seed_independent_and_conservative(self) -> None:
        manifest = self._power_manifest(population=400, holdout=200)
        manifest["holdout"]["unique_census_sites"] = 25
        for frame in prep.FRAMES:
            for row in manifest["frames"][frame]["strata"]:
                row["dev_sample_size"] = 10
        report = prep.preflight_gate_design(manifest)
        best = report["best_case"]
        self.assertEqual(best["holdout_unique_floor"], 400)
        self.assertEqual(best["dev_unique_ceiling"], 120)
        self.assertEqual(best["blind_fraction_denominator_at_bound"], 545)
        self.assertAlmostEqual(
            best["blind_fraction_lower_bound"], 400 / 545, places=15
        )
        # Any realized overlap can only reduce the unique dev denominator or
        # increase the unique holdout numerator relative to these bounds.
        for realized_holdout, realized_dev in ((400, 120), (450, 20), (500, 0)):
            actual = realized_holdout / (25 + realized_holdout + realized_dev)
            self.assertGreaterEqual(actual, best["blind_fraction_lower_bound"])

    def test_sealed_publication_is_atomic_and_one_shot(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            output = Path(raw) / "gate2"
            manifest = self._sealed_manifest()
            with patch.object(prep, "SEALED_CLAIM_ROOT", Path(raw)):
                prep.publish_artifacts(output, manifest, [], [], [], force=False)
                self.assertEqual(
                    {path.name for path in output.iterdir()},
                    {
                        "manifest.json",
                        "seed.json",
                        "attempt.json",
                        "burn-ledger.input.json",
                        "sites.census.jsonl",
                        "sites.dev.jsonl",
                        "sites.holdout.jsonl",
                        "key.jsonl",
                    },
                )
                with self.assertRaisesRegex(prep.PrepError, "already exists"):
                    prep.publish_artifacts(
                        output, self._sealed_manifest(), [], [], [], force=False
                    )

    def test_diagnostics_cannot_create_or_overwrite_sealed_bundle_roots(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            claim_root = root / "labeling"
            current = claim_root / "g2-v4"
            historical = claim_root / "g2-v3"
            with (
                patch.object(prep, "SEALED_CLAIM_ROOT", claim_root),
                patch.object(prep, "DEFAULT_ARTIFACTS", current),
            ):
                for output in (
                    claim_root,
                    current,
                    current / "nested",
                    historical,
                ):
                    with self.subTest(output=output):
                        with self.assertRaisesRegex(
                            prep.PrepError, "reserved for sealed"
                        ):
                            prep.publish_artifacts(
                                output,
                                {"gate_design_fixed": False},
                                [],
                                [],
                                [],
                                force=True,
                            )
                with self.assertRaisesRegex(
                    prep.PrepError, "reserved for sealed"
                ):
                    prep.build_artifacts(
                        SimpleNamespace(
                            systems=prep.SYSTEMS[0],
                            commitment_only=False,
                            dry_run=False,
                            output_dir=current,
                        )
                    )

            external_sealed = root / "external-sealed"
            external_sealed.mkdir()
            (external_sealed / "manifest.json").write_text(
                '{"gate_design_fixed": true}\n', encoding="utf-8"
            )
            with self.assertRaisesRegex(prep.PrepError, "sealed/unknown"):
                prep.publish_artifacts(
                    external_sealed,
                    {"gate_design_fixed": False},
                    [],
                    [],
                    [],
                    force=True,
                )

            unknown_bundle = root / "unknown-bundle"
            unknown_bundle.mkdir()
            (unknown_bundle / "manifest.json").write_text("{}\n", encoding="utf-8")
            with self.assertRaisesRegex(prep.PrepError, "sealed/unknown"):
                prep.publish_artifacts(
                    unknown_bundle,
                    {"gate_design_fixed": False},
                    [],
                    [],
                    [],
                    force=True,
                )

            with self.assertRaisesRegex(
                prep.PrepError, "explicit unsealed manifest"
            ):
                prep.publish_artifacts(
                    root / "new-unknown",
                    {},
                    [],
                    [],
                    [],
                    force=True,
                )

            partial_sealed = root / "partial-sealed"
            partial_sealed.mkdir()
            (partial_sealed / "attempt.json").write_text("{}\n", encoding="utf-8")
            with self.assertRaisesRegex(prep.PrepError, "sealed bundle state"):
                prep.publish_artifacts(
                    partial_sealed,
                    {"gate_design_fixed": False},
                    [],
                    [],
                    [],
                    force=True,
                )

            diagnostic = root / "diagnostic"
            prep.publish_artifacts(
                diagnostic,
                {"gate_design_fixed": False, "generation": 1},
                [],
                [],
                [],
                force=False,
            )
            prep.publish_artifacts(
                diagnostic,
                {"gate_design_fixed": False, "generation": 2},
                [],
                [],
                [],
                force=True,
            )
            self.assertEqual(
                json.loads((diagnostic / "manifest.json").read_text())["generation"],
                2,
            )

    def test_staging_failure_leaves_no_bundle_and_claim_blocks_retry(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            output = Path(raw) / "gate2"
            with patch.object(prep, "SEALED_CLAIM_ROOT", Path(raw)):
                with patch.object(prep, "write_jsonl", side_effect=RuntimeError("injected")):
                    with self.assertRaisesRegex(RuntimeError, "injected"):
                        prep.publish_artifacts(
                            output, self._sealed_manifest(), [], [], [], force=False
                        )
                self.assertFalse(output.exists())
                claims = list(Path(raw).glob(".t111-gate2-*.sealed-claim"))
                self.assertEqual(len(claims), 1)
                with self.assertRaisesRegex(prep.PrepError, "already claimed"):
                    prep.publish_artifacts(
                        output, self._sealed_manifest(), [], [], [], force=False
                    )

    def test_concurrent_publishers_have_exactly_one_winner(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            output = Path(raw) / "gate2"

            def publish() -> str:
                try:
                    prep.publish_artifacts(
                        output, self._sealed_manifest(), [], [], [], force=False
                    )
                except prep.PrepError:
                    return "rejected"
                return "published"

            with patch.object(prep, "SEALED_CLAIM_ROOT", Path(raw)):
                with ThreadPoolExecutor(max_workers=2) as pool:
                    outcomes = list(pool.map(lambda _: publish(), range(2)))
            self.assertEqual(sorted(outcomes), ["published", "rejected"])
            self.assertTrue((output / "manifest.json").is_file())

    def test_force_and_legacy_seed_are_forbidden_for_sealed_generation(self) -> None:
        base = {
            "systems": ",".join(prep.SYSTEMS),
            "seed": prep.LEGACY_DIAGNOSTIC_SEED,
            **prep.gate_sampling_config(),
        }
        with self.assertRaisesRegex(prep.PrepError, "--force"):
            prep.build_artifacts(SimpleNamespace(**base, force=True))
        with self.assertRaisesRegex(prep.PrepError, "diagnostic-only"):
            prep.build_artifacts(
                SimpleNamespace(**{**base, "seed": 112, "force": False})
            )
        custom = {**base, "systems": prep.SYSTEMS[0], "force": False}
        with self.assertRaisesRegex(prep.PrepError, "commit-inputs is fixed"):
            prep.build_artifacts(SimpleNamespace(**custom, commitment_only=True))
        with self.assertRaisesRegex(prep.PrepError, "--dry-run"):
            prep.build_artifacts(
                SimpleNamespace(**base, force=False, dry_run=True)
            )
        with tempfile.TemporaryDirectory() as raw:
            existing = Path(raw) / "gate2"
            existing.mkdir()
            with self.assertRaisesRegex(prep.PrepError, "already exists"):
                prep.build_artifacts(
                    SimpleNamespace(
                        **base,
                        force=False,
                        dry_run=False,
                        output_dir=existing,
                    )
                )

    def test_only_exact_declared_gitlink_is_excluded(self) -> None:
        commit = "1" * 40
        gitlink = "2" * 40
        tree = (
            f"100644 blob {'3' * 40}\tmain.go\0"
            f"160000 commit {gitlink}\tdocs/theme\0"
        ).encode()

        def fake_git(_root: Path, *arguments: str) -> bytes:
            if arguments[:2] == ("rev-parse", "--verify"):
                return (commit + "\n").encode()
            if arguments and arguments[0] == "status":
                return b""
            if arguments and arguments[0] == "ls-tree":
                return tree
            raise AssertionError(arguments)

        with tempfile.TemporaryDirectory() as raw, patch.object(prep, "git", fake_git):
            root = Path(raw)
            with self.assertRaisesRegex(prep.PrepError, "undeclared gitlink"):
                prep.pinned_tracked_files(root, commit)
            wrong = [{"path": "docs/theme", "object_id": "4" * 40, "reason": "docs"}]
            with self.assertRaisesRegex(prep.PrepError, "does not match"):
                prep.pinned_tracked_files(root, commit, wrong)
            exact = [{"path": "docs/theme", "object_id": gitlink, "reason": "docs"}]
            files, special = prep.pinned_tracked_files(root, commit, exact)
            self.assertEqual(files, ["main.go"])
            self.assertEqual(special, [{"kind": "gitlink", **exact[0]}])
            absent = [{"path": "docs/other", "object_id": gitlink, "reason": "docs"}]
            with self.assertRaisesRegex(prep.PrepError, "undeclared gitlink"):
                prep.pinned_tracked_files(root, commit, absent)

    def test_pinned_source_symlink_is_a_bound_logical_alias(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / "fixture"
            self._init_git_fixture(root)
            target = root / "targets/source.go"
            target.parent.mkdir(parents=True)
            target.write_text("package fixture\n", encoding="utf-8")
            (root / "alias.go").symlink_to("targets/source.go")
            subprocess.run(["git", "-C", str(root), "add", "-A"], check=True)
            subprocess.run(
                ["git", "-C", str(root), "commit", "-qm", "safe alias"],
                check=True,
            )
            commit = subprocess.check_output(
                ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
            ).strip()

            files, special = prep.pinned_tracked_files(root, commit)
            self.assertEqual(files, ["alias.go", "targets/source.go"])
            aliases = [row for row in special if row["kind"] == "source_symlink"]
            self.assertEqual(len(aliases), 1)
            self.assertEqual(aliases[0]["target"], "targets/source.go")
            self.assertEqual(aliases[0]["resolved_path"], "targets/source.go")
            self.assertRegex(aliases[0]["object_id"], r"^[0-9a-f]{40}$")
            self.assertRegex(aliases[0]["resolved_object_id"], r"^[0-9a-f]{40}$")
            self.assertEqual(prep.git_blob(root, commit, "alias.go"), b"package fixture\n")
            self.assertEqual(
                list(prep.git_blobs(root, commit, ["alias.go", "targets/source.go"])),
                [
                    ("alias.go", b"package fixture\n"),
                    ("targets/source.go", b"package fixture\n"),
                ],
            )
            tree = prep.git_tree_blobs(root, commit)
            self.assertEqual(tree["alias.go"], tree["targets/source.go"])

            (root / "alias.go").unlink()
            (root / "alias.go").symlink_to("../outside.go")
            subprocess.run(["git", "-C", str(root), "add", "alias.go"], check=True)
            subprocess.run(
                ["git", "-C", str(root), "commit", "-qm", "escaping alias"],
                check=True,
            )
            escaping_commit = subprocess.check_output(
                ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
            ).strip()
            with self.assertRaisesRegex(prep.PrepError, "escapes"):
                prep.pinned_tracked_files(root, escaping_commit)

    def test_short_registration_service_is_rejected(self) -> None:
        commit = "1" * 40
        row = {
            "predicate": "IMPLEMENTS_SERVICE",
            "path": "p.go",
            "start_byte": 0,
            "end_byte": 1,
            "start_line": 1,
            "end_line": 1,
            "object": "ShortService",
            "code_role": "production",
            "tier": "exact",
            "commit": commit,
        }
        with tempfile.TemporaryDirectory() as raw:
            facts = Path(raw)
            (facts / "fixture.facts.jsonl").write_text("", encoding="utf-8")
            with patch.object(prep, "load_verified_facts", return_value=[row]):
                with self.assertRaisesRegex(prep.PrepError, "fully-qualified"):
                    prep.operation_facts(
                        "fixture", facts, commit, Path(raw) / "corpus"
                    )

    def test_registration_fact_coordinate_supports_helper_and_direct_calls(self) -> None:
        helper = b"pb.RegisterAlphaServer(server, impl)"
        direct = b"server.RegisterService(&Alpha_ServiceDesc, impl)"
        fact = {
            "path": "p.go",
            "start_byte": 0,
            "end_byte": len(helper),
            "object": "pkg.Alpha",
        }
        self.assertEqual(prep.registration_position(helper, fact), (3, "RegisterAlphaServer"))
        direct_fact = {**fact, "end_byte": len(direct)}
        self.assertEqual(
            prep.registration_position(direct, direct_fact), (7, "RegisterService")
        )

    def test_precision_frames_collapse_only_consensus_module_contexts(self) -> None:
        source = "package p\nfunc wire() { client.Do(ctx); pb.RegisterAlphaServer(s, impl) }\n"
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / "fixture"
            self._init_git_fixture(root)
            commit = self._commit_fixture(root, "source", {"p.go": source})
            data = source.encode()

            call_start = data.index(b"client.Do")
            call_end = data.index(b";", call_start)
            call = {
                "path": "p.go",
                "start_byte": call_start,
                "end_byte": call_end,
                "start_line": 2,
                "end_line": 2,
                "object": "/pkg.Alpha/Do",
                "code_role": "production",
                "tier": "exact",
                "atom_id": "ea_b",
            }
            calls = prep.build_precision_frame(
                "fixture", root, commit, [call, {**call, "atom_id": "ea_a"}], {"p.go"}
            )
            self.assertEqual(len(calls), 1)
            self.assertEqual(calls[0]["atom_id"], "ea_a")
            with self.assertRaisesRegex(prep.PrepError, "disagree"):
                prep.build_precision_frame(
                    "fixture",
                    root,
                    commit,
                    [call, {**call, "object": "/other.Alpha/Do"}],
                    {"p.go"},
                )

            registration_start = data.index(b"pb.RegisterAlphaServer")
            registration_end = data.index(b" }", registration_start)
            registration = {
                "path": "p.go",
                "start_byte": registration_start,
                "end_byte": registration_end,
                "start_line": 2,
                "end_line": 2,
                "object": "pkg.Alpha",
                "code_role": "production",
                "tier": "exact",
                "atom_id": "ea_d",
            }
            registrations = prep.build_registration_precision_frame(
                "fixture",
                root,
                commit,
                [registration, {**registration, "atom_id": "ea_c"}],
                {"p.go"},
            )
            self.assertEqual(len(registrations), 1)
            self.assertEqual(registrations[0]["atom_id"], "ea_c")
            with self.assertRaisesRegex(prep.PrepError, "disagree"):
                prep.build_registration_precision_frame(
                    "fixture",
                    root,
                    commit,
                    [registration, {**registration, "object": "other.Alpha"}],
                    {"p.go"},
                )

    def test_gate_calls_quarantine_noncanonical_heuristics(self) -> None:
        exact = {
            "tier": "exact",
            "object": "/pkg.v1.Service/Call",
            "fact_fingerprint": "sha256:" + "1" * 64,
        }
        heuristic = {
            "tier": "heuristic",
            "object": "/?.Service/Call",
            "fact_fingerprint": "sha256:" + "2" * 64,
        }
        eligible, quarantine = prep.gate_call_facts(
            "fixture", [exact, heuristic]
        )
        self.assertEqual(eligible, [exact])
        self.assertEqual(quarantine["count"], 1)
        self.assertEqual(quarantine["by_tier"], {"heuristic": 1})
        with self.assertRaisesRegex(prep.PrepError, "non-canonical identity"):
            prep.gate_call_facts(
                "fixture", [{**heuristic, "tier": "exact"}]
            )

    @staticmethod
    def _init_git_fixture(root: Path) -> None:
        root.mkdir(parents=True)
        subprocess.run(["git", "init", "-q", str(root)], check=True)
        subprocess.run(
            [
                "git",
                "-C",
                str(root),
                "config",
                "user.email",
                "fixture@example.invalid",
            ],
            check=True,
        )
        subprocess.run(
            ["git", "-C", str(root), "config", "user.name", "Fixture"],
            check=True,
        )

    @staticmethod
    def _commit_fixture(
        root: Path,
        message: str,
        files: dict[str, str],
        *,
        remove: tuple[str, ...] = (),
    ) -> str:
        for rel in remove:
            (root / rel).unlink()
        for rel, content in files.items():
            target = root / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
        subprocess.run(["git", "-C", str(root), "add", "-A"], check=True)
        subprocess.run(
            ["git", "-C", str(root), "commit", "-qm", message], check=True
        )
        return subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
        ).strip()

    @staticmethod
    def _burn_stub(
        source_system: str,
        source_commit: str,
        path: str,
        start_line: int,
        end_line: int,
    ) -> tuple[list[dict[str, object]], dict[str, object], list[dict[str, object]]]:
        burned: list[dict[str, object]] = [
            {
                "system": source_system,
                "path": path,
                "start_line": start_line,
                "end_line": end_line,
            }
        ]
        coordinates_sha256 = "sha256:" + "1" * 64
        base_binding: dict[str, object] = {
            "schema": "t111-burn-scope-v2",
            "ledger_sha256": "0" * 64,
            "coordinate_count": 1,
            "coordinates_sha256": coordinates_sha256,
            "source_identities": {
                "fixture-cohort": {
                    source_system: prep.source_identity(
                        source_system, source_commit
                    )
                }
            },
        }
        cohorts: list[dict[str, object]] = [
            {
                "cohort_id": "fixture-cohort",
                "input_binding": None,
                "source_commits": {source_system: source_commit},
                "source_artifacts": [],
                "coordinates": burned,
                "coordinate_count": 1,
                "coordinates_sha256": coordinates_sha256,
            }
        ]
        return burned, base_binding, cohorts

    @staticmethod
    def _seed_record(
        binding: str, *, source: str = "external_witness"
    ) -> dict[str, object]:
        source_reference = (
            "https://beacon.nist.gov/beacon/2.0/chain/2/pulse/123"
            if source == "public_randomness_beacon"
            else "witness-receipt-test-1"
        )
        record = {
            "schema": prep.SEED_RECORD_SCHEMA,
            "input_binding": binding,
            "input_committed_at": "2026-07-13T12:00:30Z",
            "commitment_reference": "https://api.github.com/gists/abc123",
            "commitment_published_at": "2026-07-13T11:59:00Z",
            "commitment_document_sha256": "sha256:" + "9" * 64,
            "commitment_github_receipt": {
                "schema": "t111-github-initial-gist-receipt-v1",
                "api_url": "https://api.github.com/gists/abc123",
                "revision": "a" * 40,
                "created_at": "2026-07-13T11:59:00Z",
                "document_sha256": "sha256:" + "9" * 64,
            },
            "source": source,
            "source_reference": source_reference,
            "source_output_hex": (
                "cfa7b7fd8f043be76c64d0b53e95f6fdd29b37cec39a1ab9432cd110d1dbf242"
                "87d62d935b274917461252f8b9a82bdeecfc4ec5c35443141cfa83a1cc878c11"
            ),
            "recorded_at": "2026-07-13T12:01:00Z",
        }
        if source == "public_randomness_beacon":
            record["source_payload"] = {
                "pulse": {
                    "uri": source_reference,
                    "version": "2.0",
                    "period": 60_000,
                    "chainIndex": 2,
                    "pulseIndex": 123,
                    "statusCode": 0,
                    "timeStamp": record["recorded_at"],
                    "certificateId": "1" * 128,
                    "localRandomValue": "2" * 128,
                    "precommitmentValue": "3" * 128,
                    "signatureValue": "4" * 1024,
                    "outputValue": str(record["source_output_hex"]).upper(),
                    "listValues": [
                        {
                            "uri": "https://beacon.nist.gov/beacon/2.0/chain/2/pulse/122",
                            "type": "previous",
                            "value": "5" * 128,
                        }
                    ],
                }
            }
        else:
            record["source_payload"] = {
                "reference": source_reference,
                "output_hex": record["source_output_hex"],
                "recorded_at": record["recorded_at"],
                "witness": "test witness",
                "signature": "test-signature-value",
            }
        record["source_payload_sha256"] = "sha256:" + prep.hashlib.sha256(
            prep.canonical_json(record["source_payload"]).encode()
        ).hexdigest()
        record["seed_hex"] = prep.digest_parts(
            "t111-gate2-audit-seed-derive-v2",
            record["input_binding"],
            record["input_committed_at"],
            record["commitment_reference"],
            record["commitment_published_at"],
            record["commitment_document_sha256"],
            record["commitment_github_receipt"]["revision"],
            record["source"],
            record["source_reference"],
            record["source_output_hex"],
            record["source_payload_sha256"],
            record["recorded_at"],
        )
        return record

    @staticmethod
    def _sealed_manifest() -> dict[str, object]:
        binding = "sha256:" + "a" * 64
        base_binding = "sha256:" + "d" * 64
        commits = {
            system: f"{index + 1:040x}"
            for index, system in enumerate(prep.SYSTEMS)
        }
        seed_record = Gate2PreparationTests._seed_record(binding)
        attempt_claim = {
            "schema": "t111-gate2-commit-set-attempt-v2",
            "source_lineage_binding": prep.commit_set_lineage_binding(commits),
            "commits": dict(sorted(commits.items())),
            "base_input_binding": base_binding,
            "input_binding": binding,
            "committed_at": seed_record["input_committed_at"],
        }
        return {
            "schema": prep.SCHEMA,
            "gate_design_fixed": True,
            "attempt_claim": attempt_claim,
            "provenance": {"locked_commits": commits},
            "randomization": {
                "mode": "audited-unpredictable-sha256-rank-v2",
                "input_binding": binding,
                "base_input_binding": base_binding,
                "input_committed_at": seed_record["input_committed_at"],
                "seed_record": seed_record,
            },
        }

    @staticmethod
    def _power_manifest(population: int, holdout: int) -> dict[str, object]:
        def stratum(
            identifier: str, system: str, label: str, holdout_size: int
        ) -> dict[str, object]:
            return {
                "id": identifier,
                "system": system,
                "label": label,
                "population_size": population,
                "sample_population_size": population,
                "census_size": 0,
                "holdout_sample_size": min(holdout_size, population),
                "dev_sample_size": 0,
            }

        role_strata = [
            {
                "id": f"role|{role}",
                "system": "role",
                "label": role,
                "population_size": 20,
                "sample_population_size": 20,
                "census_size": 0,
                "holdout_sample_size": 20,
                "dev_sample_size": 0,
            }
            for role in sorted(prep.CODE_ROLES)
        ]
        return {
            "systems": ["fixture"],
            "sampling_config": prep.gate_sampling_config(),
            "holdout": {"unique_census_sites": 0},
            "frames": {
                prep.FRAME_CALL_PRECISION: {
                    "strata": [
                        stratum(
                            "fixture|production", "fixture", "production", population
                        )
                    ]
                },
                prep.FRAME_CALL_RECALL: {
                    "strata": [stratum("fixture|risk", "fixture", "risk", holdout)]
                },
                prep.FRAME_REGISTRATION_PRECISION: {
                    "strata": [
                        stratum(
                            "fixture|production", "fixture", "production", population
                        )
                    ]
                },
                prep.FRAME_REGISTRATION_RECALL: {
                    "strata": [
                        stratum("fixture|production", "fixture", "production", holdout)
                    ]
                },
                prep.FRAME_ROLE: {"strata": role_strata},
            },
        }


if __name__ == "__main__":
    unittest.main()
