// Package genrepo writes and verifies repository projections of the canonical
// glossary. It is used by go:generate, tests, and the ordinary merge bar.
package genrepo

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/bmeddeb/phebs/internal/glossary"
)

const (
	SourcePath     = "internal/glossary/glossary.json"
	GoPath         = "internal/glossary/terms_generated.go"
	TypeScriptPath = "ui/src/glossary.generated.ts"
	SchemaPath     = "internal/glossary/glossary_schema_generated.json"
	MCPPath        = "internal/mcp/glossary_descriptions_generated.json"
	ManualPath     = "docs/MANUAL.md"
)

// ProjectionPaths returns the standalone generated files in stable order.
func ProjectionPaths() []string {
	return []string{GoPath, TypeScriptPath, SchemaPath, MCPPath}
}

// WriteRepository regenerates every checked-in projection under root.
func WriteRepository(root string) error {
	artifacts, err := repositoryArtifacts(root)
	if err != nil {
		return err
	}
	for _, output := range standaloneOutputs(artifacts) {
		path := filepath.Join(root, filepath.FromSlash(output.path))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create glossary output directory for %s: %w", output.path, err)
		}
		if err := os.WriteFile(path, output.content, 0o644); err != nil {
			return fmt.Errorf("write glossary projection %s: %w", output.path, err)
		}
	}
	manualPath := filepath.Join(root, filepath.FromSlash(ManualPath))
	manual, err := os.ReadFile(manualPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", ManualPath, err)
	}
	updated, err := replaceManualProjection(manual, artifacts.Manual)
	if err != nil {
		return fmt.Errorf("update %s: %w", ManualPath, err)
	}
	if err := os.WriteFile(manualPath, updated, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", ManualPath, err)
	}
	return nil
}

// VerifyRepository fails when any checked-in projection differs from the
// canonical generated bytes.
func VerifyRepository(root string) error {
	artifacts, err := repositoryArtifacts(root)
	if err != nil {
		return err
	}
	for _, output := range standaloneOutputs(artifacts) {
		actual, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(output.path)))
		if err != nil {
			return fmt.Errorf("read glossary projection %s: %w", output.path, err)
		}
		if !bytes.Equal(actual, output.content) {
			return driftError(output.path)
		}
	}
	manual, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(ManualPath)))
	if err != nil {
		return fmt.Errorf("read %s: %w", ManualPath, err)
	}
	projected, err := manualProjection(manual)
	if err != nil {
		return fmt.Errorf("verify %s: %w", ManualPath, err)
	}
	if !bytes.Equal(projected, completeManualProjection(artifacts.Manual)) {
		return driftError(ManualPath)
	}
	return nil
}

type output struct {
	path    string
	content []byte
}

func repositoryArtifacts(root string) (glossary.Artifacts, error) {
	raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(SourcePath)))
	if err != nil {
		return glossary.Artifacts{}, fmt.Errorf("read canonical glossary: %w", err)
	}
	artifacts, err := glossary.Generate(raw)
	if err != nil {
		return glossary.Artifacts{}, fmt.Errorf("generate glossary projections: %w", err)
	}
	return artifacts, nil
}

func standaloneOutputs(artifacts glossary.Artifacts) []output {
	return []output{
		{path: GoPath, content: artifacts.Go},
		{path: TypeScriptPath, content: artifacts.TypeScript},
		{path: SchemaPath, content: artifacts.Schema},
		{path: MCPPath, content: artifacts.MCP},
	}
}

func replaceManualProjection(manual, projection []byte) ([]byte, error) {
	start, end, err := manualProjectionBounds(manual)
	if err != nil {
		return nil, err
	}
	result := make([]byte, 0, len(manual)-end+start+len(projection))
	result = append(result, manual[:start]...)
	result = append(result, completeManualProjection(projection)...)
	result = append(result, manual[end:]...)
	return result, nil
}

func manualProjection(manual []byte) ([]byte, error) {
	start, end, err := manualProjectionBounds(manual)
	if err != nil {
		return nil, err
	}
	return manual[start:end], nil
}

func manualProjectionBounds(manual []byte) (int, int, error) {
	begin := []byte(glossary.ManualBeginMarker)
	finish := []byte(glossary.ManualEndMarker)
	if bytes.Count(manual, begin) != 1 || bytes.Count(manual, finish) != 1 {
		return 0, 0, errors.New("generated glossary markers must each occur exactly once")
	}
	start := bytes.Index(manual, begin)
	endStart := bytes.Index(manual, finish)
	if endStart <= start {
		return 0, 0, errors.New("generated glossary markers are out of order")
	}
	return start, endStart + len(finish), nil
}

func completeManualProjection(projection []byte) []byte {
	result := make([]byte, 0, len(projection)+len(glossary.ManualBeginMarker)+
		len(glossary.ManualEndMarker)+2)
	result = append(result, glossary.ManualBeginMarker...)
	result = append(result, '\n')
	result = append(result, projection...)
	result = append(result, glossary.ManualEndMarker...)
	return result
}

func driftError(path string) error {
	return fmt.Errorf(
		"generated glossary projection %s is stale; run go generate ./internal/glossary",
		path,
	)
}
