package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"regexp"
	"sort"
	"strings"
)

// generatedHeaderRe matches both Apache Thrift generated-file markers observed
// in the wild: the modern form ("Code generated by Thrift Compiler (0.13+)")
// and the legacy form ("Autogenerated by Thrift Compiler (0.9.x-0.12)").
// The corpus exercises 0.14.1 and 0.19.0; the legacy form is covered by a
// synthetic fixture test because no HEAD-stable public corpus was found.
var generatedHeaderRe = regexp.MustCompile(`^// (Code generated by Thrift Compiler|Autogenerated by Thrift Compiler)`)

var processorCtorRe = regexp.MustCompile(`^New([A-Z]\w*)Processor$`)

func isGeneratedThrift(content []byte) bool {
	return generatedHeaderRe.Match(content)
}

// stubService is one Thrift service recovered from generated Go code.
type stubService struct {
	Scope string // generated package name
	Name  string // service name, e.g. "Agent"
	// WireMethods maps the generated Go method name (EmitBatch) to the wire
	// method name (emitBatch) recovered from processorMap key literals.
	WireMethods map[string]string
}

// Operation returns the storage-form operation object for a wire method.
func (s stubService) Operation(wireMethod string) string {
	return s.Scope + "." + s.Name + "/" + wireMethod
}

// stubIndex is pass 1 of the T19.3 rules: everything the consumer extractor
// knows after reading a repository's generated Thrift code.
type stubIndex struct {
	// Services keyed by service name. Duplicate service names across
	// packages would make name-based resolution ambiguous; the corpus has
	// none, and production abstains on duplicates.
	Services map[string]*stubService
	// methodOwners maps a generated Go method name to the service names
	// declaring it, for unique-match-or-abstain resolution.
	methodOwners map[string][]string
}

func newStubIndex() *stubIndex {
	return &stubIndex{
		Services:     map[string]*stubService{},
		methodOwners: map[string][]string{},
	}
}

// indexGeneratedFile applies the pass-1 rules to one generated Go file:
// service names come from `New<Service>Processor` constructor declarations,
// wire method names from `processorMap["m"] = ...` key literals in the same
// constructor body, and the Go method name is derived by upper-casing the
// wire name's first rune (the Apache Thrift Go generator's transform for the
// corpus's identifier shapes; underscored IDL names are a known ceiling
// recorded in the decision table).
func (index *stubIndex) indexGeneratedFile(pkgName string, content []byte) error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "generated.go", content, 0)
	if err != nil {
		return fmt.Errorf("parse generated file: %w", err)
	}
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if ok && fn.Recv == nil {
			match := processorCtorRe.FindStringSubmatch(fn.Name.Name)
			if match == nil {
				continue
			}
			service := index.ensureService(pkgName, match[1])
			for _, wire := range processorMapKeys(fn) {
				goName := upperFirst(wire)
				if _, exists := service.WireMethods[goName]; !exists {
					service.WireMethods[goName] = wire
					index.methodOwners[goName] = append(index.methodOwners[goName], service.Name)
				}
			}
		}
	}
	return nil
}

func (index *stubIndex) ensureService(scope, name string) *stubService {
	if existing, ok := index.Services[name]; ok {
		return existing
	}
	service := &stubService{Scope: scope, Name: name, WireMethods: map[string]string{}}
	index.Services[name] = service
	return service
}

// processorMapKeys collects string keys of `x.processorMap[...] = ...`
// assignments inside a function body.
func processorMapKeys(fn *ast.FuncDecl) []string {
	var keys []string
	ast.Inspect(fn.Body, func(node ast.Node) bool {
		assign, ok := node.(*ast.AssignStmt)
		if !ok {
			return true
		}
		for _, lhs := range assign.Lhs {
			indexExpr, ok := lhs.(*ast.IndexExpr)
			if !ok {
				continue
			}
			selector, ok := indexExpr.X.(*ast.SelectorExpr)
			if !ok || selector.Sel.Name != "processorMap" {
				continue
			}
			if literal := stringLiteral(indexExpr.Index); literal != "" {
				keys = append(keys, literal)
			}
		}
		return true
	})
	sort.Strings(keys)
	return keys
}

// consumerFinding is one pass-2 result for a scanned (non-generated) file.
type consumerFinding struct {
	Kind   string // "registration" | "call" | "ambiguous_call"
	Object string // service FQN, /scope.Service/method, or bare method name
}

// scanConsumerFile applies the pass-2 rules: walk call expressions; an exact
// `New<Service>Processor` callee is registration evidence, and a selector
// call whose method name maps to exactly one indexed service is caller
// evidence. Anything matching more than one service abstains.
func scanConsumerFile(content []byte, index *stubIndex) ([]consumerFinding, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "consumer.go", content, 0)
	if err != nil {
		return nil, fmt.Errorf("parse consumer file: %w", err)
	}
	seen := map[string]bool{}
	var findings []consumerFinding
	record := func(finding consumerFinding) {
		key := finding.Kind + "\x00" + finding.Object
		if !seen[key] {
			seen[key] = true
			findings = append(findings, finding)
		}
	}
	ast.Inspect(file, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		callee := calleeName(call.Fun)
		if callee == "" {
			return true
		}
		if match := processorCtorRe.FindStringSubmatch(callee); match != nil {
			if service, ok := index.Services[match[1]]; ok {
				record(consumerFinding{Kind: "registration", Object: service.Scope + "." + service.Name})
			}
			return true
		}
		// Method-shaped caller evidence requires a selector (x.Method(...))
		// with at least one argument, mirroring grpcgo.
		if _, isSelector := call.Fun.(*ast.SelectorExpr); !isSelector || len(call.Args) == 0 {
			return true
		}
		owners := index.methodOwners[callee]
		switch len(owners) {
		case 0:
		case 1:
			service := index.Services[owners[0]]
			record(consumerFinding{Kind: "call", Object: "/" + service.Operation(service.WireMethods[callee])})
		default:
			record(consumerFinding{Kind: "ambiguous_call", Object: callee})
		}
		return true
	})
	sort.Slice(findings, func(i, j int) bool {
		if findings[i].Kind != findings[j].Kind {
			return findings[i].Kind < findings[j].Kind
		}
		return findings[i].Object < findings[j].Object
	})
	return findings, nil
}

func calleeName(fun ast.Expr) string {
	switch node := fun.(type) {
	case *ast.Ident:
		return node.Name
	case *ast.SelectorExpr:
		return node.Sel.Name
	}
	return ""
}

func stringLiteral(expr ast.Expr) string {
	literal, ok := expr.(*ast.BasicLit)
	if !ok || literal.Kind != token.STRING || len(literal.Value) < 2 {
		return ""
	}
	return strings.Trim(literal.Value, `"`)
}

func upperFirst(name string) string {
	if name == "" {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}
