package typedindex

import (
	"bytes"
	"context"
	"errors"
	"strings"
	"testing"
)

func generatedFixture(t *testing.T) (GenerationBinding, PackageUnitID, GeneratedDocument, []byte) {
	t.Helper()
	_, _, request, _ := fixture(t)
	binding := GenerationBinding{Source: request.Source, RequestDigest: identity(request), ProfileDigest: request.ProfileDigest, ToolsDigest: request.ToolsDigest, PlanDigest: hash([]byte("sealed-plan"))}
	unit, err := NewPackageUnitID(hash([]byte("configured-command-proto-package-load")))
	if err != nil {
		t.Fatal(err)
	}
	// Synthetic reproduction of the sealed proto gap: the generated command.pb.go
	// needs independent byte custody; command.go's Git source cannot stand in for it.
	raw := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage command\ntype Command struct { Args []string }\n")
	doc, err := NewGeneratedDocument(context.Background(), binding, unit, "go/api/command/command.pb.go", hash([]byte("command.proto+pinned-protoc+sealed-action")), raw)
	if err != nil {
		t.Fatal(err)
	}
	return binding, unit, doc, raw
}

func TestGeneratedProtoGap(t *testing.T) {
	binding, unit, doc, raw := generatedFixture(t)
	ctx := context.Background()
	if err := VerifyGeneratedDocument(ctx, doc, binding, unit, raw); err != nil {
		t.Fatal(err)
	}
	if !IsGeneratedPath(doc.Path) || doc.Bytes != int64(len(raw)) || doc.Digest != hash(raw) || !strings.HasSuffix(doc.Path, "/go/api/command/command.pb.go") {
		t.Fatalf("descriptor lost generated source identity: %+v", doc)
	}
	if ReducedConfig().GeneratedDocuments != "omit" {
		t.Fatal("lane contract activated generated product navigation")
	}
	// The descriptor holds no caller-owned byte alias and corruption cannot pass.
	original := doc.Digest
	raw[0] ^= 1
	if doc.Digest != original || !errors.Is(VerifyGeneratedDocument(ctx, doc, binding, unit, raw), Invalid) {
		t.Fatal("mutated source accepted")
	}
	if !errors.Is(VerifyGeneratedDocument(ctx, doc, binding, unit, nil), Invalid) {
		t.Fatal("missing generated bytes accepted")
	}
}

func TestGeneratedAuthority(t *testing.T) {
	binding, unit, doc, raw := generatedFixture(t)
	other := hash([]byte("other"))
	cases := []struct {
		name string
		edit func(*GeneratedDocument)
		want error
	}{
		{"repository", func(d *GeneratedDocument) { d.Binding.Source.Repository = "example.test/other/repo" }, Stale},
		{"incarnation", func(d *GeneratedDocument) { d.Binding.Source.Incarnation = "repo-2" }, Stale},
		{"generation", func(d *GeneratedDocument) { d.Binding.Source.Generation = other }, Stale},
		{"HEAD", func(d *GeneratedDocument) { d.Binding.Source.Commit = strings.Repeat("b", 40) }, Stale},
		{"request", func(d *GeneratedDocument) { d.Binding.RequestDigest = other }, Stale},
		{"profile", func(d *GeneratedDocument) { d.Binding.ProfileDigest = other }, Stale},
		{"tools", func(d *GeneratedDocument) { d.Binding.ToolsDigest = other }, Stale},
		{"plan", func(d *GeneratedDocument) { d.Binding.PlanDigest = other }, Stale},
		{"unit", func(d *GeneratedDocument) {
			d.Unit, _ = NewPackageUnitID(other)
			d.Path, _ = GeneratedPath(d.Unit, "go/api/command/command.pb.go")
		}, Stale},
		{"missing provenance", func(d *GeneratedDocument) { d.ProvenanceDigest = "" }, Invalid},
		{"raw provenance", func(d *GeneratedDocument) { d.ProvenanceDigest = "/scratch/action" }, Invalid},
		{"missing binding", func(d *GeneratedDocument) { d.Binding = GenerationBinding{} }, Invalid},
		{"repository path", func(d *GeneratedDocument) { d.Path = "go/api/command/command.pb.go" }, Invalid},
		{"absolute producer path", func(d *GeneratedDocument) { d.Path = "/scratch/bazel-out/command.pb.go" }, Invalid},
		{"parent producer path", func(d *GeneratedDocument) { d.Path = "../bazel-out/command.pb.go" }, Invalid},
		{"path unit mismatch", func(d *GeneratedDocument) { d.Unit, _ = NewPackageUnitID(other) }, Invalid},
		{"digest", func(d *GeneratedDocument) { d.Digest = other }, Invalid},
		{"size", func(d *GeneratedDocument) { d.Bytes++ }, Invalid},
		{"negative size", func(d *GeneratedDocument) { d.Bytes = -1 }, Invalid},
		{"oversize", func(d *GeneratedDocument) { d.Bytes = MaxGeneratedBytes + 1 }, Invalid},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			changed := doc
			tc.edit(&changed)
			if err := VerifyGeneratedDocument(context.Background(), changed, binding, unit, raw); !errors.Is(err, tc.want) {
				t.Fatalf("got %v, want %v", err, tc.want)
			}
		})
	}
	if err := VerifyGeneratedDocument(context.Background(), doc, GenerationBinding{}, unit, raw); !errors.Is(err, Invalid) {
		t.Fatalf("invalid trusted binding: %v", err)
	}
}

func TestGeneratedNamespace(t *testing.T) {
	_, unit, _, _ := generatedFixture(t)
	prefixBytes := len(generatedNamespace) + 1 + 64 + 1
	limitPath := strings.Repeat("a", 200) + "/" + strings.Repeat("b", 512-prefixBytes-201)
	for _, logical := range []string{"command.pb.go", "生成/command.pb.go", limitPath} {
		name, err := GeneratedPath(unit, logical)
		if err != nil || !bundlePath(name) {
			t.Errorf("valid logical path refused: %q: %v", logical, err)
		}
	}
	if _, err := GeneratedPath(unit, limitPath+"b"); !errors.Is(err, Invalid) {
		t.Fatalf("513-byte generated path accepted: %v", err)
	}
	for _, logical := range []string{"", ".", "..", "../command.pb.go", "/command.pb.go", "a/../command.pb.go", "a//command.pb.go", "a/./command.pb.go", "a/", "a\\b.go", "C:command.pb.go", "a\x00.go", "a\n.go", "a\x7f.go", "a\xff.go", ".phebs-generated", ".phebs-generated/command.pb.go", strings.Repeat("a", 256), strings.Repeat("a/", 255) + "x"} {
		if _, err := GeneratedPath(unit, logical); !errors.Is(err, Invalid) {
			t.Errorf("accepted logical path %q: %v", logical, err)
		}
	}
	for _, name := range []string{".phebs-generated", ".phebs-generated/a", ".phebs-generated/../repo.go"} {
		if !IsGeneratedPath(name) {
			t.Errorf("namespace collision not reserved: %q", name)
		}
	}
	for _, name := range []string{"command.pb.go", "go/.phebs-generated/a", ".phebs-generated-other/a"} {
		if IsGeneratedPath(name) {
			t.Errorf("unrelated repository path reserved: %q", name)
		}
	}
	for _, bad := range []string{"", "//go/api:command", "service:command", "repository:command", "document:command.pb.go", "member:command.scip", "sha256:" + strings.Repeat("A", 64), string(unit)} {
		if _, err := NewPackageUnitID(bad); !errors.Is(err, Invalid) {
			t.Errorf("accepted non-digest unit identity %q", bad)
		}
	}
	for _, bad := range []PackageUnitID{"", PackageUnitID(hash([]byte("x"))), "package-load:sha256:bad", "package-load:package-load:sha256:bad"} {
		if _, err := GeneratedPath(bad, "command.pb.go"); !errors.Is(err, Invalid) {
			t.Errorf("accepted malformed unit %q", bad)
		}
	}
}

func TestGeneratedBoundsAndCancellation(t *testing.T) {
	binding, unit, doc, raw := generatedFixture(t)
	ctx := context.Background()
	for _, size := range []int{0, MaxGeneratedBytes, MaxGeneratedBytes + 1} {
		data := bytes.Repeat([]byte("x"), size)
		got, err := NewGeneratedDocument(ctx, binding, unit, "command.pb.go", doc.ProvenanceDigest, data)
		if size > MaxGeneratedBytes {
			if !errors.Is(err, Invalid) {
				t.Fatalf("oversized construction: %v", err)
			}
		} else if err != nil || VerifyGeneratedDocument(ctx, got, binding, unit, data) != nil {
			t.Fatalf("size %d did not round trip: %v", size, err)
		}
	}
	canceled, cancel := context.WithCancel(ctx)
	cancel()
	if _, err := NewGeneratedDocument(canceled, binding, unit, "command.pb.go", doc.ProvenanceDigest, raw); !errors.Is(err, context.Canceled) {
		t.Fatalf("construction ignored cancellation: %v", err)
	}
	if err := VerifyGeneratedDocument(canceled, doc, binding, unit, raw); !errors.Is(err, context.Canceled) {
		t.Fatalf("verification ignored cancellation: %v", err)
	}
	if _, err := NewGeneratedDocument(ctx, binding, unit, "command.pb.go", doc.ProvenanceDigest, nil); !errors.Is(err, Invalid) {
		t.Fatalf("missing source construction: %v", err)
	}
}
